### ISSUE TITLE
Split Client/Broker Code / reduce dependencies

### ISSUE THREAD

**Issue by patrickpracht** [dotnet/MQTTnet#1026]
### Description

I'm trying to integrate the MQTTnet server/broker into one of my asp.net core 3.1 projects and found out, that the MQTTnet nuget package has _tons_ of dependencies that I don't need (i.e. websockets, name resolution).

### Related to

- Client
- ManagedClient
- Server

### Describe the solution you'd like

Split out several dependencies into separate projects, so that one can leverage composition and reduce dependencies.

* split client/server
* move websocket stuff out
* move file system stuff out (message retention)

**Comment by chkr1011** [comment]
Hi, extracting the server from the core library is already planned for 3.1.x (but this might be not released released next summer). 

I am wondering where the "tons" of dependencies are coming from. I had a look at _MQTTnet.TestApp.NetCore_ which has, depending on the build target, 4, 7 or 14 external dependencies. Mostly these are .NET references. And the most are required when using _net461_. I added _netcoreapp3.1_ which "only" requires 7 libraries. These can be already reduced to 4 when _MQTTnet.Extensions.WebSocket4Net.dll_ is not used.

I agree that having a hard dependency to _Newtonsoft.Json.dll_ can also be omitted in the future by moving the storage to an official extension project.

**Comment by patrickpracht** [comment]
Appreciate your response. Looking forward to see the improvements.

By "tons of dependencies" I meant not only the top-level dependencies (these are indeed only a few), but also the sub-level.
For example, System.Net.WebSockets.Client brings in quite a few more dependencies which are likely never required in my particular project.

To shed some light: I want to receive messages, do some simple transformations on them, and pass them on via System.Threading.Channels. That's it.

**Comment by chkr1011** [comment]
Closing this for now because this change is planned but this will not happen soon.
