### ISSUE TITLE
Can IMqttClient instance be used for concurrent publishes?

### ISSUE THREAD

**Issue by colinmc86** [dotnet/MQTTnet#1068]
### Describe your question
Hello,

I am wondering if PublishAsync on IMqttClient can be called concurrently? If not, what is the recommended way of sharing these between threads?

Thanks,

Colin

### Which project is your question related to?

- Client

**Comment by chkr1011** [comment]
You should not access the client from multiple threads. But a simple lock (semaphore) is fine to mitigate this issues.

**Comment by colinmc86** [comment]
Hi @chkr1011 ,

Thanks for the response. If we should not use the client from multiple threads, what is the recommended way to use it? Creating a client each time we need one would be too much overhead, no (creating a connection, etc.. each time)?

**Comment by chkr1011** [comment]
You should create only one client and manage access to it via a lock or semaphore.

**Comment by colinmc86** [comment]
Thanks @chkr1011 . Last question, I think: can I do concurrent publishes without locking / semaphore if I am publishing qos 0 ?

**Comment by chkr1011** [comment]
I do not recommend it. It may work but is not officially supported.

**Comment by mpwillia** [comment]
@chkr1011 For clarity when you say 
> You should create only one client and manage access to it via a lock or semaphore.

Is that per thread? For example, could I have multiple clients created on their own threads all publishing messages where each thread publishes messages as you suggest, with a lock/semaphore between access of each client instance?

**Comment by chkr1011** [comment]
Locking each client instance works fine. Important is to not access the same client from different threads.
