### ISSUE TITLE
Unable to use WithUnsubscriptionInterceptor for server build options

### ISSUE THREAD

**Issue by deandob** [dotnet/MQTTnet#1077]
### Describe the bug
There is an interface defined for WithUnsubscriptionInterceptor for server build options however there is no delegate defined similar to WithSubscriptionInterceptor. This option isn't documented so its unclear how to use it, is it missing a delegate in the 
MQTTServerOptionsBuilder.cs like:
public MqttServerOptionsBuilder WithUnSubscriptionInterceptor(Action<MqttUnSubscriptionInterceptorContext> value)
        {
            _options.UnSubscriptionInterceptor = new MqttServerUnSubscriptionInterceptorDelegate(value);
            return this;
        }

### Which project is your bug related to?
- Server

### To Reproduce
var optionsBuilderEnc = new MqttServerOptionsBuilder()
    .WithUnsubscriptionInterceptor(????)
    .Build();

### Expected behavior
var optionsBuilderEnc = new MqttServerOptionsBuilder()
    .WithUnsubscriptionInterceptor(c => ServerUnSubscriptionInterceptor(c))
    .Build();

So its unclear how to hook into the unsubscribe from a client. Similar to #791

Also, while I'm here, 2 other questions if I may. 
What options do I have for the server to disconnecting a client session?
When a new message is received by the server, the object passed to the message received handler does not have access to the sessionitems, so I am using the message interceptor (which passes context which has access to sessionitems) and not bothering with doing anything in the message handler. Is there any problems with this approach (eg. using context.acceptPublish = false instead of e.ProcessingFailed in the message handler to flag a failure with processing the message)?

**Comment by SeppPenner** [comment]
Can you use the development package to test? This should be available from https://github.com/chkr1011/MQTTnet/issues/791 as stated by @chkr1011.

**Comment by deandob** [comment]
Link to the development branch? The only other active branch is feature/Server_Endpoint_API. Is there another repository?

**Comment by SeppPenner** [comment]
I guess, this should already be in the release, my mistake.

@chkr1011 Can you check this?

**Comment by deandob** [comment]
Sepp, while I have you, any insight into how to disconnect a connected client? Seems an obvious missing feature.

**Comment by SeppPenner** [comment]
> Sepp, while I have you, any insight into how to disconnect a connected client? Seems an obvious missing feature.

I'm not sure, but this seems to be not possible at the moment except with the `WithConnectionValidator` method while connecting: https://github.com/chkr1011/MQTTnet/wiki/Server#validating-mqtt-clients

**Comment by deandob** [comment]
Thanks, I will look at doing a pull request for this.

**Comment by serega404** [comment]
The problem described at the beginning is still relevant in version 3.1.2

**Comment by chkr1011** [comment]
Since version 4 there is an event called _InterceptingUnsubscriptionAsync_.
