### ISSUE TITLE
documention, managed client

### ISSUE THREAD

**Issue by fbd-ss** [dotnet/MQTTnet#1091]
Hi,
Ive setup the managed client message storage. I'm trying to get the client to republish the last message to the ui, but apart from manually resubscribing i cant get it to work. I was under the assumption that the managed client did this automatically.  What is the best way to get it to work as expected.

Use case, 
Before the app get put to sleep, the app disconnects from the client, and when the app resumes the app reconnects with the client, but i cant get a copy of the last published message.

Cheers.

**Comment by SeppPenner** [comment]
I'm not 100 percent sure, but I guess, you're looking for the `retain message` option. A good explanation (I found it very useful), is this: http://www.steves-internet-guide.com/mqtt-clean-sessions-example/.

**Comment by fbd-ss** [comment]
Hey Sepp, I have qos2 and retain set.  Steves internet guide is harder to read than the standard.  Which i never thought id say that about any standard.
Is there any decent documentation for the library?

**Comment by SeppPenner** [comment]
Maybe, https://github.com/chkr1011/MQTTnet/issues/1089 does help? I'm not really sure where the problem lies yet...

> Steves internet guide is harder to read than the standard. Which i never thought id say that about any standard.

Haha 😄 I really found it quite useful to be honest.

> Is there any decent documentation for the library?

It's in the code only, I had a documentation on the wiki page before, but keeping all the changes up to date there is a mess...

**Comment by fbd-ss** [comment]
I guess I'm just after the behavior of the managed client.

this the initial function the ui object uses to susbscribe to a topic

public async Task subscribe_async( IMqttTopicSubscription subscription_data ) {
	var topic = subscription_data.topic;

	if ( !_subscriptions.ContainsKey( topic ) ) {
		_subscriptions.Add( topic, new List<IMqttTopicSubscription>() );
	}

	await _mqtt_client.SubscribeAsync(
			new MqttTopicFilterBuilder()
				  .WithTopic( topic )
				  .WithQualityOfServiceLevel( (MqttQualityOfServiceLevel)subscription_data.qos_level )
				  .Build() );

	_subscriptions[ topic ].Add( subscription_data );
}


but i find myself having to do the following, see the foreach labeled "here"

private void setup_connected_handler() {
	_mqtt_client.UseConnectedHandler( async e => {

		_authenticate_result = e.AuthenticateResult;

		_log.Debug(
				"mqtt client connected. assigned id:{AssignedClientIdentifier}, session present:{IsSessionPresent}, max qos:{MaximumQoS}, retain available:{RetainAvailable}, server keep alive:{ServerKeepAlive}, wildcard available:{WildcardSubscriptionAvailable}, reason string:{ReasonString}, response info:{ResponseInformation}",
				e.AuthenticateResult.AssignedClientIdentifier,
				e.AuthenticateResult.IsSessionPresent,
				e.AuthenticateResult.MaximumQoS,
				e.AuthenticateResult.RetainAvailable,
				e.AuthenticateResult.ServerKeepAlive,
				e.AuthenticateResult.WildcardSubscriptionAvailable,
				e.AuthenticateResult.ReasonString,
				e.AuthenticateResult.ResponseInformation );

		foreach ( var handler in _connected_handlers ) {
			handler.Invoke();
		}

		############ here #############
		foreach ( var subscription in _subscriptions ) {
			await _mqtt_client.SubscribeAsync( subscription.Key );
			_log.Debug( "mqtt client subscribing to: {Key}", subscription.Key );
		}

		// save last good profile that could connect
		await _mediator.Send( new save_current_connection_profile_command( _profile ) );
	} );
}

apart from the initial subscribing, do i have to resubscribe each time the client is reconnected, if so what is the difference between managed and unmanaged clients?

I was under the assumption, given all other settings are correct that being managed once connected that the client would fire off the last message to all topics that were subscribed to via "_mqtt_client.UseApplicationMessageReceivedHandler". But htat isnt the case so i must be doing something wrong.  Any ideas

**Comment by fbd-ss** [comment]
documentation,  "It's in the code only".

Do you mean we have to figure out how the library works by going through the code or are there comments in the code?

**Comment by SeppPenner** [comment]
No, that's what the wiki is for. I was talking about the code comments that explain the methods exposed to the public.

**Comment by fbd-ss** [comment]
any comments on https://github.com/chkr1011/MQTTnet/issues/1091#issuecomment-780063888

**Comment by chkr1011** [comment]
Regarding the comments: This library does not explain MQTT as such. The library follows the naming scheme used in the official RFC so that you can read tutorials and documentation from other sources. These sources also contain best practices etc. A detailed documentation is not planned. There are some and the Samples directory contains more detailed information.

Regarding the difference between the Client and Managed Client: The managed client will reconnect automatically and subscribe automatically. It is also possible to publish even if the client is not connected yet. It will queue these messages and send them as soon as it is connected.
