### ISSUE TITLE
How to prevent ack on message consume failure

### ISSUE THREAD

**Issue by colinmc86** [dotnet/MQTTnet#1100]
Hello,

If I am consuming QOS 1 messages, and encounter an error consuming message, how can I prevent the message from being acked? If I have an uncaught exception inside of my client.UseApplicationMessageReceivedHandler handler will it redeliver ?

Thanks,

Colin

**Comment by chkr1011** [comment]
You can set _MqttApplicationMessageReceivedEventArgs.ProcessingFailed_ to true. Then no ACK will be sent.

**Comment by ramonsmits** [comment]
@chkr1011 Shouldn't that be the default when an exception is catched when QoS1 is requested?

So if you want QoS1 you need to do something like the following?

```c#
public async Task Handler(MqttApplicationMessageReceivedEventArgs arg)
{
    try
    {
        // Do your magic here
    }
    catch (Exception ex)
    {
        arg.ProcessingFailed = true;
        throw;
    }
}
```

**Comment by chkr1011** [comment]
I assume this question in properly answered.
