### ISSUE TITLE
Retrieve TCP Port From Server

### ISSUE THREAD

**Issue by awygle** [dotnet/MQTTnet#1102]
### Describe the feature request
I am trying to run automated tests which include an MQTTnet Server and Client. I'd like to run tests concurrently, so I don't want them to fight over TCP ports. I could use some kind of local connection (named pipe, Unix domain socket), but I don't see a backend for that. Thus I am using ephemeral TCP ports. I seem to be able to get a Server to claim a free port by passing 0 to `WithDefaultEndpointPort`, but there doesn't seem to be a way to retrieve the claimed port number from the Server so the Client knows what port to connect to.

### Which project is your feature request related to?
- Server

### Describe the solution you'd like
I think the best way to present this would be a property on Server which is called something like `ConnectedEndpoint`, which contains the port number, IP addresses, etc which end up actually being used by the Server.

### Describe alternatives you've considered
An alternative would be a local connection backend as described above, using something like named pipes on Windows or Unix domain sockets on Linux, so that the issue of TCP port contention never arises in the first place. That would be a separate feature request though.

### Additional context
None.

**Comment by chkr1011** [comment]
You can implement your own Server adapter via the adapter interface and handle connections via different transport protocols like named pipe etc.

**Comment by DanJBower** [comment]
This would be really helpful for me too. However, as a horrible short-term bodge, I was able to extract the port at runtime through reflection.

    ICollection<IMqttServerAdapter> adapters = _mqttServer.GetPrivateField<ICollection<IMqttServerAdapter>>("_adapters");
    List<MqttTcpServerListener> listeners = adapters.First().GetPrivateField<List<MqttTcpServerListener>>("_listeners");
    CrossPlatformSocket socket = listeners[0].GetPrivateField<CrossPlatformSocket>("_socket");
    Socket actualSocket = socket.GetPrivateField<Socket>("_socket");
    IPEndPoint addressInformation = (IPEndPoint)actualSocket.LocalEndPoint;

___

The code above used the following helper class to get the private field values.

    public static class ReflectionHelper
    {
        public static T GetPrivateField<T>(this object obj, string propName)
        {
            Type objectType = obj.GetType();
            FieldInfo fieldInfo = null;

            while (fieldInfo == null && objectType != null)
            {
                fieldInfo = objectType.GetField(propName, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                objectType = objectType.BaseType;
            }

            if (fieldInfo == null)
            {
                throw new ArgumentOutOfRangeException(nameof(propName),
                    $"Field {propName} was not found in Type {obj.GetType().FullName}");
            }

            return (T)fieldInfo.GetValue(obj);
        }
    }

**Comment by chkr1011** [comment]
In version 4 the used port is being written back to the Port property of the TCP options in the server. I also use this for Tests now so that the OS will choose the next free port.
