### ISSUE TITLE
Not possible to get license from within Visual Studio solution project

### ISSUE THREAD

**Issue by fkromer** [dotnet/MQTTnet#1114]
### Describe the bug

When listing the license URls of a Visual Studio 2019 solution I get a deprecation warning URL (https://aka.ms/deprecateLicenseUrl) for the license URL reference of MQTTNet v3.0.13. If I try to get the license instead I get nothing at all.

### Which project is your bug related to?

Meta-data

### To Reproduce

In Visual Studio 2019, open NuGet Package Manager, execute `Get-Package | Select-Object Id,LicenseUrl` or `Get-Package | Select-Object Id,License`.

### Expected behavior

An URL to the license file on GitHub or return of [package license expression](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file).

**Comment by SeppPenner** [comment]
I'm not sure, but for me the .nuspec file looks correct: https://github.com/chkr1011/MQTTnet/blob/master/Build/MQTTnet.nuspec.

**Comment by fkromer** [comment]
As far as I know `Get-Package | Select-Object Id,License` refers to the [`PackageLicenseExpression`](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file). That one is missing. However usually I'm a Linux citizen and only familiar with Windows stuff as long as I have to hassle around with. In this case I'm just digging into it.

**Comment by SeppPenner** [comment]
I'm not sure if this is supported within the *.nuspec file... Seems to be a tag that can be set in a project only. I will check this, however.
