### ISSUE TITLE
Client reconnecting does not work after network changes

### ISSUE THREAD

**Issue by niccolocapitelli** [dotnet/MQTTnet#1123]
Following a network change, the Mqtt client does not retry the connection to the broker and does not trigger the connection and disconnection callbacks. My setup includes a device (Mqtt client) connected to a network switch which is connected to a router. If I connect and disconnect the network cable from the switch, after a few attempts the mqtt client stops triggering the connection and disconnection callbacks. Analyzing the library code, it would seem that the workaround used as the CrossPlatformSocket timeout is not working properly.

**Comment by niccolocapitelli** [comment]
Hi, do you have any news regarding the issue? Do you need more details?.

**Comment by NikyCap91** [comment]
Looking at the library, the problem is within the class _CrossPlatformSocket_ inside _ConnectAsync_ method.

```
// Workaround for: https://github.com/dotnet/corefx/issues/24430
                using (cancellationToken.Register(() => _socket.Dispose()))
                {
                    cancellationToken.ThrowIfCancellationRequested();

#if NET452 || NET461
                    await Task.Factory.FromAsync(_socket.BeginConnect, _socket.EndConnect, host, port, null).ConfigureAwait(false);
#else
                    await _socket.ConnectAsync(host, port).ConfigureAwait(false);
#endif
                    _networkStream = new NetworkStream(_socket, true);
                }
```

It seems that the workaround does not work in this particular context and the _ConnectAsync_  gets stuck in the connection flow.
Do you have any news regarding the issue?

**Comment by chkr1011** [comment]
I am afraid we can fix this behavior in this library. Please try a .net 5+ etc. build of the application since the _ConnectAsync_ method accepts a cancellation token starting with that version.

If there are any other solutions or the bug still appears with the latest version please let me know.
