### ISSUE TITLE
Client is disconnected when unsubscribing from one of multiple subscribed topics

### ISSUE THREAD

**Issue by brettgman** [dotnet/MQTTnet#1127]
### Describe the bug
After subscribing to 2 topics, I then unsubscribe from one of them. Client is disconnected.  We're pretty sure the disconnect is not coming from our VerneMq broker

### Which project is your bug related to?

- ManagedClient

### To Reproduce
1. Using this version of MQTTnet '3.0.15'.
2. Connect and subscribe to 2 topics.  Then unsubscribe from one of them
3. Verify you have been disconnected

### Expected behavior
Don't be disconnected

**Comment by chkr1011** [comment]
Please test with the latest version of the library and reopen the ticket of the issue persists.
