### ISSUE TITLE
ManagedClient - Args returning from DisconnectedHandler

### ISSUE THREAD

**Issue by zenkraker** [dotnet/MQTTnet#1139]
### Describe the feature request
![MicrosoftTeams-image](https://user-images.githubusercontent.com/44246878/113844127-76dbc380-9794-11eb-87b2-4c8565415572.png)

Managed client does not return a useful error when bad password is used, it just return an error code 128 

### Which project is your feature request related to?
- ManagedClient

### Describe the solution you'd like
It would be nice to have a new error code with BadUsernameOrPassword which helps to identify this type of common error

**Comment by RalfMengwasser-ITEM** [comment]
This is one possible reason:

https://github.com/chkr1011/MQTTnet/issues/1148
