### ISSUE TITLE
Can not package MQTTnet into a .NET Core 3.1 library.

### ISSUE THREAD

**Issue by peterle188** [dotnet/MQTTnet#1142]
### Describe the bug
My requirement is to provide MQTT services in a dynamically loadable / unloadable assembly plug-in.

### Which project is your bug related to?
- ManagedClient

### To Reproduce
1. Using this version of Managed MQTTnet 3.0.15
2. Create a .NET Core 3.1 Library project and add Managed MQTTnet 3.0.15. 
3. Create a .NET Core 3.1 Console application and consume the above library project.
The code will not function without the library project being defined as a Console application with a main().

### Expected behavior
Expected the ability to package MQTT functionality into a Library and consume it elsewhere.

### Additional context / logging
Include debugging or logging information here:

```batch
\\ Put your logging output here.
```
### Code example
 Please provide full code examples below where possible to make it easier for the developers to check your issues.
 
```csharp
\\ Put your code here.
```

**Comment by chkr1011** [comment]
I assume the issue is solved.
