### ISSUE TITLE
Cannot access a disposed object on 'MqttChannelAdapter'

### ISSUE THREAD

**Issue by den130** [dotnet/MQTTnet#1146]
### Describe the bug
Hello,

We are using the managed client in a containerized linux arm32 image. (Embedded device)

MQTTnet.Extensions.ManagedClient = 3.0.15
ASP.NET core 3.1

After some time of running, the library seems to enter in this unrecoverable state.

```
2021-04-20 07:41:19:461warn: MQTTnet.Diagnostics.IMqttNetLogger[0]
      Error when sending request packet (MqttPublishPacket).
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MqttChannelAdapter'.
   at MQTTnet.Internal.Disposable.ThrowIfDisposed()
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttBasePacket packet, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.SendAndReceiveAsync[TResponsePacket](MqttBasePacket requestPacket, CancellationToken cancellationToken)
2021-04-20 07:41:19:579warn: MQTTnet.Diagnostics.IMqttNetLogger[0]
      Error when sending request packet (MqttPublishPacket).
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MqttChannelAdapter'.
   at MQTTnet.Internal.Disposable.ThrowIfDisposed()
   at MQTTnet.Adapter.MqttChannelAdapter.SendPacketAsync(MqttBasePacket packet, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.SendAndReceiveAsync[TResponsePacket](MqttBasePacket requestPacket, CancellationToken cancellationToken)
```

### Which project is your bug related to?
- ManagedClient

### To Reproduce
Repro steps not easy to describe, after some time it happen.

### Expected behavior
Auto recover is expected

### Additional context / logging
There are about 60 tasks that use the same IMAnagedMqttClient instance in parallel.

I implemented a parallel Task which calls the IMAnagedMqttClient.PingAsync on the same instance, and it is completing without any exception.

Also the IMAnagedMqttClient.PublishAsync is returning without any exceptions.

 When we are in this situation the library in not able to recover, even if the mqtt broker server is up and running. 

When we are in this situation the container starts to use all the available CPU, and the general load of the device grows.

When we restart the container (so also the IMAnagedMqttClient) all restart working.

I'm attaching MqttNet log (Debug level)
[mqttnet-logs.txt](https://github.com/chkr1011/MQTTnet/files/6343138/mqttnet-logs.txt)

Here how we are creating the IMAnagedMqttClient
```csharp
            var mqttClient = new MqttFactory().CreateManagedMqttClient(logger);

            var options = new ManagedMqttClientOptionsBuilder()
                .WithClientOptions(
                    new MqttClientOptionsBuilder()
                        .WithClientId(settings.ClientId)
                        .WithTcpServer(
                            settings.ServerUri.Host,
                            settings.ServerUri.Port)
                        .WithCredentials(
                            settings.Username,
                            password)
                        .WithKeepAlivePeriod(
                            TimeSpan.FromMilliseconds(
                            10000))
                        .WithCleanSession(true)
                        .Build())
                .WithAutoReconnectDelay(
                    TimeSpan.FromMilliseconds(200))
                .Build();

            await mqttClient.StartAsync(options);

```

**Comment by chkr1011** [comment]
Please try with the latest version of the library and reopen the ticket if the error is still there.
Also keep in mind that the clients are not thread safe.
