### ISSUE TITLE
MqttConnAckPacket is not properly handled and will spawn a random exception

### ISSUE THREAD

**Issue by RalfMengwasser-ITEM** [dotnet/MQTTnet#1148]
The code is missing the handling of the "MqttConnAckPacket", and everytime one is send the code instead spawns exceptions all over the place with no proper reason given.

Its basicly missing this:

else if (packet is MqttConnAckPacket connectPacket)
{
    await ProcessReceivedConnAckPacket(connectPacket).ConfigureAwait(false);
}

I fixed it for myself, to get proper disconnect messages with the correct reason as supplied by the server, for example if the server sends a protocol error or clientidinvalid. And if this library consisted of nice, structured C# I would have prepared a full fix and submitted it as an pull request (I tried).

But as the existing codebase is using exceptions for normal program flow instead of proper return values, there is no way I would ever be able to even *guess* what kind of exceptions I have to throw at which location in the code to correctly trigger the random exception handling machine we have here to produce the correct output.

Anyway. At least now you know of a bug. ;)

Sorry.

**Comment by chkr1011** [comment]
Please provide more information like the used library version and some sample code in order to reproduce the error.

If this issue persists with the latest version of the library, please reopen the issue.
