### ISSUE TITLE
Slow Client Connection to Mosquitto Broker from Microsoft Surface Pro

### ISSUE THREAD

**Issue by OleValler** [dotnet/MQTTnet#1152]
I am using MQTT.net (3.0.15) in a UWP app. My PC is connected to a Raspberry Pi 3A via simulated ethernet over USB using a static ip. The Raspi is running both a mosquitto broker and a GUI to receive and send messages to the app. The connection from the app to the device and vice versa is running absolutely fine when using my desktop pc: Messages are being exchanged instantly in both directions.

However, when I use the same application on a Microsoft Surface Pro 7, the connection from the app to the device is significantly slowed down (takes about 10-15 seconds untill a message is received, but the message is still received in the end). When the Raspi sends a message to the app, the speed remains near instantaneous.
I can fix this issue when disconnecting the surface from the wifi. When doing so, message are being exchanged instantly again.
The issue remains whether using MQTTv3.11 or MQTTv5.

Is there a way to prevent the client to look at different places than the the provided TcpServer address (which is the static ip of the Raspi)? Or what could be the problem?

### Which project is your question related to?
- Client

**Comment by chkr1011** [comment]
With the latest version you can specify the adapter IP in the options. This lets you choose which network adapter is used to create a connection with the server. It seems that, by default, the socket will use the WiFi connection instead which might be much slower. Please try and reopen this ticket if the error persists.
