### ISSUE TITLE
Client/Server example?

### ISSUE THREAD

**Issue by KevinBurton** [dotnet/MQTTnet#1154]
I looked at all of the samples and I could not see an example of a client/server pair.  Basically something as simple as the server echoing the client message would get me started.

**Comment by SeppPenner** [comment]
Hi, basically there is no such example right now, but the client and server side implementation is described under https://github.com/chkr1011/MQTTnet/wiki/Client and https://github.com/chkr1011/MQTTnet/wiki/Server. You can also have a look at the examples section under https://github.com/chkr1011/MQTTnet/wiki/Examples to get some inspiration.

**Comment by KevinBurton** [comment]
Thank you. I was just looking for a simple example where a client posts (publishes) some content to a server and the same content  shows up to another subscribing client. I see a method subscribeasync but how do I get content of a subscription? Thank you.

**Comment by SeppPenner** [comment]
@KevinBurton You need to subscribe first with https://github.com/chkr1011/MQTTnet/wiki/Client#subscribing-to-a-topic and then need to consume messages with https://github.com/chkr1011/MQTTnet/wiki/Client#consuming-messages.

Example (Not tested):

```csharp
mqttClient.UseApplicationMessageReceivedHandler(e =>
{
    Console.WriteLine("### RECEIVED APPLICATION MESSAGE ###");
    Console.WriteLine($"+ Topic = {e.ApplicationMessage.Topic}");
    Console.WriteLine($"+ Payload = {Encoding.UTF8.GetString(e.ApplicationMessage.Payload)}");
    Console.WriteLine($"+ QoS = {e.ApplicationMessage.QualityOfServiceLevel}");
    Console.WriteLine($"+ Retain = {e.ApplicationMessage.Retain}");
    Console.WriteLine();
});

await mqttClient.SubscribeAsync(new MqttTopicFilterBuilder().WithTopic("my/topic").Build());
```

So, you can handle the received messages in the `UseApplicationMessageReceivedHandler` callback.

**Comment by SeppPenner** [comment]
I guess, this is answered. If not, please re-open the issue.
