### ISSUE TITLE
Maintain Connection might continiously loop without any delays

### ISSUE THREAD

**Issue by ramonsmits** [dotnet/MQTTnet#1158]
### Describe the bug

I just looked at the managed client its maintain connection:

https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet.Extensions.ManagedClient/ManagedMqttClient.cs#L277-L280

Could it be that while the client remains connected that the while loop is continuously checking without any delays?

### Which project is your bug related to?

- ManagedClient

### Expected behavior

The loop that checks for connectivity should have a delay.

**Comment by chkr1011** [comment]
There is an implicit delay when the client still connected. See: https://github.com/dotnet/MQTTnet/blob/b0d1fcd161a2d6accb5a7784a155e5c62dfd6298/Source/MQTTnet.Extensions.ManagedClient/ManagedMqttClient.cs#L666-L669

The check interval is applied there. Not an elegant solution but it works.
