### ISSUE TITLE
mqttNet performance on larger messages

### ISSUE THREAD

**Issue by jesseemus** [dotnet/MQTTnet#1160]
### Receiving larger messages on mqttNet client is slow
When subscribing to a topic with a wildcard (+/topic) on broker (in our case moquitto), 
that has around 900 persistent messages with an average size of 180KB,
the performance of mqttNet client on receiving messages is horribly slow.

I started the project that has only the managed client in it subscribing to +/topic, and incrementing a counter on received messages.
After starting the project I also connected separate mqtt client software (mqtt.fx) to same broker and subscribed to same topic.
**For mqtt.fx it took approximately 12 seconds to receive all 900 messages from the broker.**

**meantime mqttNet client that was running at the same time had only received 40 messages.**

it looks like the ApplicationMessageReceivedHandler was firing approximately 3-4 times a second in this case.

I also tested with topics that have higher volume of messages but message size was smaller, there the performance of mqttNet and mqtt.fx was comparable.

### Which project is your bug related to?
- Client 
OR
- ManagedClient

**Comment by jesseemus** [comment]
There also seems to be frequent disconnections and OnSynchronizingSubscriptionsFailed firings when subscribing to the topic with large messages. this does not happen with "normal" topics

**Comment by jesseemus** [comment]
I have no in depth knowledge on the mqtt.fx tool, but what comes to connections both mqtt.fx and mqttNet are creating only single connection. other tools in addition to mqtt.fx are also providing great speeds, including NodeRed mqtt input node that I believe is using MQTT.js.

I was not aware that you could use multiple connections for single topic subscribe to improve performance, could you clarify what do you mean with it?

**Comment by jesseemus** [comment]
I did some further testing and added additional 200 retained messages to our broker that have average size of 4MB, now when subscribing with MQTTnet client I receive approximately 10 messages in same time where mqtt.fx receives 1000 messages.

**Comment by jesseemus** [comment]
Turns out this was Windows 10 configuration issue, running command : netsh int tcp set global autotuninglevel=normal
Fixed the issue.

**Comment by jesseemus** [comment]
I'm also getting comparable speeds to mqtt.fx with M2Mqtt library.

**Comment by jesseemus** [comment]
Running MQTTnet and M2MQTT side by side demonstrates this issue quite well, with large messages:

![image](https://user-images.githubusercontent.com/4483183/120534253-4c9c3000-c3ea-11eb-9012-eef7e37c35ca.png)

with smaller messages:

![image](https://user-images.githubusercontent.com/4483183/120534358-66d60e00-c3ea-11eb-84dc-ec14fed0c524.png)


numbers presented are the amount of received messages for each client.

**Comment by JanEggers** [comment]
can you provide a repro?

**Comment by chkr1011** [comment]
Please try again with the latest 4.0 preview from the nuget feed. Version 4 has lots of performance and memory improvements. You can also increase the internal buffer sizes in the options now. So if you usually send messages with 4 MB in size you can set the buffer size to 5 MB etc. If the problem still exists please reopen the ticket.

**Comment by kingsley91-cpu** [comment]
<img width="497" alt="Screenshot 2023-12-11 at 09 54 02" src="https://github.com/dotnet/MQTTnet/assets/152244941/30fbc948-f75b-4486-a074-3d3f264e167c">
@chkr1011 it worked as per your suggestion of increasing the internal buffer size

**Comment by chkr1011** [comment]
@kingsley91-cpu Do you have some measurements to share? I am interested in how much the performance has increased.
