### ISSUE TITLE
MQTTBroker.dll not found when run server in windows service

### ISSUE THREAD

**Issue by RalfKoch** [dotnet/MQTTnet#1163]
### Describe your question
I want to run a MQTT Server in a Windows Service.
I startet with .NET Framework 4.7.2 but the service did not start 'cause of a File not found Excpetion.
It did not say which one.
Changed the Framework to 4.6.1 and the error was more clear, MQTTBroker.dll not found even though it is there.
I do not know what I am missing here...
Or am I doing it wrong all together???

### Which project is your question related to?
- MQTTnet.Server standalone

**Comment by SeppPenner** [comment]
If you ask me, the latest version of the standalone MQTT server only works with .Net5: https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet.Server/MQTTnet.Server.csproj#L4.

**Comment by SeppPenner** [comment]
I can recommend https://github.com/SeppPenner/SimpleMqttServer as well as an example on how to run MqttNet as Windows service (Still, it uses NetCore / Net 6.0 by now).
