### ISSUE TITLE
Enable nullable context

### ISSUE THREAD

**Issue by touchofevil2** [dotnet/MQTTnet#1171]
### Describe the feature request
It would be great if we can enable nullable context for the libraries.

### Which project is your feature request related to?

- Client
- ManagedClient
- MQTTnet.Server standalone
- Server
- Generic

### Describe the solution you'd like
Enable C# nullable context. This would provide users with a good idea about the nullability expectations from the library.

**Comment by chkr1011** [comment]
This is planned but currently has low priority. So I will close this ticket for now.
