### ISSUE TITLE
Communication error instead of warning

### ISSUE THREAD

**Issue by yavapro** [dotnet/MQTTnet#1192]
### Describe the bug
In class MqttClientSessionsManager.cs on 107 line catch exception and write error. Some times i get logs with error like 'CONNECT packet must have at least 7 bytes.' or 'Expected at least 258 bytes but there are only 46 bytes'. There are created while MqttCommunicationException thrown.

I found some logic in class MqttClientConnection.cs on 239 line. But here we added checking:

```csharp
if (exception is MqttCommunicationException)
{
    _logger.Warning(exception, "Client '{0}': Communication exception while receiving client packets.", ClientId);
}
else
{
    _logger.Error(exception, "Client '{0}': Error while receiving client packets.", ClientId);
}
```

I suggest add checking in MqttClientSessionsManager like this:

```csharp
if (exception is MqttCommunicationException)
{
    _logger.Warning(exception, "Client '{0}': Communication exception while receiving client packets.", channelAdapter.Endpoint);
}
else
{
    _logger.Error(exception, "Client '{0}': Error while receiving client packets.", channelAdapter.Endpoint);
}
```

### Which project is your bug related to?
- MQTTnet.Server standalone

**Comment by chkr1011** [comment]
The standalone server is no longer part of this repository. Please open a ticket at https://github.com/chkr1011/MQTTnet.Server.
