### ISSUE TITLE
Memory leak with vb.net client?

### ISSUE THREAD

**Issue by radix50** [dotnet/MQTTnet#1215]
Hi All, 

I am using the VB.Net Client example from the Wiki here:
https://github.com/chkr1011/MQTTnet/wiki/Using-the-MQTT-client-in-VB.net

I am using a Windows forms application with .Net 4.7.2

I see gradually increasing memory usage according to how many messages are received.

Message volumes are low - say 1 - 5 messages per second

The problem occurs as soon as a topic is subscribed to - the messages can be ignored completely or output but the increase in memory usage is the same.

The problem is reproduced in the IDE, as a standalone .exe and on a different PC

Is anyone else using VB.Net as a client and seeing this issue??

Any help greatly appreciated, 

Robin

**Comment by chkr1011** [comment]
Do you also have the same issue when using C# instead for the same code? I don't think we can do anything about it because the library has no special VB-Switches at all.

**Comment by radix50** [comment]
Hi,  Thanks for getting back to me.

My C# isn't really up to trying it, I'm afraid - but I see the problem even when the MQTTnetMessageReceived handler is a dummy routine that just exits.  The private byes count just seems to gradually increase over time, starting under 20MB for my app and going over 200MB in a few days.  I am used to other stuff I have written with similar techniques running for literally months without this issue.

I also see an issue when receiving a VERY long status string generated by Zigbee2MQTT (I think around 22KB) in that it is truncated to about 13KB, naturally causing the JSON to not parse correctly...

**Comment by chkr1011** [comment]
Please try the latest version 4.0 and reopen this ticket if the issue persists.
