### ISSUE TITLE
I Want to send different messages to clients that are subscribed on the same topic,  Any way to filter the messages?  

### ISSUE THREAD

**Issue by wilari932** [dotnet/MQTTnet#1227]
### Describe your question
I want to publish a messages to certain clients, not all the clients.
that are subscribed to the same topic
i took a look on InterceptApplicationMessagePublishAsync but i dont find any way.

**Comment by SeppPenner** [comment]
What do you mean by **filtering**? Checking whether a client should be allowed to connect?

I would recommend to check https://github.com/chkr1011/MQTTnet/wiki/Server#validating-mqtt-clients, https://github.com/chkr1011/MQTTnet/wiki/Server#intercepting-application-messages and https://github.com/chkr1011/MQTTnet/wiki/Server#intercepting-subscriptions.

**Comment by wilari932** [comment]
> What do you mean by **filtering**? Checking whether a client should be allowed to connect?
> 
> I would recommend to check https://github.com/chkr1011/MQTTnet/wiki/Server#validating-mqtt-clients, https://github.com/chkr1011/MQTTnet/wiki/Server#intercepting-application-messages and https://github.com/chkr1011/MQTTnet/wiki/Server#intercepting-subscriptions.

I want to publish a messages to certain clients, not all the clients.
that are subscribed to the same topic
i took a look on InterceptApplicationMessagePublishAsync but i dont find any way. 
do you know if is possible if they are listening to the same topic? 
Topic:"Animals"
User A :  Payload :"Dog"
User B :  Payload :"Duck"

**Comment by SeppPenner** [comment]
I assume that this is not possible with MQTT... The idea with MQTT is that "groups" of clients which need the same information / send the same information are organized in sub-topics.

There are 2 scenarios as workaround I can think of:
1. Sub-topics for different clients, e.g. **topic 1**: `Animals/Dog` with message `something` and **topic 2**: `Animals/Duck` with message `something else`.
2. If you can influence the software running on the clients, you can exclude certain topics and / or payloads in the code there (Not really a good idea if you ask me).

**Comment by wilari932** [comment]
> I assume that this is not possible with MQTT... The idea with MQTT is that "groups" of clients which need the same information / send the same information are organized in sub-topics.
> 
> There are 2 scenarios as workaround I can think of:
> 
> 1. Sub-topics for different clients, e.g. **topic 1**: `Animals/Dog` with message `something` and **topic 2**: `Animals/Duck` with message `something else`.
> 2. If you can influence the software running on the clients, you can exclude certain topics and / or payloads in the code there (Not really a good idea if you ask me).

Thanks for your time it help a lot , have a nice day ! :)

**Comment by chkr1011** [comment]
I assume this question is answered.
