### ISSUE TITLE
More documentation about MqttClient `WithTopicFilter`

### ISSUE THREAD

**Issue by olicooper** [dotnet/MQTTnet#1255]
### Describe the feature request

Firs of all, thanks for all your hard work, this is a great library 👍

I was trying to get retained messages to be received on a client when I subscribed to the topic and it didn't work out-of-the-box. 
I tried adding the following but they didn't solve the issue:
* Adding `ClientOptions.WithCleanSession(false)` 
* Adding `ServerOptions.WithPersistentSessions()`
* Implementing `IMqttServerStorage` and `IMqttServerApplicationMessageInterceptor`

So I searched through the wiki and github issues etc to find out how to get it to work but couldn't find anything..
Eventually I found some additional parameters on `MqttClientSubscribeOptionsBuilder.WithTopicFilter` which allowed it to work, but I had to use trial and error to work out which ones were appropriate to set.

1. Could a few examples be provided on the wiki for this function beyond the basic configuration?
2. Could some comments also be added to the method for quick reference?
3. Can you explain here which parameters need setting `qualityOfServiceLevel`,`retainAsPublished`, `noLocal`,`retainHandling` for me to get the retained message when I subscribe (I seem to get the same message multiple times when `MqttQualityOfServiceLevel.ExactlyOnce` is set!?)

Thanks

### Which project is your feature request related to?

- Client
- Documentation

**Comment by chkr1011** [comment]
Thanks for your feedback. Unfortunately MQTT and its documentation etc. is not part of this project. This repository only covers the implementation of the protocol according to its specification. Best practices, or how the protocol works is not covered here and will never be covered. There are better places out there like _https://www.hivemq.com/mqtt-essentials/_ .
