### ISSUE TITLE
MqttClient topic `ExpiryInterval` not being set

### ISSUE THREAD

**Issue by olicooper** [dotnet/MQTTnet#1256]
### Describe the bug
I publish a message on a client with `Retain` set to true. The retained messages are processed in the broker and the `MessageExpiryInterval` is set to 60 when certain conditions are met. The retained messages are stored as JSON by the server:
```JSON
[{"Topic":"up/060fcc25/115","Payload":"Kw==","QualityOfServiceLevel":2,"Retain":true,"MessageExpiryInterval":60}]
```
When I subscribe to a topic, I receive the retained messages, but they don't have the `ExpiryInterval` set as expected. Is there a setting missing (for example do I need to implement `IMqttRetainedMessagesManager`) or is this a bug? I actually expected to not receive the message at all after the expiry lapsed.

Note: I am not able to set this on the client that publishes the message because this feature hasn't been implemented.

### Which project is your bug related to?
- Client
- Server

### To Reproduce

1. Create an Asp.NET 5 broker with a `InterceptApplicationMessagePublishAsync` which sets `context.ApplicationMessage.MessageExpiryInterval = 60;` when a message is received
2. Publish a message from client 1 with the `retain` flag set to true
3. Connect client 2 (after publishing from client 1) and subscribe to the topic
4. Receive the message on client 2 and observe no `ExpiryInterval`

**Comment by chkr1011** [comment]
These values are now being sent properly. Please test again with the latest version 4.
