### ISSUE TITLE
Design bug: IApplicationMessagePublisher doesn't distinguish publish success under QoS=0 from QoS=1

### ISSUE THREAD

**Issue by thovoll** [dotnet/MQTTnet#1259]
### Describe the bug
There is a design bug in [MqttClientPublishResult](https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Client/Publishing/MqttClientPublishResult.cs) and/or [IApplicationMessagePublisher](https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/IApplicationMessagePublisher.cs)

The current API returns MqttClientPublishResult from IApplicationMessagePublisher.PublishAsync, regardless of MqttApplicationMessage.QualityOfServiceLevel.

In case of QoS 0, this is confusing because the API returns MqttClientPublishResult.ReasonCode == MqttClientPublishReasonCode.Success, which is semantically different from the same result under QoS 1.

Under QoS 1, the client actually received a PUBACK from the broker with a success reason code. Under QoS 0, the client did not receive a PUBACK packet at all, and therefore no Reason Code.

The current design is convenient but misleading.

I did not look into QoS 2.

### Expected design
Differentiate QoS 0 publish success from QoS 1 publish success.

**Comment by chkr1011** [comment]
Which reason code would you expect there? The thing is that QoS 0 is "success" because "all relevant" steps are performed. You will get an exception if TCP connection is down etc. So from that point the "success" is fine in my opinion. And QoS 1 requires the ACK to be "successful". The client will also wait for the final ACK when using QoS 2.

**Comment by thovoll** [comment]
I admit this is a tricky API design question, and I don't have a ready-made solution. Some thoughts though...

Reason Code is an MQTT protocol concept, and a QoS 0 publish doesn't result in a Reason Code (because there is no PUBACK packet). So ideally, the publish API doesn't return a Reason Code for QoS 0 at all.

This probably means splitting the PublishAsync method into different methods by QoS (at least QoS=0 and QoS>0). This is already the case [one layer deeper in the code](https://github.com/chkr1011/MQTTnet/blob/0920c86d373cdce15efa27641c68bc468160c021/Source/MQTTnet/Client/MqttClient.cs#L240-L251).

Then, the proposed PublishQoS0Async can have a different return type than the other two. 

The design of PublishQoS0Async depends in part on the MQTT protocol spec, and in part how your library is designed independently of the MQTT protocol spec. Like you said above, the caller gets an exception when the TCP connection is down; this is not part of the MQTT protocol spec. I haven't fully surveyed the MQTT protocol spec to see all the ways a server can respond to a QoS 0 publish but I do know it **can't** send a PUBACK packet, and it seems it **can** send a DISCONNECT packet with a [reason code](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901208) like 149 (Packet too large).

I'm not sure how DISCONNECT packets are represented in your library, but an exception would probably make sense. This exception would have a Reason Code (which is different from a PUBACK Reason Code). At the end of the day, PublishQoS0Async might just return Task without a contained value and everything else is handled via exceptions.

Just my 2 cents...
