### ISSUE TITLE
Windows 7 Websocket PlatformNotSupportedException

### ISSUE THREAD

**Issue by charlesxj** [dotnet/MQTTnet#1260]
Use Websocket pattern,how to work well in  Windows 7 ?
now,my program work well in windows 10,but it run in windows 7, error is :Windows 7 Websocket PlatformNotSupportedException,
how to support windows7?

**Comment by chkr1011** [comment]
You can try to use the WebSocket implementation from WebSocket4Net (which is an extension library for MQTTnet). I added a sample in the sames directory.

**Comment by biancheng1000** [comment]
Can you be more specific?

**Comment by chkr1011** [comment]
In the samples app (see Samples directory) there is a sample called "Connect_Client_Using_WebSocket4Net". It shows how to use WebSocket4net.
