### ISSUE TITLE
How to use request response? I added withresponsetopic. Do I need to subscribe again? Do you have detailed instructions?

### ISSUE THREAD

**Issue by laolaolulu** [dotnet/MQTTnet#1264]
### Describe your question
A clear and concise description of what you want to know.

### Which project is your question related to?

- Client
- ManagedClient
- MQTTnet.Server standalone
- Server
- Generic

How to use request response? I added withresponsetopic. Do I need to subscribe again? Do you have detailed instructions?

**Comment by chkr1011** [comment]
The request response pattern is described here: https://www.hivemq.com/blog/mqtt5-essentials-part9-request-response-pattern/
