### ISSUE TITLE
Improve MqttClientConnectResultCode for userName==null, password!=null

### ISSUE THREAD

**Issue by milbrandt** [dotnet/MQTTnet#1269]
### Describe the bug

When upgrading to MQTTNet to avoid #1082 the observed MqttClientConnectResultCode.UnspecifiedError is unexpected.
For userName == null, password != null I would  have expected either a `MqttClientConnectResultCode.ProtocolError`, `ClientIdentifierNotValid` or `BadUserNameOrPassword`.

### Which project is your bug related to?

- Client

### To Reproduce

The unit test Use_Username_Null_Password_Empty was extended to test for the result code, see #1270.

### Expected behavior

A more specific ResultCode, preferable `MqttClientConnectResultCode.BadUserNameOrPassword` so that all invalid user/password combinations are covered by the same result code.

**Comment by chkr1011** [comment]
This issue is already fixed.
