### ISSUE TITLE
Huge Performance Difference according to previous versions

### ISSUE THREAD

**Issue by drony** [dotnet/MQTTnet#1278]
MqttNet **3.12** 1000 Message Receive Duration :**~14secs**
MqttNet **3.16** 1000 Message Receive Duration :**24secs**
Paho 1000 Message Receive Duration :~14secs
Xamarin 1000 Message Receive Duration :~14secs

_*each message package 8KB_
![Screenshot 2021-10-28 170125](https://user-images.githubusercontent.com/101887/139273769-06df8c31-aef6-4e39-afa1-481bc7431519.png)

**Comment by chkr1011** [comment]
This library often gets new features which may have an impact on performance as well. Maybe that is one possible reason. Please share more details how your comparison is made. Are you sending empty messages or is there more going on? 

Please try again with version 4.0.0 which will be published as a preview within the next weeks. The new version got a lot of performance improvements.

**Comment by chkr1011** [comment]
Please retry with the latest release and reopen this ticket if the problem still occurs.
