### ISSUE TITLE
Access Client Status In Client Disconnected Handler

### ISSUE THREAD

**Issue by ikbalkazanc** [dotnet/MQTTnet#1291]
### Question
```
public async Task HandleClientDisconnectedAsync(MqttServerClientDisconnectedEventArgs eventArgs)
{
    var client = await _server.GetClientStatusAsync().Result.Where(x=>x.ClientId == eventArgs.ClientId);
}
```
How can I access the client's status. In the above code "client" is null. at least access the session data?

### Which project is your question related to?

- Client
- MQTTnet.Server standalone
- Server

**Comment by chkr1011** [comment]
This will be implemented in version 4.1.
