### ISSUE TITLE
.NET 6 Support

### ISSUE THREAD

**Issue by anwarminarso** [dotnet/MQTTnet#1296]
### Describe the feature request
.NET 6 Support

### Which project is your feature request related to?
- MQTTnet
- MQTTnet.AspnetCore
- MQTTnet.Extensions.ManagedClient
- MQTTnet.Extensions.Rpc
- MQTTnet.Extensions.WebSocket4Net

**Comment by chkr1011** [comment]
Version 4.0 will have a dedicated build for .NET 6.0. But also the current version can be used together with .NET 6.0.

**Comment by chkr1011** [comment]
Very soon. You can already use previews from the MyGet feed.
