### ISSUE TITLE
Handle additional MQTT 5 features in version 4

### ISSUE THREAD

**Issue by logicaloud** [dotnet/MQTTnet#1301]
### Describe the feature request
Handle MQTT 5 features:
- SessionExpiryInterval
- MessageExpiryInterval
- WillDelayInterval
- Persisted Sessions

### Which project is your feature request related to?
- Server

### Describe the solution you'd like
I have implemented handling of the various intervals and also a persisted session extension point and related calls (for implementers to use their own storage to persist sessions) against branch `feature/Reason_Code_In_Subscription_Interceptor`. The interval handling is fairly concise, the persisted session extension is a bit more involved. There are overlaps with #1298. 

It would be nice if this implementation could find it's way into the project but at this point I'm uncertain how to proceed. I.e. wait for #1298 then look at the rest, separate out the interval handling into a pull request (additional merge work later), or wait for a solution from someone else who may be working on this to integrate later? Any advice appreciated.

### Describe alternatives you've considered
Any other solution will be fine.

### Additional context
Related to #805, #806, #1256.

**Comment by chkr1011** [comment]
These features will be implemented but not in 4.0 because otherwise 4.0 would never be released 😄 My plan is to finalize, test and document the current version 4.0 features first. The only thing which is left are finalization of persisted sessions.

**Comment by logicaloud** [comment]
No worries. I'll leave it for a while and check back when version 4 is out.

**Comment by chkr1011** [comment]
I will close this ticket as it covers multiple features. Please create one ticket per feature (a few are already out there).
