### ISSUE TITLE
MqttTopicFilterComparer not as internal

### ISSUE THREAD

**Issue by ddegasperi** [dotnet/MQTTnet#1306]
Hi,

it would be nice, if the class MqttTopicFilterComparer is not part of the internal namespace of the server, because it's very useful to check for matching topic also in the client when registering a generic message receiver listening on topic '#'

Example:

```
mqttClient.UseApplicationMessageReceivedHandler(e =>
{
    if (MqttTopicFilterComparer.IsMatch(e.ApplicationMessage.Topic, "myspecialtopic"))
    {
        // do some special logic here
    }
    else
    {
        // do other logic here
    }
});
```

The class seems to be moved with the new version 3.1.0 and the following [commit](https://github.com/chkr1011/MQTTnet/commit/cd8940f9b7cc7fc46c1465ae266aba6fdd2b546c#diff-215c548d9507bdf3516a3c239ae512133ced7593caaa11e8f7898badc885ca91)

I can of course use the class this way, but from the user's point of view it is not optimal to use internal classes. Please consider to move this class in another namespace.

**Comment by dagophil** [comment]
I'd love that as well. Matching the concrete message topic to a subscription seems to be relevant to all MQTT client users that subscribe to more than a single topic.

**Comment by chkr1011** [comment]
The topic filter comparer will be moved to the "public" area of this library in the next version 4.0.

**Comment by dagophil** [comment]
That's good news, thank you :)
