### ISSUE TITLE
Network protocol error for subscriptions is raised (after publishing)

### ISSUE THREAD

**Issue by Oliver-Piorun** [dotnet/MQTTnet#1310]
### Describe the bug
A network protocol error for ongoing subscriptions is raised after publishing a message to the server. The error cancels the subscriptions.

Platform:
- Windows 10
- Version: 21H2
- Build: 19044.1348

Client:
- Download: https://mosquitto.org/download/
- Version: 2.0.14

Server: 
- Download: https://github.com/chkr1011/MQTTnet/tree/master/Tests/MQTTnet.TestApp.AspNetCore2
- Version: 5e5818d7df78de6a0a1342c9dca692346f70ad97 (latest master)

**Important:** This issue is not only related to the test app. We also experience it in our server app.

### Which project is your bug related to?

- MQTTnet.Server standalone

### To Reproduce
1. Navigate to the `MQTTnet.TestApp.AspNetCore2` project directory
2. Remove the lines `88-92` in `Program.cs` (to make the app build and run)
3. Run the app via `dotnet run --framework net5.0`
4. Subscribe via `./mosquitto_sub -h localhost -p 1883 -t '#' -q 1`
5. Publish via `./mosquitto_pub -h localhost -p 1883 -t "test/foo" -m "message"`

### Expected behavior
We expect no network protocol error to occur (which cancels the subscription).

### Screenshots
Subscription:
![grafik](https://user-images.githubusercontent.com/15194243/145210677-08461c3b-423e-4666-bb80-7795e3bd4cd5.png)

Publish:
![grafik](https://user-images.githubusercontent.com/15194243/145210752-d842b908-4667-454f-814e-afa907bb5b2d.png)

### Additional context / logging
We found a couple of workarounds for this problem. The following commands avoid a network protocol error:
- `./mosquitto_sub -h localhost -p 1883 -t '#' -q 1 -i "client id"` or
- `./mosquitto_sub -h localhost -p 1883 -t '#' -q 1 -V 31` or
- `./mosquitto_pub -h localhost -p 1883 -t "test/foo" -m "message" -V 31`

So specifying a client id or the protocol version `31` helps. The protocol versions `311` (default) and `5` are faulty.
Using the MQTTnet client does also work btw.

Greetings!

**Comment by chkr1011** [comment]
Please test with latest version 4.0 and reopen the ticket if the issue persists.
