### ISSUE TITLE
How does MqttClient specify the network card to send data?

### ISSUE THREAD

**Issue by RalphLuo** [dotnet/MQTTnet#1311]
### Describe your question
When the server has multiple network cards, how does mqttclient specify the network card to send data?

### Which project is your question related to?
- Client

**Comment by chkr1011** [comment]
Please let me now if there is an API for .net sockets. If there is any API for this I can add them at the client options.

**Comment by RalphLuo** [comment]
Please refer to the following code.
![demo](https://user-images.githubusercontent.com/1762679/145739367-05f7e7f3-cb19-4469-9b99-ce8d8f4d0b14.png)

**Comment by RalphLuo** [comment]
> Please let me now if there is an API for .net sockets. If there is any API for this I can add them at the client options.

Can you add the client options?

**Comment by chkr1011** [comment]
I will add them. But please do not expect this feature within the next weeks. I will add it in version 4.0.

**Comment by chkr1011** [comment]
This is implemented and will be part of release 4.1.0.
