### ISSUE TITLE
.WithMaxPendingMessagesPerClient() vs retained messages

### ISSUE THREAD

**Issue by jkompis** [dotnet/MQTTnet#1315]
### .WithMaxPendingMessagesPerClient() vs retained messages
I have a MQTT server running with max pending messages per client set to 100.
I have a topic status/{variable}. This topic has more than 100+ retained messages.
I subscribe to the topic status/+ expecting all the 100+ messages to be received.
In reality I receive only 100 messages upon subscription.
I think that retained messages are upon subscription added into pending messages queue and thus also have to comply with max pending messages restriction.
As far as I understand retained message should be always received upon subscription no matter the QoS.
Is this intended? Is this a bug?

### Which project is your question related to?
- Server (MQTTnet 3.1.1)

**Comment by msavara** [comment]
I would also be interested in the answer to this question.

**Comment by chkr1011** [comment]
This is intended as these limits should protect the broker from high memory usage. I recommend to set this value high enough so that an expected amount of messages can be transferred without problems. If the MQTT spec has more details on this topic please let me know.

**Comment by chkr1011** [comment]
I assume this is answered.
