### ISSUE TITLE
MQTT broker does not receive all packets

### ISSUE THREAD

**Issue by pgogte** [dotnet/MQTTnet#1319]
I have 10 clients that transmit packets over zigbee (packet size 32 bytes) to a beagle bone black. Each client transmits a packet every 1 second. They all transmit 100 packets each. The beagle bone zigbee receives all the  1000 packets. The beagle bone blindly (without any processing) passes on the packet to the mqtt broker which is running on a i7, 4 core windows 10 machine. The message is published to a topic specific for each client (client/1, client/2 and so on).  There are no consumers clients for these topics as yet. I have put a counter in the mqtt message received handler to count the messages received. Of the 1000 messages only 550 +- 20 messages are counted by the message received handler on the broker. There is no error at either end (windows mcn or the beagle bone black). The remaining messages just seem to vanish.
If the same test is repeated with a 3 second interval between transmits from clients then the messages that are processed by the broker goes up to 850 +- 30.
How can I find out what is happening to the missing packets? I am not using managed client on the beagle bone black. Both the broker program on windows and the client program on beagle bone are using MQTTnet c#.
The Message received handler is doing nothing, it just increments the counter and spits it out to the control. I even tried to pump the messages into a concurrentque as soon as it is received and do the counting and printing in a separate thread. Still no luck.

**Comment by GieltjE** [comment]
How are you incrementing the counter? In c# you need to be carefull with high speed increment/updates.

**Comment by chkr1011** [comment]
I close this ticket due to inactivity.
