### ISSUE TITLE
.NET 6 ManagedClient floods the AppDomain with Tasks and UnobservedTaskException is being thrown

### ISSUE THREAD

**Issue by npehrsson** [dotnet/MQTTnet#1327]
### Describe the bug
Flooded with _UnobservedTaskException_ 
_A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The operation has timed out.)_
The underlying exceptions seems to be a System.TimeoutException.

### Which project is your bug related to?

- ManagedClient

### To Reproduce
1. I have only been able to reproduce this in our Azure environment.
2. The environment current application has no load at all, just sends a message, and then it starts.
2. Using ManagedClient with version 3.0.16 or 3.1.1
2. Use .NET 6.01.
2. Observe _TaskScheduler.UnobservedTaskException_
3. Connect and send a message (do not set up any subscriptions)

### Expected behavior
When sending a message within a couple of minutes _UnobservedTaskException_ starts to be thrown.
There is no usage at all after been sending the first message.
Not sure if it's sending the message or just making the connection happen.
When using only the MqttClient with an open connection we do not see this behavior.
So if not using ManagedClient we can't see the behavior, and with this, it starts.

### Screenshots
This is a small capture of the Task list when taking a memory dump
![image](https://user-images.githubusercontent.com/3260533/148405490-fc3f686b-75f4-454f-ba8d-0d1b95067df0.png)
All the tasks have the current stack trace.
![image](https://user-images.githubusercontent.com/3260533/148405667-6a7acb73-ac5f-4236-8956-041a5e2d4ddc.png)

### Additional context / logging
The Web App in Azure is using the same Azure App Service Plan with another Web App, which is Task heavy so there could be high competition of the thread pool.

### Code & Configuration
            var messageBuilder = new MqttClientOptionsBuilder()
                .WithClientId(clientId)
                .WithTcpServer(mqttOptions.Uri, mqttOptions.Port)
                .WithKeepAlivePeriod(TimeSpan.FromSeconds(60))
                .WithCleanSession();

            var managedOptions = new ManagedMqttClientOptionsBuilder()
                .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
                .WithClientOptions(options)
                .Build();

**Comment by npehrsson** [comment]
``

**Comment by npehrsson** [comment]
This is the log, from MqttNetLogger, not much I'm afraid.

<html>
<body>


1/10/2022, 8:40:20.046 PM | Started |  
-- | -- | --
  | 1/10/2022, 8:40:20.106 PM | Trying to connect with server 'dev-vm-mqtt.westeurope.cloudapp.azure.com:8883' (Timeout=00:00:10). |  
  | 1/10/2022, 8:40:20.968 PM | Connection with server established. |  
  | 1/10/2022, 8:40:21.029 PM | Start receiving packets. |  
  | 1/10/2022, 8:40:21.121 PM | Authenticated MQTT connection with server established. |  
  | 1/10/2022, 8:40:21.121 PM | Connected. |  
  | 1/10/2022, 8:40:21.140 PM | Publishing subscriptions at reconnect |  
  | 1/10/2022, 8:40:21.171 PM | Publishing 6 added and 0 removed subscriptions |  
  | 1/10/2022, 8:40:21.999 PM | Start sending keep alive packets.

**Comment by npehrsson** [comment]
Probably found the solution.

My current version of .NET 6 locally is 6.0.100 (x64), the current one on our Azure Web Apps is 6.0.0 (x86), when selecting the self-contained option so the version is forced to 6.0.100 (x86) the problem goes away.

However, I believe when looking at some data I've received during the triage I could see traces that  StartPublishing(); has been called multiple times and that there is some starvation on BlockingCollection.

Not sure it's worth it to chase a bug that is only being seen in .NET 6.0.0 when there is a new version.
Apart from the image below I could see many tasks in the same stack trace from StartPublishing to the Wait in the BlockingCollection, this is also the only place I could see that the reference to the task was abandoned.
![image](https://user-images.githubusercontent.com/3260533/148859728-5069b864-6015-412b-9699-261912b24767.png)

**Comment by npehrsson** [comment]
Follow up, I took a memory dump, there are still lots of tasks being waited for.
However they are not timing out

**Comment by yyjdelete** [comment]
@npehrsson 
The `TimeoutException` is already reported as https://github.com/dotnet/runtime/issues/60856, and should already(https://github.com/dotnet/runtime/pull/61491) be fixed in 6.0.1

**Comment by SeppPenner** [comment]
@npehrsson Can you check this with Net 6.0.1 again, please?

**Comment by npehrsson** [comment]
As I confirmed in my previous comment with version 6.0.100 the unhandled TimeoutExceptions are gone.
However, I noticed that their ManagedMqttClient creates a lot of Tasks waiting.

I assume this issue can be closed

**Comment by SeppPenner** [comment]
> As I confirmed in my previous comment with version 6.0.100 the unhandled TimeoutExceptions are gone. However, I noticed that their ManagedMqttClient creates a lot of Tasks waiting.
> 
> I assume this issue can be closed

Uups, sorry. I missed your statement there...

> Not sure it's worth it to chase a bug that is only being seen in .NET 6.0.0 when there is a new version.


I will close the issue :)
