### ISSUE TITLE
Keep alive does not seem to work for Client with AWS

### ISSUE THREAD

**Issue by onedumbtrucker** [dotnet/MQTTnet#1328]
### Describe your question
I have tried setting both WithKeepAlivePeriod and WithKeepAliveSendInterval and I may be misunderstanding how this works with AWS IoT Core but my devices never show as connected despite successfully provisioning and regularly publishing data to my endpoint.

Not sure if I am using the Client or ManagedClient. My application is based off the application example here https://github.com/aws-samples/aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4
using websockets and sigv4

### Which project is your question related to?

- Client
- ManagedClient
- Generic

**Comment by chkr1011** [comment]
Please try with latest version 4 and reopen this ticket if the error persists. There is no special AWS handling in this library. What exactly is the issue with keep alive? Does AWS disconnect and claims that a PINREQ was not sent from the client?
