### ISSUE TITLE
Error in overload definition of ConnectAsync

### ISSUE THREAD

**Issue by ilgrank** [dotnet/MQTTnet#1331]
### Describe the bug
The Overload definition of the client **ConnectAsync** method reports:
`System.Threading.Tasks.Task[MQTTnet.Client.Subscribing.MqttClientSubscribeResult] SubscribeAsync(MQTTnet.Client.Subscribing.MqttClientSubscribeOptions options, System.Threading.CancellationToken cancellationToken)`
but when calling ConnectAsync  with the two arguments (MqttClientSubscribeOptions and CancellationToken ) the method fails with an error.

### Which project is your bug related to?

- Client

### To Reproduce

1. Using this version of MQTTnet: '3.11'
2. Run this code: (Powershell)

```
Add-Type -Path "C:\temp\MQTTnet.dll"
$Factory=[MQTTnet.MqttFactory]::new()
$MqttClient=$Factory.CreateMqttClient()
$Options=[MQTTnet.Client.Options.MqttClientOptionsBuilder]::new().WithClientId('TestClient').WithTcpServer('test.mosquitto.org').WithCleanSession().Build()
$SO=[MQTTnet.Client.Subscribing.MqttClientSubscribeOptions]::new().TopicFilters=[MQTTnet.TopicFilterBuilder]::new().WithTopic('$SYS').Build()
$MqttClient.ConnectAsync($options, [System.Threading.CancellationToken]::None)
$MqttClient.SubscribeAsync($SO, [System.Threading.CancellationToken]::None)

```
3. With these arguments: none.
4. error:
`Cannot find an overload for "SubscribeAsync" and the argument count: "2".`

### Expected behavior
The client should subscribe to the topic

### Screenshots
n.a.

### Additional context / logging
n.a.
### Code example
see above 

The client gets created correcly, and connects fine.
The problem arises when using the SubscribeAsync method even when following literally the overload definition.

**Update**
following the suggetion here: [https://github.com/dotnet/MQTTnet/issues/849#issuecomment-593066981](https://github.com/dotnet/MQTTnet/issues/849#issuecomment-593066981)
I also tried feeding ConnectAsync a list:
```
Add-Type -Path "C:\temp\MQTTnet.dll"
$Client=[MQTTnet.MqttFactory]::new().CreateMqttClient()
$Options=[MQTTnet.Client.Options.MqttClientOptionsBuilder]::new().WithClientId('TestClient').WithTcpServer('test.mosquitto.org').WithCleanSession().Build()
$Client.ConnectAsync($options, [System.Threading.CancellationToken]::None)

$TFList=[System.Collections.Generic.List[[MQTTnet.TopicFilter]]]::new()
$TFList.Add(([MQTTnet.TopicFilter]@{topic='$SYS'}))
$SO=[MQTTnet.Client.Subscribing.MqttClientSubscribeOptions]::new().TopicFilters=$TFList
$Client.SubscribeAsync($SO) <-Fails
$Client.SubscribeAsync($SO,[System.Threading.CancellationToken]::None) <-Fails too

```
in that tread it also has been suggested to just use:
`$Client.SubscribeAsync($TSList) `
but it fails too

**Comment by ilgrank** [comment]
The problem seems related on how Powershell passes the TopicFilterList (expected as an Enumerable).
The code below works, should anyone need it the future:
```
Add-Type -Path "C:\temp\MQTTnet.dll"
$MQTTClient=[MQTTnet.MqttFactory]::new().CreateMqttClient()
$ClientOptions=[MQTTnet.Client.Options.MqttClientOptionsBuilder]::new().WithClientId('TestClient').WithTcpServer('test.mosquitto.org').WithCleanSession().Build()
$MQTTClient.ConnectAsync($ClientOptions, [System.Threading.CancellationToken]::None)
$TopicFilters=[System.Collections.Generic.List[MQTTnet.TopicFilter]]::new()
$TopicFilter=[MQTTnet.TopicFilter]::new()
$TopicFilter.Topic='$SYS'
$TopicFilters.Add($TopicFilter)
$SubscribeOptions=[MQTTnet.Client.Subscribing.MqttClientSubscribeOptions]::new()
$SubscribeOptions.TopicFilters=$TopicFilters
$MQTTClient.SubscribeAsync($SubscribeOptions,[System.Threading.CancellationToken]::None)
```
one of the things I was not understanding is that 
`[MQTTnet.TopicFilterBuilder]::new().Build() `produces an object of type `[MqttTopicFilter]`
while
`[MQTTnet.TopicFilter]::new()` produces a `[TopicFilter]`

**Comment by chkr1011** [comment]
There are currently two types of there classes in the library. _MqttTopicFilter_ is the correct one. _TopicFilter_ is an old one which is already marked as obsolete due to wrong naming style (Mqtt was missing). _TopicFilter_  derives from _MqttTopicFilter_  to that they are compatible but _TopicFilter_  will be removed soon.
