### ISSUE TITLE
Handle Json subscribed message in Xamarin from Shelly device

### ISSUE THREAD

**Issue by nicomara** [dotnet/MQTTnet#1332]
Hi guys, I've tried to display in xamarin.forms client project a subscribed message from Shelly 1 device, I'm not sure if this is the problem, but I can't show the device's status using the **ApplicationMessage** class, this is because the response **message's format is Json**? Otherwise how could I manage it to show user this payload? 

### Which project is your question related to?

- Client

**Comment by chkr1011** [comment]
The payload is transmitted as a plain byte array so you have to convert it so a string first. Then you can parse the string as a JSON document. You can either use _Encoding.UTF8.GetString()_ or the extension method _ConvertPayloadToString_ on _MqttApplicationMessage_ from this library.

**Comment by nicomara** [comment]
You're right, I've alreay tried the method _ConvertPayloadToString_, but I always failed. I'm looking for other problems because in Debug I've found _UseApplicationMessageReceivedHandler_ didn't catch any _ApplicationMessage_ and this is strange, I will check again about Shelly Mqtt Support docs, maybe something wrong in topic subscribed or the device is not publishing data to broker (I'm using the free one of Mosquitto to test it). If you have any other hint for me is a pleasure.
Thank you

**Comment by SeppPenner** [comment]
You can use http://www.mqttfx.jensd.de/ (Go to `downloads` and use one of the "old" downloads, the latest version is maintained by a company and costs some euros) to check your payloads that occur on the MQTT server. There, you can switch to JSON display and see if the data is correct JSON or not. If it's not JSON, you can see the raw bytes as well. I hope, this helps a bit for debugging.

In general, Shelly should work with MQTT (I have a test device as well and it's spamming the MQTT broker with messages 😅 ).

**Comment by nicomara** [comment]
Thank you for the useful suggest, I'm going to try it just because it's very interesting, but I would share with you that I've found that I didn't receive a message from the Api _shellies/<model>-<deviceid>/relay/0_ like described in the docs to report the status,  only subscribing the _announce_ topic I can handle a _ApplicationMessage_ with its payload.
Probably I'm missing a step, I'm looking for it, sorry but like you realized I'm a beginner on it.

**Comment by chkr1011** [comment]
There is also a release available for _MQTTnetApp_ (https://github.com/chkr1011/MQTTnetApp) which is a MQTT tool built around this library. @SeppPenner I will add a reference to our wiki that this tool can be used to debug packets and test if the library has an issue or the user code.
