### ISSUE TITLE
Apache ActiveMQ connection Exception

### ISSUE THREAD

**Issue by nazzour** [dotnet/MQTTnet#1333]
### Describe the bug
I am trying to connect to Apache ActiveMQ (mqtt) using MQTTnet. I installed an Apache ActiveMQ docker and I just instantiated a simple client using the code below. My ActiveMQ does not have any user/password. When I start my test I get an MQTTnet.Adapter.MqttConnectingFailedException
The code is really very simple and basic but it did not work

### Which project is your bug related to?

- Client

### To Reproduce
1. Using this version of MQTTnet '4.0.0'.

### Expected behavior
Connect to ApacheActiveMQ

### Additional context / logging

```
MQTTnet.Adapter.MqttConnectingFailedException: 'Error while authenticating. Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.'

InnerException
MqttCommunicationTimedOutException: Exception of type 'MQTTnet.Exceptions.MqttCommunicationTimedOutException' was thrown.

```
### Code example
 
```csharp
// Create a new MQTT client.
var factory = new MqttFactory();
var mqttClient = factory.CreateMqttClient();
// Create TCP based options using the builder.
var options = new MqttClientOptionsBuilder()
    .WithTcpServer("127.0.0.1", 1883)
    .Build();
await mqttClient.ConnectAsync(options, CancellationToken.None); 
```
PS: I am getting the same issue with Mosquitto
Any help please

**Comment by chkr1011** [comment]
Thanks for testing version 4.0.0 and reporting feedback.
To me it looks like a address issue. The exception indicates that the endpoint is not reachable. Thus the _MqttCommunicationTimedOutException_. "'Error while authenticating." is a bit misleading here because connecting on TCP level is also part of the authentication.

**Comment by nazzour** [comment]
Thanks @chkr1011 , I just confirmed that it was a broker issue. thanks
