### ISSUE TITLE
Request: Add documentation and examples for 4.0 release

### ISSUE THREAD

**Issue by ilgrank** [dotnet/MQTTnet#1334]
Hi
I'm new to MQTTnet, but the fact that have been so many changes between 3.x and 4.x releases doesn't help, as the docs and examples don't seem to be updated.

 I could stick to the 3.x branch for now, but given the upcoming changes, I find It would be more efficient to just develop for 4.0 instead
Thanks!

**Comment by chkr1011** [comment]
Please check the _Samples_ directory in branch _feature/Reason_Code_In_Subscription_Interceptor_. The WiKi will be reduced to text only for future versions. Then all sample code is part of the samples directory. It is also supported to execute those samples.

**Comment by SeppPenner** [comment]
> The WiKi will be reduced to text only for future versions.

That would be a really good idea. It's nearly impossible to keep the Wiki up-to-date with the code changes...

**Comment by chkr1011** [comment]
I close this ticket because version 4.0 is finally released. New samples including documentation are available in the _Samples_ directory. If you are missing something please let us know.
