### ISSUE TITLE
Reset ManagedClient password in disconnect handler

### ISSUE THREAD

**Issue by nikeshkrishnan** [dotnet/MQTTnet#1341]
### Describe your question
Hi,
In my use case, the ManagedClient's password is an authentication token that has an expiry time. So, I wanted to know if there is a way to reset the ManagedClient's password in the  Disconnection handler, without actually having to rebuild the client options and restart the client again. 
### Which project is your question related to?

 
- ManagedClient

**Comment by SeppPenner** [comment]
I don't believe that this is possible.

**Comment by nikeshkrishnan** [comment]
> I don't believe that this is possible.

what is your opinion about putting a setter for IMqttClientCredentials in the library code? I am working on a very hardware-constrained system, so if there is any way by which I could bypass restarting the entire ManagedClient it would be greatly helpful.

**Comment by chkr1011** [comment]
The credentials can also be set via the interface _IMqttClientCredentials_. There you can implement your own credentials provider which will return a different password in the getter as needed.

**Comment by nikeshkrishnan** [comment]
> _IMqttClientCredentials_.

if

> The credentials can also be set via the interface _IMqttClientCredentials_. There you can implement your own credentials provider which will return a different password in the getter as needed.

if this is done when the managed MQTT client resets the   connection(when the internet comes back up again) will the updated password be used to reinitiate the connection

**Comment by chkr1011** [comment]
I assume this question is answered. If not please reopen the ticket.
