### ISSUE TITLE
How to close a specified client connection in Server

### ISSUE THREAD

**Issue by francescoz-devtek** [dotnet/MQTTnet#1346]
### Describe your question
I want to close the connection of the specified client in Server, but I can't find any method related.
Any suggestion?

### Which project is your question related to?
- Server

**Comment by bxb-l** [comment]
I also want to know!

**Comment by SeppPenner** [comment]
This depends on when you want to close the connection. I guess, https://github.com/dotnet/MQTTnet/wiki/Server#validating-mqtt-clients is not what you're searching for?

**Comment by SeppPenner** [comment]
Is this answered with my message above or not?

**Comment by chkr1011** [comment]
There is an API for it. You can make a call like _(await _server.GetClientsAsync())[0].DisconnectAsync();_ I will also add a new sample for this.
