### ISSUE TITLE
4.0 preview releases missing strong name signatures

### ISSUE THREAD

**Issue by GieltjE** [dotnet/MQTTnet#1349]
### Describe the bug
The 4.0 preview builds are missing the strong name signatures making it impossible to use with strong named release builds.

### Which project is your bug related to?
- Client
- ManagedClient

**Comment by chkr1011** [comment]
Thanks for your feedback. The build CI now creates assemblies with a strong name. Please test the latest preview nuget.

**Comment by GieltjE** [comment]
Thnx, they work just fine
