### ISSUE TITLE
Removal of SpanBasedMqttPacketWriter & Reader

### ISSUE THREAD

**Issue by chkr1011** [dotnet/MQTTnet#1352]
Version 4 has some optimizations in the area of allocations and memory management. Thus I had to change the _MqttPacketWriter_. I saw that @JanEggers created a custom one based on _Span<>_ in the past _SpanBasedMqttPacketWriter_. 

I did a benchmark and, to my surprise, the old one seems to perform better. So my goal is to get rid of the Span based on in the next release to reduce complexity. 

![image](https://user-images.githubusercontent.com/6939810/153475548-4f54b2d2-f864-4dd3-af10-eb011ee22b94.png)

Benchmark code:
https://github.com/dotnet/MQTTnet/blob/298f8cae0c0bffda2793d5bc6062e80c372fdc81/Source/MQTTnet.Benchmarks/MqttPacketWriterBenchmark.cs#L39-L55

I you (@JanEggers ) don't mind I will remove the writer and (after doing another benchmark) reader from the ASP extension. If there are any other reasons for having two separate ones please let me know.

**Comment by JanEggers** [comment]
@chkr1011 the whole point was to optimize memory usage and throughput. if the default is now better than the span based remove the span based one. maybe have a look at the existing benchmarks I just looked at them and was not sure which one i used to compare.
