### ISSUE TITLE
The connection with TLS to the Mosquitto Broker will take 10+ seconds.

### ISSUE THREAD

**Issue by woojunfeng** [dotnet/MQTTnet#1354]
### Describe the bug
The connection with TLS to the Mosquitto Broker will take 10+ seconds.

### Which project is your bug related to?
- Client

### To Reproduce
1. Using this version of MQTTnet 4.0 and 3.1.2 .

**Comment by woojunfeng** [comment]
@chkr1011 yes, it is connected after 10+ secs,and working well.
Mosquitto is looped at `SSL_DATA_PENDING` function.
I can't tell which part is wrong,maybe .NET or Mosquitto.

Mosquitto Broker must set the TLS config. I was using self_signed_cert(made by OPENSSL) for the broker and .Net client

**Comment by woojunfeng** [comment]
Mqtt.js in Node.js connected immediately  (the same TLS cert)

**Comment by woojunfeng** [comment]
there may be something wrong with my computer.
it run well on other PC.
:(

**Comment by SeppPenner** [comment]
@woojunfeng Can we close the issue since it doesn't seem to be a problem of MQTTnet?

**Comment by SeppPenner** [comment]
I will close the issue now as unrelated to the library. Feel free to re-open it if there is more insight :)
