### ISSUE TITLE
Could not load file or assembly 'MQTTnet, Version=3.1.2.0

### ISSUE THREAD

**Issue by ivanrlg** [dotnet/MQTTnet#1356]
### Describe the bug
System.IO.FileNotFoundException: 'Could not load file or assembly 'MQTTnet, Version=3.1.2.0, 
Culture=neutral, PublicKeyToken=b69712f52770c0a7'. The system cannot find the file specified.'

### Which project is your bug related to?

- Client
- ManagedClient

### To Reproduce
After updating to this version my UWP project when trying to use the library crashes immediately with the above mentioned error.
### Additional context / logging
Xamarin Project, Android/UWP.

Currently on Android it works perfectly. In UWP it crashes.

**Comment by mstanisavljevicns** [comment]
Facing the same issue. Any news here?

**Comment by bartsipes** [comment]
@ivanrlg can you post what your UWP project file looks like? Sounds like you could have a missing or outdated reference. Or possibly a binding redirect that hasn't been updated.

**Comment by chkr1011** [comment]
I assume this issue is fixed since no feedback was provided. If the issue still exists with version 4.0 please create a new ticket and include a sample project so that we can reproduce the issue.
