### ISSUE TITLE
Client delay for publish with QoS 1

### ISSUE THREAD

**Issue by lpaulusLohr** [dotnet/MQTTnet#1361]
### Describe your question

I want to know how is the MQTT Client delay set for QoS 1 before retrying to send the next message 
before he receive the PUBACK ?

### Which project is your question related to?

- Client
- ManagedClient

**Comment by chkr1011** [comment]
When using the _MqttClient_ there is no retry at all. If you get an exception while publishing you must initiate the try on your own.
When using the _ManagedClient_ the failed message gets sent after the connection is restored (and so on).
