### ISSUE TITLE
MqttClient V4 blocking http cancellation

### ISSUE THREAD

**Issue by alberk8** [dotnet/MQTTnet#1363]
### Verification

Before opening a bug make sure that the following conditions are met.

1. Performance issues are also appearing in RELEASE mode of your application.
2. An increased memory consumption or high CPU load also happens when your application runs in RELEASE mode AND logging is DISABLED.
3. Client issues with not received messages, connection drops etc. can be reproduced via another client application like "MQTTnetApp" (https://github.com/chkr1011/MQTTnetApp) or similar.
4. The bug also appears in the VERY LATEST version of this library. There is no support for older version (due to limited resources) but pull requests for older versions are welcome.

### Describe the bug
I have a Http call in the ApplicationMessageReceviedAsync delegate that blocks the cancellation of the http.  the whole http call just hangs if the endpoint does not exist.

### Which component is your bug related to?

- Client
- ManagedClient

### To Reproduce
```csharp
  private async Task _mqttClient_ApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs arg)
        {
              if (arg.ApplicationMessage.Topic == _topic + "/reply/device")
            {
                Console.WriteLine(arg.ApplicationMessage.ConvertPayloadToString());
                var payloadStr = arg.ApplicationMessage.ConvertPayloadToString();
                if(!string.IsNullOrEmpty(payloadStr))
                {
                    
                    using HttpClient httpClient = new HttpClient();
                    httpClient.BaseAddress = new Uri("http://localhost:8082");

                    using (CancellationTokenSource cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromSeconds(3)))
                    {
                        Console.WriteLine("XXXXXX"); // **the next line hangs**.
                        await httpClient.GetAsync("", cancellationTokenSource.Token);
                        Console.WriteLine("YYYYYY");
                       
                    }
                   
                }
            }
}
```

### Expected behavior
The delegate should terminate when the cancellation token expires.

### Additional context / logging
Include debugging or logging information here:

```batch
\\ Put your logging output here.
```
### Code example
Please provide full code examples below where possible to make it easier for the developers to check your issues.

**Ideally a Unit Test (which shows the error) is provided so that the behavior can be reproduced easily.**
 
```csharp
\\ Put your code here.
```

**Comment by MD-V** [comment]
I don't think that you should not create a new HttpClient instance every time in your ApplicationMessageReceivedAsync handler. Please refactor your code to use HttpClientFactory and see if the issue still exists.

See the following link on more information about HttpClient and HttpClientFactory:
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

**Comment by alberk8** [comment]
> I don't think that you should create a new HttpClient instance every time in your ApplicationMessageReceivedAsync handler. Please refactor your code to use HttpClientFactory and see if the issue still exists.
> 
> See the following link on more information about HttpClient and HttpClientFactory: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

That was the first thing I did (using AddHttpClient and using DI) but that did not work.  I then tried HttpClient and that also did not work.  If the http endpoint exists then it worked.  The problem is that the http call never timeout when the endpoint does not exists.

**Comment by SeppPenner** [comment]
Can you manually set the .Timeout property of the HttpClient to e.g. 5 seconds?

**Comment by alberk8** [comment]
> Can you try to manually set the .Timeout property of the HttpClient to e.g. 5 seconds and check if this changes anything?
> 
> ```cs
> var httpClient = new HttpClient();
> httpClient.Timeout = TimeSpan.FromSeconds(5);
> ```
> 
> **EDIT:** Sorry, forget about it... I have seen that you added the using block with the cancellation token around the client.

Try that too. Still no go.

**Comment by MD-V** [comment]
This example works for me (.NET 6, console, 4.0.0-preview5):

```
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using MQTTnet;
using MQTTnet.Client;
using MQTTnet.Server;

var builder = new HostBuilder()
               .ConfigureServices((hostContext, services) =>
               {
                   services.AddHttpClient();
                   services.AddTransient<MyApplication>();
               }).UseConsoleLifetime();

var host = builder.Build();

using (var serviceScope = host.Services.CreateScope())
{
    var services = serviceScope.ServiceProvider;

    var myService = services.GetRequiredService<MyApplication>();
    await myService.Run();

}

return 0;

internal class MyApplication
{
    private readonly ILogger _logger;
    private IHttpClientFactory _httpFactory { get; set; }
    public MyApplication(ILogger<MyApplication> logger, IHttpClientFactory httpFactory)
    {
        _logger = logger;
        _httpFactory = httpFactory;
    }

    public async Task Run()
    {
        var port = 4841;

        var topic = "mqttnet/samples/topic/1";

        var mqttFactory = new MqttFactory();

        // The port for the default endpoint is 1883.
        // The default endpoint is NOT encrypted!
        // Use the builder classes where possible.
        var mqttServerOptions = new MqttServerOptionsBuilder()
            .WithDefaultEndpoint()
            .WithDefaultEndpointPort(port)
            .Build();

        using var mqttServer = mqttFactory.CreateMqttServer(mqttServerOptions);
        await mqttServer.StartAsync();

        using var mqttSubscriber = mqttFactory.CreateMqttClient();

        var mqttClientOptionsSubscriber = new MqttClientOptionsBuilder()
            .WithTcpServer("localhost", port)
            .WithClientId("Subscriber")
            .Build();

        var topicFilter = new MqttTopicFilterBuilder()
                           .WithTopic(topic)
                           .WithExactlyOnceQoS()
                           .Build();

        mqttSubscriber.ApplicationMessageReceivedAsync += async (applicationMessage) =>
        {
            var httpClient = _httpFactory.CreateClient();
            httpClient.BaseAddress = new Uri("http://asdf:8082");

            using (CancellationTokenSource cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromSeconds(3)))
            {
                Console.WriteLine("XXXXXX"); // **the next line hangs**.

                try
                {
                    await httpClient.GetAsync("", cancellationTokenSource.Token);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }

                Console.WriteLine("YYYYYY");
            }
        };

        await mqttSubscriber.ConnectAsync(mqttClientOptionsSubscriber, CancellationToken.None);

        await mqttSubscriber.SubscribeAsync(topicFilter, CancellationToken.None);

        var applicationMessage = new MqttApplicationMessageBuilder()
            .WithTopic(topic)
            .WithPayload("test")
            .WithQualityOfServiceLevel(MQTTnet.Protocol.MqttQualityOfServiceLevel.ExactlyOnce)
            .Build();

        await mqttSubscriber.PublishAsync(applicationMessage, CancellationToken.None);

        Console.WriteLine("Press Enter to exit.");
        Console.ReadLine();

        await mqttSubscriber.DisconnectAsync();
        await mqttServer.StopAsync();
    }
}
```

**Comment by alberk8** [comment]
I have found the problem.  It seems that the http error messages were swallowed in the delegate.   If I have a try and catch over the http call it does catches it.
