### ISSUE TITLE
TLS v1.3 Implementation by MQTTNet

### ISSUE THREAD

**Issue by Rohit03sahu** [dotnet/MQTTnet#1367]
We have not found any implementation for TLS1.3 in mqttNet Library

### Exception 
" The client and server cannot communicate because they do not possess a common algorithm. "

### Describe the solution you'd like
Build TLS 1.3 client connection

**Comment by chkr1011** [comment]
This library does not implement TLS on its own and fully relies on .NET. So if you use .net6.0 as a target TLS 1.3 becomes available.

**Comment by azometry** [comment]
HI, I had a similar question and wanted to know when could we see v4.0 to be released as I see that version is .net6 compatible. If I understand correctly currently version 4.0 is pre-release only ?

**Comment by Rohit03sahu** [comment]
We have enabled TLS 1.3 on win 2022. In result, we can able to establish the connection b/w client to broker.

**Comment by SeppPenner** [comment]
> We have enabled TLS 1.3 on win 2022. In result, we can able to establish the connection b/w client to broker.

Er, I don't think you need to enable TLS1.3 in Windows: https://answers.microsoft.com/en-us/windows/forum/all/how-to-enable-tls-13-in-windows-10/f9ab4993-4758-4de3-a7f9-54a47b61cc77:

> TLS/1.3 is supported in all versions of Chromium-based Edge and should have been enabled by default. Windows 10 1903 has support for TLS/1.3.

And what is Windows 2022? There's only Windows 10 and 11...
