### ISSUE TITLE
How to check mqtt client trying to reconnect to broker.

### ISSUE THREAD

**Issue by jprathore** [dotnet/MQTTnet#1368]
Hi, Thank you first of All.

I am using MQTT client auto-reconnect functionality to connect broker. I am restarting the broker and have to check when the MQTT client trying to reconnect to the broker when the connection disconnect to the broker.

Is there any boolean?  so that I can check that connection is lost to broker and MQTT client trying to connect broker

**Comment by MD-V** [comment]
Ah I see. I think you can add a listener to mqttClient.InternalMqttClient.ConnectingAsync (should match your code). This handler is called every time the MqttClient (ManagedMqttClient is a wrapper around MqttClient) is trying to connect. See: https://github.com/dotnet/MQTTnet/blob/7d95c238c325411ce6518cee5fd3a07832c890f5/Source/MQTTnet/Client/MqttClient.cs#L122

and Sample: 
https://github.com/dotnet/MQTTnet/blob/7d95c238c325411ce6518cee5fd3a07832c890f5/Source/MQTTnet.Tests/Mockups/TestEnvironment.cs#L212
