### ISSUE TITLE
High availability using two broker

### ISSUE THREAD

**Issue by itelligent-mrivas** [dotnet/MQTTnet#1371]
### Describe your question
Hi, 
I need create a high availability MQTT system. The aim is that if one MQTT broker is down (for example the server is broken), the other MQTT continue running and the full sistem can be working.

My question is if MQTT.net allow this configuration between brokers, to allow the broker synchronization and the client integration with the multiple brokers, because no view this functionality in the documentation either opened issues.

Thanks
Mario Rivas

### Which project is your question related to?

- Client
- Server

**Comment by SeppPenner** [comment]
I have created a project that uses Microsoft Orleans to achieve clustering. It's not perfect (And not really well maintained as I didn't have the time to work on it again). Maybe you want to check it out: https://github.com/SeppPenner/NetCoreMQTTExampleCluster
