### ISSUE TITLE
Mock Mqtt Client

### ISSUE THREAD

**Issue by Rohit03sahu** [dotnet/MQTTnet#1374]
### Describe the feature request
I would like to write some unit case for mqtt client.

### Which project is your feature request related to?
Client

### Describe the solution you'd like
How can we mock mqtt client ?

**Comment by MD-V** [comment]
Hello @Rohit03sahu,

if you are using the 3.X nuget package you can mock IMQttClient interface. For 4.X you'll have to encapsulate the MqttClient in a Custom Client class which you can mock (introduce your own interface).

**Comment by SeppPenner** [comment]
Should be fixed with the latest changes in the MyGet feed according to https://github.com/dotnet/MQTTnet/pull/1378, https://github.com/dotnet/MQTTnet/discussions/1358.
