### ISSUE TITLE
Does Mqttnet version 4.0 contain below mentioned interface ?

### ISSUE THREAD

**Issue by Rohit03sahu** [dotnet/MQTTnet#1375]
### Describe your question
Does mqttnet version 4.0 has IMqttClient,IMqttClientOptions, IMqttClientConnectedHandler, IMqttClientDisconnectedHandler, IMqttApplicationMessageReceivedHandler & IMqttClinet

### Which project is your question related to?
- Client
- ManagedClient

**Comment by MD-V** [comment]
Hello @Rohit03sahu,

no most of the interfaces have been removed to keep the public API small and clean. See [here](https://github.com/dotnet/MQTTnet/wiki/Upgrading-guide#from-3x-to-400) and [here](https://github.com/dotnet/MQTTnet/pull/1357). As per the Wiki you should encapsulate all in custom clients.

**Comment by SeppPenner** [comment]
Far related to https://github.com/dotnet/MQTTnet/pull/1378.

**Comment by chkr1011** [comment]
After a discussion we restored a couple of them (IMqttClient etc.). But the Managed Client and the "normal" one no longer share interfaces because they work in a completely different way so that this lead to much confusion in the past.
