### ISSUE TITLE
Unable to create stable communication mqtt connection in docker env

### ISSUE THREAD

**Issue by Rohit03sahu** [dotnet/MQTTnet#1382]
### Describe your question
Communication between mqttClient and broke is not stable where broker & client both are running in docker env.

### Which project is your question related to?
- Client
- ManagedClient
- MQTTnet.Server standalone
- Server

**Comment by chkr1011** [comment]
Does is run stable when ONLY the server runs in docker or the client? What means "not stable"? Do you get disconnects? Please provide more information about the situation.

**Comment by SeppPenner** [comment]
Please feel free to re-open this issue and please provide more details. We can't do anything with that less description :(
