### ISSUE TITLE
IOS not connecting to broker 

### ISSUE THREAD

**Issue by yudokusora** [dotnet/MQTTnet#1383]
### Verification

Before opening a bug make sure that the following conditions are met.

### Describe the bug
When doing client.connectAsync(options) on a real iphone device(in simulator it works) the program will continue working but no request will be sent, when trying to debug, no error is shown 

### Which component is your bug related to?
- Client

### To Reproduce
1. Using this version of MQTTnet '3.1.2'.
2. On a real iphone device
3. Run this code:

`public async Task connect(string channel,string message)
        {

            try
            {
                

                var mqttFactory = new MqttFactory();

                IMqttClient client = mqttFactory.CreateMqttClient();
                var options = new MqttClientOptionsBuilder().WithClientId(Guid.NewGuid()
                    .ToString()).WithTcpServer("192.168.1.2").WithCleanSession().Build();

                client.UseConnectedHandler(e =>
                {
                    Console.WriteLine("connected to the server");
                    client.SubscribeAsync(new TopicFilterBuilder().WithTopic(channel).Build());

                });

                client.UseDisconnectedHandler(e =>
                {
                    Console.WriteLine("disconnected to the server");
                });

                await client.ConnectAsync(options);

                await PublishMessageAsync(client, message, channel);

                await client.DisconnectAsync();

            }catch (Exception ex)
            {

            }

        }`
4. With these arguments 'test,hello world'.
5. it will crash the debugger

### Expected behavior
the program will continue execution but the debugger will stop at client.connectasync()

### Additional context / logging
I added the local network permision and it ask for it

**Comment by yudokusora** [comment]
I added a trace and this is what it says: "Trying to connect with server '192.168.1.2:1883' (Timeout=00:00:10)."

**Comment by yudokusora** [comment]
Also after saying that, the task just dies

**Comment by chkr1011** [comment]
Do you use Xamarin to build the iOS app? Please check for proper permissions in your application so that external network can be reached etc.

I don't think that this is an issue of this library if the code works in the simulator.

**Comment by chkr1011** [comment]
I assume this is solved.
