### ISSUE TITLE
Server Sample is not working / outdated

### ISSUE THREAD

**Issue by XeroVice** [dotnet/MQTTnet#1384]
### Describe your question
Hello,

I've been trying to get a server (broker) running, allthough the provided samples seem to be outdated and do not work. After some research I managed to get it running Syntaxwise but I get an error when trying to publish.
`Error: A network protocol error occurred when communicating with the broker.`

Are there somewhere samples which are working correctly?

Thank you in advance!

### Which project is your question related to?
- Server

**Comment by XeroVice** [comment]
```
using System;
using System.Text;
using MQTTnet;
using MQTTnet.Protocol;
using MQTTnet.Server;

namespace mqttTest 
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Validating_Connections();
        }
        private static IMqttServer _mqttServer;
        public static async Task Validating_Connections()
        {

            var mqttFactory = new MqttFactory();

            var mqttServerOptions = new MqttServerOptionsBuilder()
                .WithDefaultEndpointPort(1883)
                //.WithConnectionValidator(ValidateConn)
                .Build();

            using (_mqttServer = mqttFactory.CreateMqttServer())
            {
                await _mqttServer.StartAsync(mqttServerOptions);

                Console.WriteLine("Press Enter to exit.");
                Console.ReadLine();

                await _mqttServer.StopAsync();
            }
        }
        private void OnMessageReceive(object sender, MqttApplicationMessageReceivedEventArgs e)
        {
            Console.WriteLine(e.ApplicationMessage);
        }


        private static void ValidateConn(MqttConnectionValidatorContext v)
        {
            if (v.Username == "test" && v.Password == "teresa2014")
            {
                v.ReasonCode = MqttConnectReasonCode.Success;
            }
        }
    }
}
```

**Comment by rlkollman** [comment]
Have you created a client using MQTTnet or are you using a prebuilt client? What client is it? I assume the error you quoted is on the client - so, we'd need more information on the client to help with this specific error.

I tried the code you provided above with .NET Framework 4.7.2, MQTTnet 3.1.2, connected 2 clients using [MQTT Explorer](http://mqtt-explorer.com/) (pre-built client), and successfully subscribed/published.  MQTTnet uses MQTT Protocols 3.1, 3.1.1 and 5 - ensure your client is using one of these protocols.

**Comment by XeroVice** [comment]
> Have you created a client using MQTTnet or are you using a prebuilt client? What client is it? I assume the error you quoted is on the client - so, we'd need more information on the client to help with this specific error.
> 
> I tried the code you provided above with .NET Framework 4.7.2, MQTTnet 3.1.2, connected 2 clients using [MQTT Explorer](http://mqtt-explorer.com/) (pre-built client), and successfully subscribed/published. MQTTnet uses MQTT Protocols 3.1, 3.1.1 and 5 - ensure your client is using one of these protocols.

I used mosquitto client to sub and publish at Debian 10. It works with the mosquitto server but not with the mqttnet server with the same command and message

**Comment by chkr1011** [comment]
Please use the latest build from the MyGet feed (URL in README). The preview from nuget is a little bit outdated.

**Comment by chkr1011** [comment]
Version 4.0 is now officially released and new Samples where added in the _Samples_ directory of this repository. If you miss something in the samples please reopen the ticket.
