### ISSUE TITLE
Whether offline messages are supported

### ISSUE THREAD

**Issue by SpringHgui** [dotnet/MQTTnet#1386]
### Describe the feature request
Whether offline messages are supported
### Which project is your feature request related to?

- Server

### Describe the solution you'd like
`WithCleanSession = false`
After subscribing to a message, the client is offline for a period of time. When it goes online again, it can receive messages during the offline period

**Comment by SeppPenner** [comment]
Are you talking about retained messages?

**Comment by chkr1011** [comment]
If you refer to persisted sessions (across server restarts): They are not yet supported. Support is planned but not for version 4.0.
