### ISSUE TITLE
How to retrieve username in MqttApplicationMessageInterceptor?

### ISSUE THREAD

**Issue by seikosantana** [dotnet/MQTTnet#1388]
### Describe your question
I am trying to identify a device that is connected to the broker by its username, but i wasn't able to find how to get the username of the message publisher from `MqttApplicationMessageInterceptorContext`. There's an issue i read about which I cannot find for now, says there's a dictionary that exposes informations, I assume it is MqttApplicationMessageInterceptorContext.SessionItems, but on each received message, it is always empty. Where is username stored and retrievable from the application message interceptor?

Thanks in advance

### Which project is your question related to?
- Server

**Comment by SeppPenner** [comment]
What you can do is the following:

Store the connected clients in a dictionary / list on valid connections (With the `.WithConnectionValidator` method, https://github.com/dotnet/MQTTnet/wiki/Server#validating-mqtt-clients) and get it inside the `WithApplicationMessageInterceptor` method by using the (unique) client id that can be found in the context.

The session items should do the same thing if not something crucial has changed lately.

**Comment by seikosantana** [comment]
The session item always has no items.. Wonder if I missed something.

**Comment by SeppPenner** [comment]
You need to set the username manually if I remember correctly:

```csharp
var optionsBuilder = new MqttServerOptionsBuilder()
    .WithConnectionValidator(c =>
{
    if (c.ClientId.Length < 10)
    {
        c.ReasonCode = MqttConnectReasonCode.ClientIdentifierNotValid;
        return;
    }

    if (c.Username != "mySecretUser")
    {
        c.ReasonCode = MqttConnectReasonCode.BadUserNameOrPassword;
        return;
    }

    if (c.Password != "mySecretPassword")
    {
        c.ReasonCode = MqttConnectReasonCode.BadUserNameOrPassword;
        return;
    }

    c.ReasonCode = MqttConnectReasonCode.Success;
    c.SessionItems["UserName"] = c.Username; // Set the user name to the session items.
});
```

And later:

```csharp
var optionsBuilder = new MqttServerOptionsBuilder()
    .WithApplicationMessageInterceptor(c =>
    {
        var userName = c.SessionItems["UserName"]; // Get the username from the session items.
    })
    .Build();
```

I don't know if the code works already like that, but the idea should be clear, I guess.

The alternative if this doesn't work is to use a custom `Dictionary<string, string>` in the server that stores the ClientId (Is available in both contexts) as key and the corresponding user name (Needs to be added in the same way as in the above example).

**Comment by seikosantana** [comment]
Ah yeah it works
I didn't know i had to put it in myself 😄

Thanks a lot!
