### ISSUE TITLE
Is v4 ready for release - nuget versions are tagged preview

### ISSUE THREAD

**Issue by deandob** [dotnet/MQTTnet#1390]
Hi,

Is there a timeline on a final version v4.0 available on nuget? Preview 5 is a couple of months old, is it deemed safe for use in production systems or only for testing (waiting for v4.0)? 
Or simply grab the latest code off the MAIN branch?

**Comment by chkr1011** [comment]
Version 4.0 is still in development. Only bug fixes and small API changes and the version will be finalized within the next couple of  weeks. Please checkout the MyGet feed (URL in README). It contains latest automated builds. Betas etc. are no longer pushed to nuget.
