### ISSUE TITLE
GetClientStatusAsync should change to GetClientsStatusAsync

### ISSUE THREAD

**Issue by behroozbc** [dotnet/MQTTnet#1391]
### Describe the bug
I think the [`GetClientStatusAsync` method ](https://github.com/dotnet/MQTTnet/blob/73d681bc1f978c4e6cf03266fcd1fb4a30a5d205/Source/MQTTnet/Server/Internal/MqttClientSessionsManager.cs#L232) should change to `GetClientsStatusAsync` because `GetClientStatusAsync` return a list of clients not a client.
### Which component is your bug related to?
- Server

### Expected behavior
[`GetClientStatusAsync` method](https://github.com/dotnet/MQTTnet/blob/73d681bc1f978c4e6cf03266fcd1fb4a30a5d205/Source/MQTTnet/Server/Internal/MqttClientSessionsManager.cs#L232) should change to `GetClientsStatusAsync` .

**Comment by SeppPenner** [comment]
@chkr1011 Seems to be a valid point. What do you think?

**Comment by chkr1011** [comment]
Well it is plural aleady. The method Returns multiple status but the Plural of Many Status is Status as well.

**Comment by behroozbc** [comment]
> Well it is plural aleady. The method Returns multiple status but the Plural of Many Status is Status as well.

 My problem is for Client, not status.
This method return multi Clients too.

**Comment by logicaloud** [comment]
If I wanted a method to return the brand of many cars then I would call the method `GetCarBrands`, not `GetCarsBrands` nor `GetCarsBrand`, so I'd say the singular form of `Client` is OK here. `Status` seems correct here although `Statuses` also seems to be an accepted plural form, especially in American English. Either leaving the  name as `GetClientStatusAsync` or changing to `GetClientStatusesAsync` would make sense.

**Comment by behroozbc** [comment]
I think `GetClientStatusesAsync` a very good name and make sense.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by behroozbc** [comment]
I think is better to have two method 

- `GetClientStatusesAsync` return a list of client statuses
- `MqttClientStatus` return a client status change like this 
like this
```
        public Task<IList<MqttClientStatus>> GetClientStatusesAsync()
        {
            var result = new List<MqttClientStatus>();

            lock (_clients)
            {
                foreach (var connection in _clients.Values)
                {
                    var clientStatus = new MqttClientStatus(connection)
                    {
                        Session = new MqttSessionStatus(connection.Session)
                    };

                    result.Add(clientStatus);
                }
            }

            return Task.FromResult((IList<MqttClientStatus>)result);
        }
        public MqttClientStatus GetClientStatus(string id)
        {
            var connection = GetClient(id);
            return new MqttClientStatus(connection)
            {
                Session = new MqttSessionStatus(connection.Session)
            };
        }
```

**Comment by chkr1011** [comment]
GetClientStatusesAsync  is a good compromise in my opinion. I will change it accordingly.

**Comment by chkr1011** [comment]
I renamed the methods. Please check the myget feed with latest changes.
