### ISSUE TITLE
Replace ApplicationMessageSkippedHandler with event in ManagedClient

### ISSUE THREAD

**Issue by mmuecke** [dotnet/MQTTnet#1394]
### Describe your question
In version 4 the handlers were replaced by async events. However, one handler has remained here. Was it meant that way? Otherwise, the handler is to be replaced by an event.

https://github.com/dotnet/MQTTnet/blob/626baa7bb5028199588090a6358e962fdae3c084/Source/MQTTnet.Extensions.ManagedClient/IManagedMqttClient.cs#L24

### Which project is your question related to?
- ManagedClient

**Comment by chkr1011** [comment]
Thanks for the feedback. This and other events are not yet migrated since 4.0 is still in development. Please checkout the MyGet feed with latest changes. I just migrated them so that an updated nuget will be available soon.
