### ISSUE TITLE
How can I filter itself's message of server publishing?

### ISSUE THREAD

**Issue by f3404923** [dotnet/MQTTnet#1400]
I'm making a mqtt broker app for windows service. And I want to publish a message to client when client connected, the client can connect /subscribe/publish to server normally, but the server publish message can be received by itself. How can I filter itself message?
My main code as below.
----------------------------------------------------------------------------------------------------
    public class MQTTServer:IDisposable
    {
        
        private static IMqttServer?  mqttServer;
        public static event Action<string,string>? MessageReceived;
        
        public static ILogger<Worker>? logger { get;  set; }
 
         
        public static async Task  StartMqttServerAsync()
        {        
           
            if (mqttServer == null)
            {
                var optionsBuilder = new MqttServerOptionsBuilder()
                    .WithConnectionBacklog(100)
                    .WithDefaultEndpointPort(1883)                 
                    .WithConnectionValidator(c =>
                    {
                        if (c.ClientId.Length < 10)
                            c.ReasonCode = MqttConnectReasonCode.ClientIdentifierNotValid;
                        if (c.Username.Equals("U17") && c.Password.Equals("FITBIT@2022"))
                        {
                            c.ReasonCode = MqttConnectReasonCode.Success;
                            logger?.LogInformation($">>>A new client incoming:{c.ClientId}>>> {DateTime.Now}" );
                        }
                          
                        else
                            c.ReasonCode = MqttConnectReasonCode.BadUserNameOrPassword;
                    })                   
                    .WithSubscriptionInterceptor(c =>
                    {
                        if (c.TopicFilter.Topic.Equals("Status") || c.TopicFilter.Topic.Equals("Command"))
                            c.AcceptSubscription = true;
                        else
                            c.CloseConnection = true;
                        logger?.LogInformation("Subscribe: {date}>>>{topic}"  , DateTime.Now,c.TopicFilter.Topic);
                    });
                mqttServer = new MqttFactory().CreateMqttServer() as MqttServer;
                mqttServer.StartedHandler = new MqttServerStartedHandlerDelegate(c => {
                    logger?.LogInformation("MQTT Service start {date}"  , DateTime.Now);
                });
                mqttServer.StoppedHandler = new MqttServerStoppedHandlerDelegate(c => {
                    logger?.LogInformation("Service stop: {date}", DateTime.Now);
                });                
                mqttServer.UseClientConnectedHandler(c => {
                    logger?.LogInformation("Connection: {date}"+c.ClientId ,DateTime.Now);
                });
                mqttServer.UseClientDisconnectedHandler(c => { 
                    logger?.LogInformation("Disconnected: "+c.ClientId+","+c.DisconnectType.ToString());
                });
                //收到从客户端返回的信息
                mqttServer.UseApplicationMessageReceivedHandler(async c => {      
                   
                    string s = System.Text.Encoding.UTF8.GetString(c.ApplicationMessage.Payload);                    
                    MessageReceived.Invoke(s,c.ClientId);
                });
                
                await mqttServer.StartAsync(optionsBuilder.Build());
                
            } 
        }

        private static async Task StopMqttServer()
        {
            if (mqttServer == null) return;
            await mqttServer.StopAsync();
            mqttServer = null;
            logger.LogInformation("Stop MqttServer: {date}",DateTime.Now );
        }

        /// <summary>
        /// 异步发布消息
        /// </summary>
        /// <param name="message"></param>
        public static async Task PublishMessageAsync(string topic,string message  )
        {
            await mqttServer.PublishAsync(new MqttApplicationMessage {
                Topic = topic,
                Payload = Encoding.UTF8.GetBytes(message),
                QualityOfServiceLevel=MqttQualityOfServiceLevel.AtLeastOnce,
            });
         }

        public async void Dispose()
        {
            await StopMqttServer();
        }
    }

**Comment by SeppPenner** [comment]
What do you mean by itself? That the server shouldn't get to receive the server message?

**Comment by chkr1011** [comment]
You can set the "ClientId" in the server options. This is the ID which the server will use when publishing messages. Then you can filter this client in the interceptors etc.

**Comment by SeppPenner** [comment]
> You can set the "ClientId" in the server options. This is the ID which the server will use when publishing messages. Then you can filter this client in the interceptors etc.

This is probably the best solution. Others wpuld be to distinguish by a unique topic (If the server only sends to one topic) or by adding a custom field e.g. to a JSON payload). But the `ClientId` needs to be unique in the whole system for each client (and in this case the server is a `MQTT client`, so the solution from @chkr1011 is the best.
