### ISSUE TITLE
MQTTNet Server - Communication with clients from different subnet?

### ISSUE THREAD

**Issue by Elpra-Bozas** [dotnet/MQTTnet#1403]
### Describe your question
Hello,
We have a MQTTNet Server set up in our local network which contains multiple subnets. The server does not seem to recognize MQTT packets that are sent from clients from different subnets, even though the packets arrive at the host PC.
e.g. when building the broker with IPAddress lets say 192.168.0.214 (by using WithDefaultEndpointBoundIPAddress), all packets with source and destination on the same sub are handled successfully.
If the destination is lets say on 192.168.202.203 the broker does not respond even if he was build with the same IPAddress.
Are there any other broker build options we should pay attention to?

### Which project is your question related to?

- Server

**Comment by chkr1011** [comment]
No there are no other properties related to this. The bound IP address is used for that. Probably the documentation for .net has more information about how it works for other subnets.
