### ISSUE TITLE
Shared subscriptions is not supported?

### ISSUE THREAD

**Issue by chang196700** [dotnet/MQTTnet#1404]
### Describe your question
I cannot subscribe topic start with "$share/". I checked the code and found that topics starting with "$share/" directly returned SharedSubscriptionsNotSupported. Are there plans to support this feature in the future?

### Which project is your question related to?
- Generic

**Comment by SeppPenner** [comment]
No, this feature is not yet supported. Check out https://github.com/dotnet/MQTTnet/issues/821.

**Comment by chkr1011** [comment]
This feature has low priority at the moment. It may be implemented but not within the next months. Maybe someone is also interested in this feature and implements it.
