### ISSUE TITLE
Use SPDX license for Nuget package?

### ISSUE THREAD

**Issue by d5UtQvp8QQU9** [dotnet/MQTTnet#1406]
### Describe your question
It is recommended to use the SPDX license identifier for Nuget when using a common license like MIT:
https://docs.microsoft.com/en-us/nuget/reference/nuspec#license

> An SPDX license expression or path to a license file within the package, often shown
in UIs like nuget.org. If you're licensing the package under a common license, like
MIT or BSD-2-Clause, use the associated [SPDX license identifier](https://spdx.org/licenses/).
For example:
`<license type="expression">MIT</license>`

The same also possible inside SDK-style .csproj files:
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#important-nuget-package-metadata:
`<PackageLicenseExpression>MIT</PackageLicenseExpression>`

This project currently uses a file reference to the 'LICENSE' file: `<PackageLicenseFile>LICENSE</PackageLicenseFile>`, the file contains the MIT license.

Is there a reason this project has not yet adapted this recommendation?

### Which project is your question related to?

- Generic

**Comment by chkr1011** [comment]
There is no reason. The topic is new to us. I will adopt the changes and release a new nuget verison quite soon.

**Comment by d5UtQvp8QQU9** [comment]
Thank you for your reply.
I didn't want to sound like this is a problem, I just noticed a difference between MQTTnet and Microsoft packages (also MIT). Also I think this might make life easier for SBOM-tools (although I don't know definitely).

**Comment by SeppPenner** [comment]
This is fixed with https://github.com/dotnet/MQTTnet/pull/1408, I guess. Correct me, if I'm wrong.
