### ISSUE TITLE
It is better to set the capacity of the list.

### ISSUE THREAD

**Issue by behroozbc** [dotnet/MQTTnet#1407]
### Discussed in https://github.com/dotnet/MQTTnet/discussions/1401

<div type='discussions-op-text'>

<sup>Originally posted by **behroozbc** April 28, 2022</sup>
I just saw this code and noticed a small performance issue.
https://github.com/dotnet/MQTTnet/blob/73d681bc1f978c4e6cf03266fcd1fb4a30a5d205/Source/MQTTnet/Server/Internal/MqttClientSessionsManager.cs#L254

If a list has a small number of items, it does not really matter to set the capacity of the list. However, when the list becomes large, it is important to set the capacity of the list. the cost of performance is `O(log(n))` and happened because of the `EnsureCapacity` method of `List<T>`  
There's a possibility that things might change like this
```
 var result = new List<MqttClientStatus>(_clients.Values.Count);
```
It would be my pleasure to find and fix the whole project if you would like.</div>

**Comment by chkr1011** [comment]
Due to the fact that this is an ongoing process I will close this issue. These optimizations are applied from time to time. If someone will change this in a single pull request the PR can also be created without this ticket.
