### ISSUE TITLE
MQTT-Broker auto reduce the message-publish number  when user sub some duplicate topics  

### ISSUE THREAD

**Issue by gmiloveyou** [dotnet/MQTTnet#1419]
### Describe your question
When a client sub two topic that are related or duplicate
example topic:
     "cnc/1/command/fileDispatch/+"  and  "cnc/1/#"

If I use some paid broker (Alibaba service).

And publish the message like this 
topic :  "cnc/1/command/fileDispatch/123456",

The client will received message twice
![image](https://user-images.githubusercontent.com/13726557/172128809-ae8db51a-6e76-4d29-a873-42d8a86e03e7.png)

but when I use MQTTnet Broker,  the client will only received the message once.
![image](https://user-images.githubusercontent.com/13726557/172128552-9776e657-6148-451e-813b-97f548bfc416.png)

Does MQTTnet broker has some extra mechanism that make things different?

### Which project is your question related to?
- MQTTnet.Server standalone
- Server
- Generic

**Comment by logicaloud** [comment]
The specification (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718037, section `3.3.5 Actions`), says:

> When Clients make subscriptions with Topic Filters that include wildcards, it is possible for a Client’s subscriptions to overlap so that a published message might match multiple filters. In this case the Server MUST deliver the message to the Client respecting the maximum QoS of all the matching subscriptions [MQTT-3.3.5-1]. In addition, the Server MAY deliver further copies of the message, one for each additional matching subscription and respecting the subscription’s QoS in each case. 

So it looks like that MQTTnet does what it MUST do and the Alibaba service does what it MAY do.

**Comment by gmiloveyou** [comment]
> The specification (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718037, section `3.3.5 Actions`), says:
> 
> > When Clients make subscriptions with Topic Filters that include wildcards, it is possible for a Client’s subscriptions to overlap so that a published message might match multiple filters. In this case the Server MUST deliver the message to the Client respecting the maximum QoS of all the matching subscriptions [MQTT-3.3.5-1]. In addition, the Server MAY deliver further copies of the message, one for each additional matching subscription and respecting the subscription’s QoS in each case.
> 
> So it looks like that MQTTnet does what it MUST do and the Alibaba service does what it MAY do.

This solve my problem.
Truly appreciate your support.
