### ISSUE TITLE
Has anyone successfully subscribed to emqx using the client?

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/MQTTnet#1420]
Has anyone successfully subscribed to emqx using the client?

I can connect successfully, but the subscription fails all the time. I don't know whether it is an mqttnet problem or an emqx problem.

**Comment by bbhxwl** [comment]
I can confirm that I can receive messages from mqttnet by using emqx testing tools.

![image](https://user-images.githubusercontent.com/26525599/172141747-e292f695-212c-4f4b-ab55-f941f4c44ed8.png)
![image](https://user-images.githubusercontent.com/26525599/172141779-c40f48a6-df04-49ac-b789-7e8779e25528.png)

**Comment by bbhxwl** [comment]
Mqttnet cannot subscribe. Should this be a bug in mqttnet?

**Comment by MD-V** [comment]
MqttClient.SubscribeAsync() returns a MqttClientSubscribeResult. Can you check if there is any ReasonString set by eqmx?

**Comment by SeppPenner** [comment]
Maybe https://github.com/dotnet/MQTTnet/issues/1314 can help here?

**Comment by SeppPenner** [comment]
I remember that there was a test somewhere with all kinds of public brokers, but I didn't find it anymore...

**Comment by chkr1011** [comment]
@SeppPenner I was wrong. The code if part of the TestApp (option 5).
@bbhxwl I added a screenshot with results I get when using the latest version of this library. So emqx generally works.

![image](https://user-images.githubusercontent.com/6939810/178471360-1eee89f7-54ca-40b9-a52b-886b0877199b.png)
