### ISSUE TITLE
Can V4 server not publishasync data?

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/MQTTnet#1429]
Can V4 server not publishasync data?
I used to be like this. Can't V4?

···

                Common.mqttServer.PublishAsync(new MqttApplicationMessage() { Topic = "KePuBox/Devices", Payload = Encoding.UTF8.GetBytes(Newtonsoft.Json.JsonConvert.SerializeObject(new { cmd = "video", url = url.Trim(), title = title.Trim(), desc = desc.Trim() })), QualityOfServiceLevel = MQTTnet.Protocol.MqttQualityOfServiceLevel.ExactlyOnce }, System.Threading.CancellationToken.None);
···

**Comment by SeppPenner** [comment]
In version 4, the method is called `EnqueueAsync` if I'm correct. This is something for the wiki (Upgrading guide).

**Comment by bbhxwl** [comment]
> `EnqueueAsync`

In the past, the server could push messages, but now only the client can push messages?

**Comment by SeppPenner** [comment]
> > `EnqueueAsync`
> 
> In the past, the server could push messages, but now only the client can push messages?

Oh sorry, I didn't see that you were referring to the server... @chkr1011 Can you answer the question?

**Comment by chkr1011** [comment]
@bbhxwl  The server can still publish messages but the method has changed to _EnqueueAsync_ as @SeppPenner mentioned. The reason is that also in V3 the message was NOT published. It was just added to the internal message queue and processed later and send to all subscribed clients. To reflect this the method was renamed.

**Comment by mcaden** [comment]
Looks like it's actually `InjectApplicationMessage`
https://github.com/dotnet/MQTTnet/blob/e33495010e185de7e77c95b12db50c554c25f425/Source/MQTTnet/Server/MqttServer.cs#L202

**Comment by bbhxwl** [comment]
> Looks like it's actually `InjectApplicationMessage`
> 
> https://github.com/dotnet/MQTTnet/blob/e33495010e185de7e77c95b12db50c554c25f425/Source/MQTTnet/Server/MqttServer.cs#L202

I have switched to emqx.

**Comment by yylyhldev** [comment]
> @bbhxwl The server can still publish messages but the method has changed to _EnqueueAsync_ as @SeppPenner mentioned. The reason is that also in V3 the message was NOT published. It was just added to the internal message queue and processed later and send to all subscribed clients. To reflect this the method was renamed.

None on the server：EnqueueAsync

**Comment by yylyhldev** [comment]
> InjectApplicationMessage

The message sent through InjectApplicationMessage goes to InterceptingPublishAsync, but the Client does not receive it
