### ISSUE TITLE
Why doesn't the server work?

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/MQTTnet#1431]
I don't think the server will open any ports and can't connect.

```
 static void Main(string[] args)
        {
            MqttFactory fac = new MqttFactory();
            var options = new MqttServerOptionsBuilder().WithDefaultEndpointPort(2666).Build();
            var server = fac.CreateMqttServer(options);
            Console.WriteLine(server.IsStarted.ToString());
            server.StartAsync();
            Console.WriteLine(server.IsStarted.ToString());
            Console.ReadLine();
        }
```

**Comment by chkr1011** [comment]
Please add "WithDefaultEndpoint()", "WithDefaultEndpointPort" will only set the port. This will enable the endpoint. For security reasons it is disabled by default since version 4.

**Comment by GieltjE** [comment]
This is wrongly denoted on the following wiki pages:
https://github.com/dotnet/MQTTnet/wiki/Server
https://github.com/dotnet/MQTTnet/wiki/Upgrading-guide

Could you fix these? (can't make a pull request or edit it otherwise)

**Comment by SeppPenner** [comment]
> This is wrongly denoted on the following wiki pages: https://github.com/dotnet/MQTTnet/wiki/Server https://github.com/dotnet/MQTTnet/wiki/Upgrading-guide
> 
> Could you fix these? (can't make a pull request or edit it otherwise)

The wiki is only for version 3 and below and will soon be deprecated either way.
