### ISSUE TITLE
DisconnectedAsync event args type; managed vs. unmanaged

### ISSUE THREAD

**Issue by d5UtQvp8QQU9** [dotnet/MQTTnet#1432]
### Describe the feature request
I'm trying to port an application using MqttManagedClient v3 to v4.
While doing so I discovered that the event handler for the `DisconnectedAsync` event has different arguments for managed vs unmanaged clients.

IMqttClient:
`event Func<MqttClientDisconnectedEventArgs, Task> DisconnectedAsync;`

MqttClient:
`public event Func<MqttClientDisconnectedEventArgs, Task> DisconnectedAsync {...}`

IManagedMqttClient:
`event Func<EventArgs, Task> DisconnectedAsync;`

ManagedMqttClient:
`public event Func<EventArgs, Task> DisconnectedAsync {...}`

There is, to my understanding, no technical reason for doing so, as the managed event is simply a relayed version of the unmanaged event:
````
add => InternalClient.DisconnectedAsync += value;
remove => InternalClient.DisconnectedAsync -= value;
````

### Which project is your feature request related to?
- ManagedClient

### Describe the solution you'd like
Could the managed version of the event also use MqttClientDisconnectedEventArgs as event argument?

### Describe alternatives you've considered
Instead of using the event in IManagedMqttClient:
`managedClient.DisconnectedAsync += async e => {...}`
Use the nested unmanaged client directly:
`managedClient.InternalClient.DisconnectedAsync += async e => {...}`

### Additional context
none

**Comment by chkr1011** [comment]
Thank you for reporting this issue. The event arg types are just wrong and must be changed. I will release a hotfix version soon.
