### ISSUE TITLE
Send message on to client after connection

### ISSUE THREAD

**Issue by fogzot** [dotnet/MQTTnet#1435]
### Describe the feature request
I am trying to publish a message just after a client connects and subscribes to a specific topic. The message is intended to send initial configuration to the client, so it is important that the client receives it. I tryied injecting a message using `InjectApplicationMessage` from the `ClientSubscribedTopicAsync` event but the client does not receive the message.

### Which project is your feature request related to?
- Server

### Describe the solution you'd like
It would be nice if `ClientSubscribedTopicAsync` could be called *after* setting up the client subscription and make sure that messages generated on the server are correctly delivered.

Note: I am using version 4.0.0 of MQTTnet; in version 3 this worked.

**Comment by fogzot** [comment]
Additional information: injecting the message in a different task that delays even as little as 1ms is enough for the client to receive the message. It seems that when `OnClientSubscribedTopic` is called the client is not **yet** subscribed and the message gets lost. I'd like the message to not be lost or, at least, to use an informative name for the event, like `ClientSubscribingTopicAsync`.

**Comment by chkr1011** [comment]
I fixed this issue. Please test with version 4.0.2.192 from the MyGet feed (see readme) and let me know if it works. No delay etc. is required. The event was just fired at the wrong time (as you already mentioned).

**Comment by fogzot** [comment]
The readme does not contain any reference to a MyGet feed.

**Comment by MD-V** [comment]
It does :) --> https://www.myget.org/feed/mqttnet/package/nuget/MQTTnet

**Comment by fogzot** [comment]
My fault. I used `Ctrl-F` on the homepage and found nothing. :(

**Comment by fogzot** [comment]
And I confirm it works. Great, thanks.

**Comment by qcjxberin** [comment]
I feel that it is not as convenient to use as before, and the new one does not know what to use.
