### ISSUE TITLE
.net 6    websocket  MQTTnet.Exceptions.MqttProtocolViolationException

### ISSUE THREAD

**Issue by wxtiankong** [dotnet/MQTTnet#1440]
Server :
services
                .AddMqttServer(it =>
                {
                    it.WithDefaultEndpoint();
                    it.WithDefaultEndpointPort(config["Mqtt:Port"].As<int>()); 
                })  
                .AddMqttTcpServerAdapter()
                .AddMqttWebSocketServerAdapter()
                .AddConnections(); 

app.UseEndpoints(endpoints =>
            {
                endpoints.MapMqtt("/mqtt");
            });
            app.UseMqttServer(server =>
            {  
                
                server.StartedAsync += Server_StartedAsync;
                server.StoppedAsync += Server_StoppedAsync;
                server.ClientConnectedAsync += Server_ClientConnectedAsync;
                server.ValidatingConnectionAsync += Server_ValidatingConnectionAsync;
                server.ClientDisconnectedAsync += Server_ClientDisconnectedAsync;
                server.ClientSubscribedTopicAsync += Server_ClientSubscribedTopicAsync;
                server.ClientUnsubscribedTopicAsync += Server_ClientUnsubscribedTopicAsync;
                server.ApplicationMessageNotConsumedAsync += Server_ApplicationMessageNotConsumedAsync; 
            });

MQTTnet.Exceptions.MqttProtocolViolationException :

![1655812849097](https://user-images.githubusercontent.com/23546114/174794228-be60c4c5-cb41-4aa3-89be-70aadfbec90a.png)

**Comment by MD-V** [comment]
Hello @wxtiankong,

to correctly understand this issue please provide more information (e.g. Stack trace, which versions are you using?, which client are you using?)

**Comment by SuperCatss** [comment]
能否请教一下，在net 6里面创建mqtt 服务器，tcp 正常连接，ws 连接失败 ，楼主是怎么解决的

**Comment by h1nson** [comment]
> 能否请教一下，在net 6里面创建mqtt 服务器，tcp 正常连接，ws 连接失败 ，楼主是怎么解决的

解决了吗？

**Comment by SuperCatss** [comment]
> > 能否请教一下，在net 6里面创建mqtt 服务器，tcp 正常连接，ws 连接失败 ，楼主是怎么解决的
> 
> 解决了吗？

解决了，ws的端口与tcp的端口不一样。
