### ISSUE TITLE
How to publish on topic and comunicate with clients from broker?

### ISSUE THREAD

**Issue by biapar** [dotnet/MQTTnet#1444]
How to publish on topic and comunicate with clients from broker?
I use the latest MQTTNet version.

**Comment by chkr1011** [comment]
Please check sample "Publish_Message_From_Broker" in "Samples" directory. Please keep in mind that client still must subscribe to the respective topic first. A direct communication is not possible in MQTT (as @MD-V already explained).

**Comment by mazorvanunu** [comment]
is it possible to detect when the message publish was not delivered to the client/had any faults ? a look at the source suggest no such exception will be thrown after a call to InjectApplicationMessage

https://github.com/dotnet/MQTTnet/blob/e33495010e185de7e77c95b12db50c554c25f425/Source/MQTTnet/Server/Internal/MqttClientSessionsManager.cs#L132

will ApplicationMessageNotConsumedAsync event suitable for detect a faulty delivery ? is this event triggered after a delivery was unsuccessful?

many thanks

**Comment by JesFo** [comment]
> Please check sample "Publish_Message_From_Broker" in "Samples" directory. Please keep in mind that client still must subscribe to the respective topic first. A direct communication is not possible in MQTT (as @MD-V already explained).

That sample doesn't seem to be there anymore. Any other examples for doing this?

**Comment by SeppPenner** [comment]
> > Please check sample "Publish_Message_From_Broker" in "Samples" directory. Please keep in mind that client still must subscribe to the respective topic first. A direct communication is not possible in MQTT (as @MD-V already explained).
> 
> That sample doesn't seem to be there anymore. Any other examples for doing this?

It's here: https://github.com/dotnet/MQTTnet/blob/41d5b703441b9f2f1adf3887f22e51faafc4c58e/Samples/Server/Server_Simple_Samples.cs#L39
