### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by GieltjE** [dotnet/MQTTnet#1455]
The wiki describes the usage of WithDefaultEndpointPort() but omits the required follow up of WithDefaultEndpoint() as described in #1431

https://github.com/dotnet/MQTTnet/wiki/Server
https://github.com/dotnet/MQTTnet/wiki/Upgrading-guide

**Comment by chkr1011** [comment]
The Wiki is only for version 3. I added a big note at the top. The wiki will be removed soon. The sample in the samples directory for version 4 already contains the required call.
