### ISSUE TITLE
The server is running for a long time, and the message reception is slow

### ISSUE THREAD

**Issue by hapgaoyi** [dotnet/MQTTnet#1458]
I have multiple clients that send messages at the same time and keep running. After a long time, the server will slow down to receive messages. If the server app is restarted, it will be restored，why?

**Comment by hapgaoyi** [comment]
The problem has already been solved

**Comment by chkr1011** [comment]
What was the reason. I am interested 😁

**Comment by KraskoVladimir** [comment]
Please write what was the reason.
