### ISSUE TITLE
V4 - Custom class with interceptors

### ISSUE THREAD

**Issue by bluewalk** [dotnet/MQTTnet#1463]
### Describe your question
After migrating to v4 (as v3 seems to be depricated now), all custom implementation of `IMqttServerSubscriptionInterceptor, IMqttServerConnectionValidator, IMqttServerApplicationMessageInterceptor, IMqttServerClientConnectedHandler, IMqttServerClientDisconnectedHandler` have stopped working.

How would one go ahead and validate connections, intercept subscription and message publishes etc. in a separate class? As the wiki hasn't been updated yet?

I see `InterceptingSubscriptionAsync` but I would like to move all of this logic to a separate class instead of in my Startup.cs 😉

I was using the following code with V3 which worked flawlessly:

```csharp
        services.AddSingleton<IMqttServerConnectionValidator>(x => x.GetRequiredService<MqttServerHandler>());
        services.AddSingleton<IMqttServerSubscriptionInterceptor>(x => x.GetRequiredService<MqttServerHandler>());
        services.AddSingleton<IMqttServerApplicationMessageInterceptor>(x => x.GetRequiredService<MqttServerHandler>());
        services.AddSingleton<IMqttServerClientConnectedHandler>(x => x.GetRequiredService<MqttServerHandler>());
        services.AddSingleton<IMqttServerClientDisconnectedHandler>(x => x.GetRequiredService<MqttServerHandler>());

        services.AddHostedMqttServerWithServices(builder =>
                builder.WithoutDefaultEndpoint()
                    .WithConnectionValidator(builder.ServiceProvider.GetRequiredService<IMqttServerConnectionValidator>())
                    .WithSubscriptionInterceptor(builder.ServiceProvider.GetRequiredService<IMqttServerSubscriptionInterceptor>())
                    .WithApplicationMessageInterceptor(builder.ServiceProvider.GetRequiredService<IMqttServerApplicationMessageInterceptor>())
            )
            .AddMqttConnectionHandler()
            .AddConnections();
```
I've done it this way as the `ValidateConnectionAsync` and `InterceptSubscriptionAsync` requires a service that is injected via DI

### Which project is your question related to?

- Server
- Generic

**Comment by chkr1011** [comment]
I updated sample _Server_Asp_Net_Samples_ in master. It shows how to use V4 together with DI.
