### ISSUE TITLE
What is the equivalent of WithApplicationMessageInterceptor on v4?

### ISSUE THREAD

**Issue by brkzkn** [dotnet/MQTTnet#1467]
Hello,

I'm trying to upgrade the library to v4. As you know, there are a bunch of changes (_wiki should be updated for v4, the sample folder doesn't cover all of them_). I would like to ask one of them how to implement WithApplicationMessageInterceptor.

`MqttServerOptionsBuilder` doesn't have `.WithApplicationMessageInterceptor` functions. So, can someone tell me how can I implement `WithApplicationMessageInterceptor` with v4.

Thanks

**Comment by chkr1011** [comment]
Please checkout the server class. It has many events which are replacing the former interfaces and handlers. So for every handler from version 3 there is a new event at the MQTT server instance.
