### ISSUE TITLE
How to intercept messages published from Server in V4

### ISSUE THREAD

**Issue by Jeanot-Zubler** [dotnet/MQTTnet#1470]
### Describe your question
In V3 my `ApplicationMessageInterceptor` checked, whether the `ClientId` was `null` and if that was the case, set `context.ApplicationMessage.Retain = true;`. This way, all messages published by the server would be retained.

In V4 I publish messages from the broker by calling the `server.InjectApplicationMessage()` method. I also added an eventhandler to the `server.InterceptingPublishAsync` property, that tries to do the same thing as my `ApplicationMessageInterceptor` did before. However, for server side injected messages, this handler is never called. Do I need to use a different Event for this, or is this not possible? Do I have to set `Retain = true` on every message I want to publish from the server at the location it is generated?

### Which project is your question related to?
- Server

**Comment by chkr1011** [comment]
Thanks for reporting this issue. This is indeed an issue. This will be fixed in the next version 4.1 of the library.
