### ISSUE TITLE
Error creating MQTT Websocket connection from IIS to IIS on application startup.

### ISSUE THREAD

**Issue by mkamran8** [dotnet/MQTTnet#1471]
### Describe your question
Hi,
I have a broker that I'm converting to be hosted from .NET 6 API using IIS and WebSockets. On application startup, we are creating an MQTT client to connect to itself. The connection fails when the code is hosted from IIS but works when run independently. I can successfully connect to IIS using wss from an external client. The startup code is hooked using the ApplicationStarted lifetime event.
Any help in this regard would be appreciated. 

**Environment**
Windows 11.
IIS 10
ASPNET 6
MQTTnet 4

**Error**
Unable to connect to the remote server

### Which project is your question related to?
- Client
- Server

Thank you.

**Comment by chkr1011** [comment]
This  question is related to ISS, kestrel and .net 6. I assume we cannot help much here.

**Comment by hgraghu** [comment]
Hi @mkamran8 did you happen to get it working, I'm looking for the same

**Comment by Rikj000** [comment]
@chkr1011, I fail to see why this would be unrelated.

Currently MQTTnet does not appear to support WebSocket + IIS usage,
on my end I'm facing the same issues as @mkamran8 when running under IIS.
*("The server returned status code '400' when status code '101' was expected")*.

Meanwhile all works as expected when running under Kestrel.

In my opinion this should either be:
- Resolved/fixed and perhaps documented an implementation example
- Documented, that IIS is **not supported** by MQTTnet

**Comment by Rikj000** [comment]
My bad, seems like the `WebSocket Protocol` simply still had to be enabled in IIS.. :facepalm: 

![iis-enable-websocket](https://user-images.githubusercontent.com/24852597/213162525-ae9cfa4b-5784-4e94-86fc-cb5914ef0138.png)

**Comment by jvssoft** [comment]
1. in IIS service you can do like this:
    webBuilder..UseIIS() 
2.services.AddHostedMqttServer(
                optionsBuilder =>
                {
                    optionsBuilder.WithDefaultCommunicationTimeout(TimeSpan.FromSeconds(5));
                    optionsBuilder.WithConnectionBacklog(1000);
                    optionsBuilder.WithDefaultEndpoint();
                    optionsBuilder.WithDefaultEndpointPort(1883);
                });

            services.AddMqttConnectionHandler();
            services.AddConnections();
            services.AddMqttTcpServerAdapter();
