### ISSUE TITLE
SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by qcjxberin** [dotnet/MQTTnet#1475]
This is the first time for me to use an SSL certificate. At present, I have found a problem. When I use mqtt.fx, I get an error: SSL peer shut down incorrectly. After checking some information, I cannot solve it.
![image](https://user-images.githubusercontent.com/5792218/181905717-4ce446ee-3e75-4e05-bfd4-40e4fceca700.png)

var CERTIFICATE_FILE_PATH = DG.Setting.Current.WebRootPath.GetFullPath().CombinePath("cert", "certificate.pfx");
X509Certificate2 certificate = new X509Certificate2(CERTIFICATE_FILE_PATH, CERTIFICATE_PASSWORD.ToString(), X509KeyStorageFlags.Exportable);

services.AddHostedMqttServer(mqttServer =>{
                // 关闭默认端口（1883端口）
                mqttServer.WithoutDefaultEndpoint();
                // 启用加密端口
                mqttServer.WithEncryptedEndpoint();
                // 设置加密端口号
                mqttServer.WithEncryptedEndpointPort(LabelSetting.Current.MqttPort);
                // 设置加密端口所使用的证书
                mqttServer.WithEncryptionCertificate(certificate.Export(X509ContentType.Pfx));
                // 设置加密端口所使用的SSL协议
                mqttServer.WithEncryptionSslProtocol(SslProtocols.Tls12 | SslProtocols.Tls13);
.........
})
.AddMqttConnectionHandler()
             .AddConnections();

![image](https://user-images.githubusercontent.com/5792218/181905780-14004950-3786-4189-8b24-0f213c0d2550.png)
![image](https://user-images.githubusercontent.com/5792218/181905784-33b53709-a13c-4d90-a729-103e99c82dca.png)

**Comment by chkr1011** [comment]
I don't think we can help here. This project relies on SSL implementation from .net. So you may need to open a ticket is these repositories.

**Comment by qcjxberin** [comment]
I use the method in the current tutorial to operate, but the certificate is wrong, I don't know how to get it

**Comment by qcjxberin** [comment]
@chkr1011 Please help identify what is generally causing the problem.
