### ISSUE TITLE
Unable to create WebSocket based Mqtt server in Net 6

### ISSUE THREAD

**Issue by SuperCatss** [dotnet/MQTTnet#1484]
I refer to the following documents
[https://github.com/dotnet/MQTTnet/blob/master/Samples/Server/Server_Asp_Net_Samples.cs](url)

I use the following version
![image](https://user-images.githubusercontent.com/24800663/183391736-2f081a2d-2bbc-4809-925e-c3ae9a0bd76b.png)

- MQTTnet 4.1.0.247
- MQTTnet.AspNetCore 4.1.0.247

When I connect using tcp it works fine. When I connect using ws, it can't connect.
When connecting using ws, the following exception occurred
**引发了异常: MQTTnet.dll 中的“MQTTnet.Exceptions.MqttProtocolViolationException”(“Expected at least 21538 bytes but there are only 69 bytes”)**
```csharp
var builder = WebApplication.CreateBuilder(args);

builder.WebHost.ConfigureKestrel(option => { option.ListenAnyIP(1883, l => l.UseMqtt()); });

builder.Services.AddHostedMqttServer(
    optionsBuilder => { optionsBuilder.WithDefaultEndpoint(); });
builder.Services.AddMqttConnectionHandler();
builder.Services.AddConnections();

var app = builder.Build();
app.UseRouting();

app.UseEndpoints(
    endpoints =>
    {
        endpoints.MapConnectionHandler<MqttConnectionHandler>(
            "/mqtt",
            httpConnectionDispatcherOptions => httpConnectionDispatcherOptions.WebSockets.SubProtocolSelector =
                protocolList => protocolList.FirstOrDefault() ?? string.Empty);
    });

app.UseMqttServer(
    server =>
    {
        //server.ValidatingConnectionAsync += MqttController.Server_ValidatingConnectionAsync;
        //server.ClientConnectedAsync += MqttController.MqttServer_ClientConnectedAsync;
        //server.ClientDisconnectedAsync += MqttController.MqttServer_ClientDisconnectedAsync;
        //server.ClientSubscribedTopicAsync += MqttController.MqttServer_ClientSubscribedTopicAsync;
        //server.ClientUnsubscribedTopicAsync += MqttController.MqttServer_ClientUnsubscribedTopicAsync;
        //server.InterceptingPublishAsync += MqttController.MqttServer_InterceptingPublishAsync;
    });

app.Run();
```

**Comment by Jeanot-Zubler** [comment]
My understanding is, with your configuration you are listening only to MQTT over TCP (port 1883). If you want to also listen for websockets, you need to listen to a different port. Basically:
```c#
builder.WebHost.ConfigureKestrel(option =>
{ 
    option.ListenAnyIP(1883, l => l.UseMqtt()); 
    option.ListenAnyIP(1884);
});
```
Then you can connect your websocket client to the port 1884.

**Comment by SuperCatss** [comment]
> My understanding is, with your configuration you are listening only to MQTT over TCP (port 1883). If you want to also listen for websockets, you need to listen to a different port. Basically:
> 
> ```cs
> builder.WebHost.ConfigureKestrel(option =>
> { 
>     option.ListenAnyIP(1883, l => l.UseMqtt()); 
>     option.ListenAnyIP(1884);
> });
> ```
> 
> Then you can connect your websocket client to the port 1884.

Maybe you're right, but the wiki prompted me to do this.
[https://github.com/dotnet/MQTTnet/wiki/Server#using-websockets-with-net50](url)

**Comment by Jeanot-Zubler** [comment]
The wiki does the exact same thing as i just suggested. It just uses port 5000 instead of 1884.

**Comment by SuperCatss** [comment]
> The wiki does the exact same thing as i just suggested. It just uses port 5000 instead of 1884.

Actually, you are right. Now my service is working in mqtt with websocket. Port 5000, I think it is used by Asp Net Core api. Because the annotation is **default http pipeline**, maybe this should be changed to **websocket**
