### ISSUE TITLE
Ability to set default Client ID for Server

### ISSUE THREAD

**Issue by Jeanot-Zubler** [dotnet/MQTTnet#1488]
### Describe the feature request
The API of injecting messages from the server is not really consistent with itself:
When creating a new `InjectedMqttApplicationMessage(MqttApplicationMessage applicationMessage)` the ClientID does not have to be set. However, for being able to actually inject this message, `SenderClientId` must not be `null`.
In Version 3, when publishing from the Server, the `ClientID` was always `null`.

### Which project is your feature request related to?
- Server

### Describe the solution you'd like
For me, the ideal solution would be to be able to assign a ClientID-like string to the server, that is used by default when injecting messages. This could then be overridden by the `SenderClientId`property of the `InjectedMqtttApplicationMessage`.

### Describe alternatives you've considered
1. Allow publishing messages with `ClientID == null` (Behaviour of library V3)
2. Require a non-null `SenderClientId` when creating an `InjectedMqttApplicationMessage`.

### Additional context
Thinking about it, this might actually be a bug, after solving issue #1470

**Comment by chkr1011** [comment]
I agree that it is better to enforce a client id for any injected application message. I will not yet change this to avoid breaking changes.

Since version 4 the client id is mandatory due to several new features so there is no way back 😄

**Comment by chkr1011** [comment]
Not when it comes to compiling but from business logic perspective. I recommend that you create an extension method in your project which always uses the same client ID internally. Another option is to encapsulate the server and provide your own (customized) API.
