### ISSUE TITLE
PINGREQ sent too late with low KeepAlivePeriod

### ISSUE THREAD

**Issue by Stannieman** [dotnet/MQTTnet#1490]
### Describe the bug
I see that PINGREQs are sometimes sent too late. When KeepAlivePeriod is set to something pretty short (2 seconds in my case) this leads to random disconnects from the broker. Especially on macOS this is pretty severe, Windows not so much, Linux was not tested.
The Macbook is the 2015 model so can't expect too much from it, but still...

I think this is because `MqttClient` uses `DateTime.UtcNow` to keep track of the elapsed time since the last message. If the system clock is not very steady or gets synced then, with a short keep alive, even a few seconds of "time travel" can cause a PINGREQ to be sent too late.

I am currently testing an `MqttClient` implementation that uses `System.Diagnostics.StopWatch` for tracking time. Once I am convinced it improves stability I will open a PR.

### Which component is your bug related to?
- Client

### To Reproduce
1. Set KeepAlivePeriod to something very short
2. Run the client on macOS
3. It disconnects randomly after a few minutes. If you check Wireshark you can see that a PINGREQ was missed.

### Expected behavior
It never disconnects as long as the network is stable.

**Comment by Stannieman** [comment]
I created a PR with Stopwatch as improvement already, but it does not fix the issue.

I found that the Task.Delay of 250ms in the ping loop occasionally takes way longer. We need to find a more reliable timer there.

**Comment by chkr1011** [comment]
Please try two things with the original code (not your already improved one with Stopwatch code):

Create the task runs the method _TrySendKeepAliveMessagesAsync_ in line from:

`_keepAlivePacketsSenderTask = Task.Run(() => TrySendKeepAliveMessagesAsync(backgroundCancellationToken), backgroundCancellationToken);`

to: 

`_keepAlivePacketsSenderTask = Task.Factory.StartNew(() => TrySendKeepAliveMessagesAsync(backgroundCancellationToken),
                        backgroundCancellationToken, 
                        TaskCreationOptions.PreferFairness | TaskCreationOptions.LongRunning,
                        TaskScheduler.Default);`

and let me know if it already works better.

**Comment by Stannieman** [comment]
Indeed I think some delay in thread scheduling or finding a free thread in the pool is the culprit here.

Currently trialing with Thread.Sleep(250) and running the entire TrySendKeepAliveMessagesAsync in a thread with priority Highest. It is the bad practice nuclear option but at least if this works then we know it is fixable :)

As for why Task.Delay takes so long in the first place, I'm not sure... Is it really the delay that takes too long, or does it take too long to resume the rest of the method?
If we run it in a long running task, doesn't ConfigureAwait(false) try to go to the pool anyway? If we have a dedicated thread from the long running task we may need to remove ConfigureAwait so it continues in the right thread.

**Comment by chkr1011** [comment]
For me it is okay if we have a real old school thread with high priority for this purpose. Keep alive is too important to avoid disconnects etc. so a blocking thread is worth it.

**Comment by Stannieman** [comment]
Long running task does not fix it. Also with removing ConfigureAwait in the ping loop makes no difference 😔

**Comment by chkr1011** [comment]
Do you also send messages (PUBLISH packets) while the issue appears or is it also happening when the client is "idle"?

**Comment by Stannieman** [comment]
It's idle, and even the machine is mostly idle. It is also happening waaaay less on Windows so maybe it is influenced by some OS scheduling. Will check if there happens to be a spike in CPU usage when it occurs.

**Comment by chkr1011** [comment]
Please try using the good old Timer class from the Threading namespace. If I remember it correctly it uses a different approach than just sleeping.

**Comment by Stannieman** [comment]
I tried System.Timers.Timer with both a timer that is restarted for every 250ms wait and one that keeps ticking continuously (just in case repeated restarting affects things). Still occurs in both cases.

System.Timers.Timer uses System.Threading.Timer internally but has a nicer API, guess it does not matter which one we use.
I think both System.Threading.Timer and Task.Delay use a System.Threading.TimerQueueTimer behind the scenes to do the timing.

Also tried with the new PeriodicTimer, same result. And it also uses System.Threading.TimerQueueTimer.

I'm running out of ideas. Oh the other hand it is very hard to believe that it is impossible to get some action to run reliably at an interval. Variations of even a few tens of milliseconds are acceptable but a 250ms delay that turns into 2000 is not. Maybe the code is fine but something in the runtime itself is not.

**Comment by logicaloud** [comment]
Just to clarify, have you measured the ~2000ms around `Task.Delay` or is it the `while` loop time?

**Comment by Stannieman** [comment]
Yes around the delay so it's not a network thing.

**Comment by logicaloud** [comment]
As you have observed with your own console application, I could not reproduce a problem when running 1000 async tasks, each with a `Task.Delay` of 250 ms (otherwise idle) in a NET 6 console application (2018 Mac Mini, MacOs Montery 12.5.1). The release mode build run outside of Visual Studio had max delays of 270 over 8 hours or so (so max 20ms out). Running in Debug mode within the IDE for an hour or two, I could see delays of up to ~750 ms (500 ms over).

If you can post a minimal example, maybe using the MQTTnet broker, that produces the problem on your side then I can try that with the hardware I have available.

Use of `DateTime.UtcNow` timestamps to measure short time periods is not ideal but I'd say it is unlikely to cause an issue on time synchronized systems and you'd be unlucky to run into a problem over a short observation period on non-synchronized systems.

**Comment by Stannieman** [comment]
I was unable to test last week, but back now. Will try to create a minimal repro.
Release mode has the same problem.

**Comment by Stannieman** [comment]
Ok there are very interesting developments!
The app in which I could reproduce it happened to be an Avalonia UI app. I looked futher in that direction and found:

* I cannot reproduce the issue with MQTTnet in a simple console app.
* I can reproduce the issue with MQTTnet in a boiler plate Avalonia desktop app (just default project template).
* AND in that basic Avalonia app without MQTTnet and only a bare Task.Delay in a loop it also occurs!

So that means this issue can be closed as it has nothing to do with MQTTnet. Sorry for wasting your time on this!
I will shift my focus to Avalonia now cause it must be doing some filthy things behind the scenes that cause the timers to break.

**Comment by Stannieman** [comment]
Just cause it's fun to look at:
So I put a while (true) with Task.Delay(250) in a minimal Avalonia app and everytime the delay takes more than 500ms it logs to console.

After 5 to 10 minutes this is what I got
`
Too long: 00:00:10.1278680
Too long: 00:00:01.4919020
Too long: 00:00:10.1362750
Too long: 00:00:10.0013450
Too long: 00:00:10.0012170
Too long: 00:00:10.0014200
Too long: 00:00:10.0012190
Too long: 00:00:10.0014000
Too long: 00:00:10.0014770
Too long: 00:00:10.0012340
Too long: 00:00:10.0298920
Too long: 00:00:09.9944410
Too long: 00:00:10.0013260
Too long: 00:00:10.0011620
Too long: 00:00:10.0011870
Too long: 00:00:10.0100230
Too long: 00:00:10.0057740
Too long: 00:00:10.0125380
Too long: 00:00:10.0072980
Too long: 00:00:10.0296070
Too long: 00:00:09.9992390
Too long: 00:00:10.0023670
Too long: 00:00:10.0020110
Too long: 00:00:10.0019850
Too long: 00:00:10.0063740
Too long: 00:00:09.9987900
Too long: 00:00:10.0016140
Too long: 00:00:01.4810180
Too long: 00:00:10.0016090
Too long: 00:00:20.0312540
Too long: 00:00:19.9925110
Too long: 00:00:20.0018100
Too long: 00:00:20.0017170
Too long: 00:00:20.0116750
Too long: 00:00:19.9987460
Too long: 00:00:20.0019690
Too long: 00:00:20.0016450
Too long: 00:00:20.0018110
Too long: 00:00:03.6547710
Too long: 00:00:02.4756200
Too long: 00:00:02.5731120
Too long: 00:00:03.6644760
`
I think this qualifies as off the charts crazy.

**Comment by logicaloud** [comment]
Interesting; thanks for the update. I wonder if running the MQTT client or `Task.Delay` on a separate long running task with `Task.Delay(...).ConfigureAwait(false) and with dispatch of any relevant messages onto the UI thread may help in this case.

**Comment by chkr1011** [comment]
@Stannieman  Wow this are amazing news because I have the same issue in my Avalonia app "MQTTnetApp" (https://github.com/chkr1011/MQTTnetApp) which is a Postman-like tool for MQTT communication. I also randomly disconnects due to missing keep alive. Especially when the application is idle.

Are you gonna open a ticket in the Avalonia project including all the information above? If not I would like to do so.

**Comment by Stannieman** [comment]
@chkr1011 here you go: https://github.com/AvaloniaUI/Avalonia/issues/8883#issuecomment-1236059239
