### ISSUE TITLE
Are topic permissions possible on MQTTnet

### ISSUE THREAD

**Issue by iainwhiteigs** [dotnet/MQTTnet#1491]
### Describe your question
I'd like to know whether I can use topic permissions in MQTTnet. I'm thinking about the kind of thing [here](https://www.hivemq.com/blog/mqtt-security-fundamentals-authorization/)

For example, one user might only have 'subscribe' permissions to one topic and 'publish' permissions to another topic. Is there a way to implement this?

### Which project is your question related to?
- Server

**Comment by iainwhiteigs** [comment]
I think I've found the answer  - I can use message interceptors and subscription interceptors as described [here] (https://github.com/dotnet/MQTTnet/wiki/Server#intercepting-subscriptions) and [here](https://github.com/dotnet/MQTTnet/wiki/Server#intercepting-application-messages)

**Comment by Jeanot-Zubler** [comment]
An concept of how to do it can be found here https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfig/blob/master/src/NetCoreMQTTExampleJsonConfig/Program.cs , though it uses version 3 of this library. The basic concept is, that you have the `ClientId` in every Subscription and Publish. During Connection, you have `ClientId`, `UserName` and `Password` available to associate the ID with a specific user.

**Comment by chkr1011** [comment]
You can also put custom data at the session items dictionary passed in the event args. This session items are available in mostly all event args (since version 4.1). So you can pass the user name to the session items and receive it in the other events.
