### ISSUE TITLE
WebSocket Client

### ISSUE THREAD

**Issue by Hulkstance** [dotnet/MQTTnet#1507]
Hi,

I really like the way you handle backpressure, e.g. https://github.com/dotnet/MQTTnet/blob/master/Source/MQTTnet.Extensions.ManagedClient/ManagedMqttClient.cs#L174 and the code base looks pretty. Is there a raw websocket client project of yours?

**Comment by chkr1011** [comment]
Sorry but we do not have our own web socket implementation and there are no plans for implementing such a thing.
