### ISSUE TITLE
Expected at least 21538 bytes but there are only 69 bytes 

### ISSUE THREAD

**Issue by whzooo** [dotnet/MQTTnet#1510]
### Describe your question

■■■■■■ logLevel:Verbose source:MqttTcpServerListener message:Client '127.0.0.1:57459' accepted by TCP listener '0.0.0.0:8001, ipv4'.
■■■■■■ logLevel:Error source:MqttClientSessionsManager message:Expected at least 21538 bytes but there are only 69 bytes 
■■■■■■ logLevel:Verbose source:MqttTcpServerListener message:Client '127.0.0.1:57459' disconnected at TCP listener '0.0.0.0:8001, ipv4'.
■■■■■■ logLevel:Verbose source:MqttTcpServerListener message:Client '127.0.0.1:58205' accepted by TCP listener '0.0.0.0:8001, ipv4'.
■■■■■■ logLevel:Error source:MqttClientSessionsManager message:Expected at least 21538 bytes but there are only 69 bytes 
■■■■■■ logLevel:Verbose source:MqttTcpServerListener message:Client '127.0.0.1:58205' disconnected at TCP listener '0.0.0.0:8001, ipv4'.

### Which project is your question related to?

- Client
- ManagedClient
- Server
- Generic

**Comment by Jeanot-Zubler** [comment]
I think this is the same issue as #1484

**Comment by chkr1011** [comment]
@Jeanot-Zubler I also think so. @whzooo Please reopen this ticket if the mentioned solution does not work.
