### ISSUE TITLE
The documentation for version 4 or the samples are not straightforward.

### ISSUE THREAD

**Issue by zeitmeister** [dotnet/MQTTnet#1524]
### Describe your question
A clear and concise description of what you want to know.
I feel like that the new version of MQTTnet is lacking som documentation. 
I'm trying to use the client subscribe samples but the event handler code is only run when i include the `Console.ReadLine() `as stated in the `Handle_Received_Application_Message`-function in the Subscribe samples. 
Is the ReadLine-statement necessary for receiving many messages in order. That doesn't make much sense to me.
Another question that I can't really seem to get answered by the current documentation is if I need to connect to the broker for every message I want to publish as the Clients Publish samples seems to state.

Hope I have made my case clear enough.
Kind regards!
### Which project is your question related to?

- Generic

**Comment by chkr1011** [comment]
The _ReadLine()_ statement is required because the console application will close otherwise and thus no more receiving is done. In your application you may handle this differently. 

You can for sure send multiple messages using the same client and connection. I added a sample for this.
