### ISSUE TITLE
Where is my "public static class MqttServerExtensions" ?

### ISSUE THREAD

**Issue by lianggan13** [dotnet/MQTTnet#1526]
### Describe your question
Oh, my god, What do you do? 
When I update the version from  [3.1.2] to [4.1.0.247], I can't find the extension metod -- " public static Task<MqttClientPublishResult> PublishAsync(this IMqttServer server, string topic)"

### Which project is your question related to?
- Server

**Comment by chkr1011** [comment]
This method is renamed to InjectApplicationMessageAsync because it actually does not publish anything. Please read release notes from 4.0 and have a look at the Samples directory in the solution for more information.

**Comment by lianggan13** [comment]
thank you！
