### ISSUE TITLE
How the client sends messages to the server (broker) ?

### ISSUE THREAD

**Issue by lianggan13** [dotnet/MQTTnet#1530]
### Describe your question
Can the client send messages to the server (broker)?
Can the server (broker) receive messages from client ?
If can, how?

### Which project is your question related to?
- Client
- Server

**Comment by SeppPenner** [comment]
To be correct, a "direct" communication between client and server is not possible in MQTT as that's not how the protocol works.
What you can do:
1. Create a server that listens on all packages.
2. Create a client that publishes on a certain topic (I would recommend `$SYS\...` (... is your sub-topic, of course) for that.
3. Let the server read the incoming messages and decide what to do. Examples can be found below:

The server can handle incoming messages like this:

```csharp
public void Startup()
{
    var optionsBuilder = new MqttServerOptionsBuilder()
        .WithDefaultEndpoint()
        .WithDefaultEndpointPort(1883)
        .WithEncryptedEndpointPort(8883);

    var mqttServer = new MqttFactory().CreateMqttServer(optionsBuilder.Build());
    mqttServer.InterceptingPublishAsync += this.InterceptApplicationMessagePublishAsync;
    mqttServer.StartAsync();
}
    
public Task InterceptApplicationMessagePublishAsync(InterceptingPublishEventArgs args)
{
    // Do whatever you like with args.
    // ...
    // Allow publish.
    args.ProcessPublish = true;
    // Or don't allow publish.
    //args.ProcessPublish = false;
    return Task.CompletedTask;
}
```

The client can send messages like this:

```csharp
public static async Task Publish_Application_Message()
{
    var mqttFactory = new MqttFactory();

    using (var mqttClient = mqttFactory.CreateMqttClient())
    {
        var mqttClientOptions = new MqttClientOptionsBuilder()
            .WithTcpServer("127.0.0.1")
            .Build();

        await mqttClient.ConnectAsync(mqttClientOptions, CancellationToken.None);

        var applicationMessage = new MqttApplicationMessageBuilder()
            .WithTopic("$SYS/something")
            .WithPayload("Do something, server!")
            .Build();

        await mqttClient.PublishAsync(applicationMessage, CancellationToken.None);

        await mqttClient.DisconnectAsync();
            
        Console.WriteLine("MQTT application message is published.");
    }
}
```

Please also have a look at the samples under https://github.com/dotnet/MQTTnet/tree/master/Samples and e.g. my project under https://github.com/SeppPenner/SimpleMqttServer/blob/master/src/SimpleMqttServer/MqttService.cs.

**Comment by SeppPenner** [comment]
> Yeah，that's pretty cool. Thank you !

Glad that I could help you :)
