### ISSUE TITLE
Upgrade guide from v3 to v4

### ISSUE THREAD

**Issue by Rod-O** [dotnet/MQTTnet#1533]
### Describe the feature request
Is your feature request related to a problem? 
I have a big project using this library, but upgrading from v3 to v4 seems impossible, 
specially without documentation, I can't find anything.
current asp.net example is for v3
I'm stuck with v3

Please describe.
I just need a guide to upgrade.

### Which project is your feature request related to?
I'm using ASP.net core 6

### Describe the solution you'd like
a Wiki ?  yes

**Comment by chkr1011** [comment]
Please check:
* Release notes from version 4 (https://www.nuget.org/packages/MQTTnet/4.0.0.167#release-body-tab)
* Upgrade guide in Wiki (https://github.com/dotnet/MQTTnet/wiki/Upgrading-guide)
* Samples for version 4 (https://github.com/dotnet/MQTTnet/tree/master/Samples)
