### ISSUE TITLE
How does the mqttserver v4 version server send messages, in version 3.1.2 IMqttServer support using the PublishAsync method

### ISSUE THREAD

**Issue by jiangzhuangxiansheng** [dotnet/MQTTnet#1536]
### Describe the feature request

【Hello,How does the mqttserver v4 version server send messages, in version 3.1.2 IMqttServer support using the PublishAsync method】

### Which project is your feature request related to?

- Client
- ManagedClient
- Server
- Generic

**Comment by SeppPenner** [comment]
The best is to have a look at the samples folder: https://github.com/dotnet/MQTTnet/tree/master/Samples:

```csharp
var mqttFactory = new MqttFactory();

using (var mqttClient = mqttFactory.CreateMqttClient())
{
    var mqttClientOptions = new MqttClientOptionsBuilder()
        .WithTcpServer("broker.hivemq.com")
        .Build();

    await mqttClient.ConnectAsync(mqttClientOptions, CancellationToken.None);

    var applicationMessage = new MqttApplicationMessageBuilder()
        .WithTopic("samples/temperature/living_room")
        .WithPayload("19.5")
        .Build();

    await mqttClient.PublishAsync(applicationMessage, CancellationToken.None);

    await mqttClient.DisconnectAsync();
            
    Console.WriteLine("MQTT application message is published.");
}
```

**Comment by jiangzhuangxiansheng** [comment]
Instead of creating a new client, I want to send messages through the server

**Comment by MD-V** [comment]
Use InjectApplicationMessage of MqttServer class.

https://github.com/dotnet/MQTTnet/blob/a3227a444a7ad68c60c8fa4245094dba18fe99fd/Source/MQTTnet/Server/MqttServer.cs#L211

**Comment by timothyparez** [comment]
I also had to dig through the issues to find this answer.
Perhaps someone can add it to https://github.com/dotnet/MQTTnet/wiki/Upgrading-guide

**Comment by SeppPenner** [comment]
The problem is that the wiki will not be updated anymore (It's just a reference for version 3.x and below) and we just use the examples from the https://github.com/dotnet/MQTTnet/tree/master/Samples folder.
