### ISSUE TITLE
How to subscribe to several topics

### ISSUE THREAD

**Issue by HenrikJuulsgaard** [dotnet/MQTTnet#1538]
I'm trying to subscribe to several topics using topicfilterbuilder...

![image](https://user-images.githubusercontent.com/39522208/195331785-69a7ef8e-508d-4458-b64a-866d18aa3a34.png)
what is the best way, first try to create a topicList don't work, any suggestion anyone ?

Thanks in advance, Henrik

### Discussed in https://github.com/dotnet/MQTTnet/discussions/1485

<div type='discussions-op-text'>

<sup>Originally posted by **carrisian** August  8, 2022</sup>
I have several topic for example:
/server/identify
/sever/control
/server/take/object
I want to subscribe to everything on the level server

I try to execute this code and it doesn't work.

_private async Task mqttClient_ConnectedAsync(MqttClientConnectedEventArgs arg)
        {      
            await mqttClient.SubscribeAsync(new MqttTopicFilterBuilder().WithTopic("/server/#").Build());
        }_

What's wrong? Thank you in advanced

</div>

**Comment by Jeanot-Zubler** [comment]
You can create `MqttClientSubscribeOptions` containing multiple topic filters. A simple example would look like this:
```csharp
var mqttClient = new MqttFactory().CreateMqttClient();
        var topics = new List<string> { "/server/topic1", "testtopic", "my/topic/#/with/wildcard" };
        var options = new MqttClientSubscribeOptionsBuilder();
        foreach (var topic in topics)
        {
            options.WithTopicFilter(topic);
        }

        await mqttClient.SubscribeAsync(options.Build());
```

**Comment by chkr1011** [comment]
@HenrikJuulsgaard I added a sample to the master branch. It is basically the same as @Jeanot-Zubler suggested.

**Comment by HenrikJuulsgaard** [comment]
Solution works perfectly!
Thank you all, much appreciated.
