### ISSUE TITLE
MqttServer stops responding

### ISSUE THREAD

**Issue by FYN-Michiel** [dotnet/MQTTnet#1542]
Using version 4.1.1.318 the MqttServer sometimes stops responding/processing to new messages after a while.
When reverting to 4.1.0.247 everything returns to normal (no other code changes).

We use an MQTTnet MqttServer on localhost to communicate between processes, this runs on about 75+ machines.
It doesn't happen on every machine (about 1:10) and doesn't happen very often (about every other day).

Working on a way to reproduce this (or provide more information), doesn't want to occur on our debug machines.

### Code example
Please provide full code examples below where possible to make it easier for the developers to check your issues.

**Ideally a Unit Test (which shows the error) is provided so that the behavior can be reproduced easily.**
 
```csharp
    public void Start(Int32 port, String username, String password)
    {
        _username = username;
        _password = password;
        MqttServerOptionsBuilder optionsBuilder = new MqttServerOptionsBuilder()
            .WithDefaultEndpoint()
            .WithDefaultEndpointPort(port);
        
        MqttServer = new MqttFactory().CreateMqttServer(optionsBuilder.Build());
        MqttServer.ValidatingConnectionAsync += MqttServerOnValidatingConnectionAsync;
        MqttServer.StartAsync();
    }
    private Task MqttServerOnValidatingConnectionAsync(ValidatingConnectionEventArgs arg)
    {
        if (!String.Equals(arg.UserName, _username, StringComparison.Ordinal) || !String.Equals(arg.Password, _password, StringComparison.Ordinal))
        {
            arg.ReasonCode = MqttConnectReasonCode.BadUserNameOrPassword;
            return Task.CompletedTask;
        }

        arg.ReasonCode = MqttConnectReasonCode.Success;
        return Task.CompletedTask;
    }

    public MqttServer MqttServer;
```

**Comment by chkr1011** [comment]
I created a branch for this ticket. It is possible that you test a build from the myget feed? I will then revert the changes one by one from the latest version so find the root cause. If you can also build the repo directly for testing, please let me know.

**Comment by FYN-Michiel** [comment]
Can absolutely test dev builds (as long as they are signed), just let me know which one to pull (and allow for a few days of testing).

**Comment by chkr1011** [comment]
OK will let you know as soon I have a build available on the myget feed.

And you don't attach any other event handlers?

**Comment by FYN-Michiel** [comment]
> And you don't attach any other event handlers?

There are no other handlers attached, all logic is done through the clients.

> @FYN-Michiel Please try build 4.1.1.336 from the myget feed and let me know if it works better.

Pulled version 4.1.1.339, will be released to the machines tomorrow, will report back later.
Thanks for the work so far.

**Comment by chkr1011** [comment]
@FYN-Michiel Please use the exact version I posted. Other versions are from other feature branches so they may do not contain the actual fix. In the meantime, I figured out some issues in the _AsyncLock_ replacement and fixed them. Now please try version x.x.x.340.

**Comment by FYN-Michiel** [comment]
Pushing x.x.x.340 now, will report back after a few days.

**Comment by FYN-Michiel** [comment]
Thanks, no more issues have been found, many thanks for the support :)
