### ISSUE TITLE
Add underlying SocketOption of TCP KeepAlive into the server option

### ISSUE THREAD

**Issue by Seamus3131** [dotnet/MQTTnet#1544]
### Describe the feature request
It appears that by default an opened socket is not configured with a TCP-KeepAlive flag. No TCP-KeepAlive set can lead to kind of DDOS attacks.
I would like to be able to configure at IMqttServer level these TCP-KeepAlive through available SocketOption up-front.

### Which project is your feature request related to?
- Server

### Describe the solution you'd like
In MqttServerTcpEndpointOptions add the SocketOption for TCP-KeepAlive control
KeepAlive
TcpKeepAliveInterval
TcpKeepAliveRetryCount
TcpKeepAliveTime

Update CrossPlatformSocket to set the socketOption when opening the socket

### Additional context

Many thanks

**Comment by Seamus3131** [comment]
Hello, listening socket only in my case.
Thank you

**Comment by chkr1011** [comment]
The feature is now implemented in the branch attached to this ticket. Please check it out and let me know if it works as you expect.
