### ISSUE TITLE
possible bug in server repeatedly sending the same message to client subscribed with cleanSession=false

### ISSUE THREAD

**Issue by dkavicki** [dotnet/MQTTnet#1546]
1 ) I've implemented simple server to work with my managed client like this :
/ Create the options for MQTT Broker
var options = new MqttServerOptionsBuilder()
    //Set endpoint to localhost
    .WithDefaultCommunicationTimeout(TimeSpan.FromMinutes(10))
    .WithPersistentSessions()
    .WithDefaultEndpoint();
// Create a new mqtt server
var server = new MqttFactory().CreateMqttServer(options.Build());
await server.StartAsync();
// Keep application running until user press a key
Console.WriteLine("Broker Started. Press Enter to exit.");
Console.ReadLine();
// Stop and dispose the MQTT server if it is no longer needed!
await server.StopAsync();

2) My managed client connects to the server with CleanSession=false and subscribes to some topics
 var options = new ManagedMqttClientOptionsBuilder()
            //.WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
            .WithClientOptions(new MqttClientOptionsBuilder()
                .WithClientId("dda-mqtt-client")
                .WithTcpServer("localhost")
                .WithCleanSession(false)
                .WithSessionExpiryInterval(9999)
                .WithKeepAlivePeriod(TimeSpan.FromMinutes(1))
                .WithWillQualityOfServiceLevel(MQTTnet.Protocol.MqttQualityOfServiceLevel.ExactlyOnce)
                .WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V500)
                .Build())
            .Build();

        var mqttClient = new MqttFactory().CreateManagedMqttClient();

In connected handler first time I connect I get (as expected)
arg.ConnectResult.IsSessionPresent = false
Then I disconnect and connect again and this time I get (expected)
arg.ConnectResult.IsSessionPresent = true
Then I disconnect again.

3) Using another second client I connect to the server and publish some message to the topic the first client has subscribed

4) I start the first client again and immediately got the message the second client has published in the MqttClient_ApplicationMessageReceivedAsync handler (expected) 
At the end of handler I set MqttApplicationMessageReceivedEventArgs.IsHandled = true

5) Now I disconnect/stop the first client again and start it back, and again I'm getting the same message I already have gotten before
And, according to my understanding this is wrong.

I have tested the same scenario using the mosquito 2.0.10 server and it was not showing behaviour in 5). It only sent the message to my client once, no matter how many times I've disconnected and reconnected afterwards

Thank you

Dean

**Comment by chkr1011** [comment]
Did you published the message as retained? If so the client will get the message on every connect because it gets subscribed on every connect.

**Comment by dkavicki** [comment]
> Did you published the message as retained? If so the client will get the message on every connect because it gets subscribed on every connect.

Thanks, I know this about retaining and then you need to explicitely delete it on the broker by sending empty payload

But I did not publish using WithRetainFlag
Here is the snippet I was using for publishing

    var msg = new ManagedMqttApplicationMessageBuilder()
                            .WithApplicationMessage(new MqttApplicationMessageBuilder()
                                .WithPayload(payload)
                                .WithTopic(topc)
                                .WithQualityOfServiceLevel(MQTTnet.Protocol.MqttQualityOfServiceLevel.ExactlyOnce)
                                .WithResponseTopic(responseTopic").Build()).Build();
    await managedMqttClient.EnqueueAsync(msg);

**Comment by mark-trumed** [comment]
I am seeing the same behavior when publishing messages from the broker via calls to InjectApplicationMessage().

If there are multiple client disconnects/reconnects, every time a client reconnects it receives persisted application messages that were sent after all previous reconnects. I have also validated that all the application messages are being acknowledged by the client.

It appears that the persisted application messages are not being cleared by the broker after a client reconnects and has received and acknowledged them.

**Comment by chkr1011** [comment]
@dkavicki  I created a branch for this ticket and tried to reproduce the issue based on the code fragments you posted. But I had no luck and the code works fine. Probably I did not get the problem completely. 

Please pull the code and check unit test _Receive_While_Not_Cleanly_Disconnected_ and change it so that the issue appears as described.

**Comment by dkavicki** [comment]
> @dkavicki I created a branch for this ticket and tried to reproduce the issue based on the code fragments you posted. But I had no luck and the code works fine. Probably I did not get the problem completely.
> 
> Please pull the code and check unit test _Receive_While_Not_Cleanly_Disconnected_ and change it so that the issue appears as described.

Hi thank you; just a quick update. 
I'm on it and also cannot reproduce, whatever I have tried so far. I will continue and keep you posted.

**Comment by dkavicki** [comment]
@chkr1011 
Hi Christian, there are couple of differences in the unit test code comparing to my scenario.
First one is that the you create a managedClient, subscribe, create ApplicationMessageReceivedAsync handler and startAsync
and then using the senderClient you publish the message. 
At this point, immediatelly the ApplicationMessageReceivedAsync  is invoked and the receivedMessage list is added an item.

My scenario is that I before publishing with the senderClient stop managed client and then after publish with the sender client start it again. And this is not the same start as you do it in the single process, My managedClient is a separate app.

I tried modifying UnitTest to do this but discovered that the ApplicationMessageReceivedAsync handler still lives after I stop the managedClient and as soon as I publish with the senderClient it is being invoked, before I start the managedClient again.

So I did ApplicationMessageReceivedAsync handler in a way I can do add and removal of the handler
managedClient.ApplicationMessageReceivedAsync += myHandler;
managedClient.ApplicationMessageReceivedAsync -= myHandler;

but at this point I got strange behaviour that such defined handler is not called.
Hope this might somehow shed some light for you
I'm stopping for today, will continue tomorrow
Cheers
Dean

**Comment by dkavicki** [comment]
@chkr1011 I tried pushing my changes but I cannot. Looks like I don't have permission. Or maybe I'm doing something else wrong. Could you please check it out and give me some hints
Thanks
Dean

**Comment by dkavicki** [comment]
@chkr1011 I tried debugging the MqttNet Server code and in MqttSession.cs in EnqueueDataPacket method there is a code :

            if (publishPacket.QualityOfServiceLevel > MqttQualityOfServiceLevel.AtMostOnce)
            {
                    publishPacket.PacketIdentifier = _packetIdentifierProvider.GetNextPacketIdentifier();
                    _unacknowledgedPublishPackets[publishPacket.PacketIdentifier] = publishPacket;
            }
From what I was able to deduce, for some reason, in my scenario, this _unacknowledgedPublishPackets dictionary gets inserted two times with the same publishPacket
Doing the simple check if the publishPacket is already in the dictionary I was able to make my scenario working right

            if (publishPacket.QualityOfServiceLevel > MqttQualityOfServiceLevel.AtMostOnce)
            {
                if (!_unacknowledgedPublishPackets.Values.Contains(publishPacket))
                {
                    publishPacket.PacketIdentifier = _packetIdentifierProvider.GetNextPacketIdentifier();
                    _unacknowledgedPublishPackets[publishPacket.PacketIdentifier] = publishPacket;
                }
            }
Of course, I cannot be sure that this would not cause some other side effects  in different cases
So, hopefully, it will shed some light to you on what could be going wrong here 
Cheers
Dean

**Comment by chkr1011** [comment]
@dkavicki Thanks for pointing into the right direction. I fixed the issue which adds the publish packets by accident when the session is being recovered. Please try the branch attached to this ticket and let me know if it works.

**Comment by BlackBooth** [comment]
I can confirm, that the server now works the way it should. Thank you for fixing!

**Comment by dkavicki** [comment]
I can confirm as well that the issue is not happening anymore. Thanks Christian!
Cbeers
Dean
