### ISSUE TITLE
Subscribing to MqttServer.ClientAcknowledgedPublishPacketAsync results in two events for every published application message

### ISSUE THREAD

**Issue by mark-trumed** [dotnet/MQTTnet#1550]
### Describe the bug
After creating an MqttServer instance, I add an event handler for ClientAcknowledgedPublishPacketAsync:
_mqttServer.ClientAcknowledgedPublishPacketAsync += OnClientAcknowledgedPublishPacketAsync;

Every time a message is published to a client and acknowledged by the client, the event handler function OnClientAcknowledgedPublishPacketAsync() is called twice.

### Which component is your bug related to?
- Server

### To Reproduce
Using version 4.1.2.350 of MQTTnet.
See the description for steps to reproduce.

### Expected behavior
When a client receives and acknowledges a message, the ClientAcknowledgedPublishPacketAsync event handler is only called once.

### Screenshots
n/a

### Additional context / logging
n/a

**Comment by mark-trumed** [comment]
@chkr1011 Yes, messages were published as QoS 2.

**Comment by chkr1011** [comment]
Ok then I assume this is the issue. I will fix this so that the event only gets called after the PUBCOMP message is received because only this message clearly marks the successful end of the transfer process.

**Comment by mark-trumed** [comment]
@chkr1011 Thank you.
