### ISSUE TITLE
mqttnet client   network is disconnected 

### ISSUE THREAD

**Issue by jiangzhuangxiansheng** [dotnet/MQTTnet#1558]
hello I use mqttnet version [v4.1.2.350] when the network is disconnected, there will be no response when I connect to the server, WIthTimeout is set for 3 seconds, I hope it can tell me that the connection is not successful

**Comment by chkr1011** [comment]
If you pass a cancellation token (with automatic timeout) in the _ConnectAsync_ method, you will get the cancellation exception if the connection was not possible. This also includes disabled WiFi etc. The timeout option is not yet used as a fallback when there was no cancellation token passed. This will be changed soon.
