### ISSUE TITLE
MQTTnet is missing with Windows service.

### ISSUE THREAD

**Issue by VentsislavDinev** [dotnet/MQTTnet#1559]
I create C# windows service solution with MQTTnet  for communication between Windows server and IoT devices. When I try to build this service from Visual studio I can, when I try to run this service from sc.exe and Services.exe application I can't because MQTTnet library is missing 

System.IO.FileNotFoundException: 'Could not load file or assembly 'MQTTnet, Version=4.1.2.350, Culture=neutral, PublicKeyToken=fdb7629f2e364a63' or one of its dependencies. The system cannot find the file specified.'

**Comment by chkr1011** [comment]
Please also reference the MQTTnet nuget package and not only extensions like the managed client. Additionally, you can try to set the "Copy local" property to true for the MQTTnet assembly.
