### ISSUE TITLE
MqttClient.SendAndReceiveAsync will never finish if disconnect happen between send and recv.

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/MQTTnet#1561]
### Describe the bug
MqttClient.SendAndReceiveAsync will never finish if disconnect happen between send and recv

### Which component is your bug related to?
- Client 4.1.2.350 (since 3.0.0)

### To Reproduce
```cs
        static async Task Main(string[] args)
        {
            var factory = new MqttFactory();
            var srv = factory.CreateMqttServer(new MqttServerOptionsBuilder()
                .WithDefaultEndpoint()
                .Build());
            await srv.StartAsync();
            srv.ClientSubscribedTopicAsync += (ev) =>
            {
                return srv.DisconnectClientAsync(ev.ClientId, MQTTnet.Protocol.MqttDisconnectReasonCode.NormalDisconnection);
            };
            var cli = factory.CreateMqttClient();
            await cli.ConnectAsync(new MqttClientOptions
            {
                ClientId = "aaa",
                CleanSession = true,
                ChannelOptions = new MqttClientTcpOptions
                {
                    Server = "127.0.0.1",
                    Port = 1883
                }
            });
            try
            {
                await cli.SubscribeAsync("#");
            } catch (Exception ex) { }
            Console.WriteLine("Finished");
        }
```

### Expected behavior
`SubscribeAsync()` should finished with exception, instead of never finish after client is disconnect.

**Comment by chkr1011** [comment]
This seems to be the case for all async calls which are waiting for ACK packets. I fixed this in the attached branch and added more unit tests. Thanks for providing the sample code. It makes finding the issue very easy for me. Please try the code from the attached branch of this ticket and let me know if it works better.

**Comment by yyjdelete** [comment]
@chkr1011 Thanks, the new branch works well for me
