### ISSUE TITLE
High CPU Load from AsyncSignal

### ISSUE THREAD

**Issue by sebastian-dev** [dotnet/MQTTnet#1565]
The locking in AsyncSignal.cs looks wrong. 
`public void Set()` _isSignaled = false
and in `WaitAsync` _isSignaled = true;

otherwise the _isSignaled makes no sense until _isSignaled is never reset.

with the implementation before:
[1552 mqttnetservermqttclientsessionsmanager subscribersessions is](https://github.com/dotnet/MQTTnet/commit/2842f27522fb3f5dbcb781e423564b1ef65043cf)
everything was fine.

Fix??
```
public void Set()
        {
            lock (_syncRoot)
            {
                // If there is already a waiting task let it run.
                _waiter?.Approve();
                _waiter = null;
                _isSignaled = false;
            }
        }
```
```
public Task WaitAsync(C..
....
if (_isSignaled)
                {
                    return CompletedTask.Instance;
                }
                _isSignaled = true;
```

**Comment by chkr1011** [comment]
Thanks for reporting this issue. I attached a branch to this ticket where some issues are fixed with the new async signal. I also found another edge case which was not yet covered in the unit tests.

Please let me know if the solution works for you.

**Comment by chkr1011** [comment]
Thanks for providing feedback.
