### ISSUE TITLE
Receiving Topics Not Subscribed To

### ISSUE THREAD

**Issue by leemorton** [dotnet/MQTTnet#1576]
### Describe the bug
I followed the wiki for the managed client and when subscribing to a specific topic  I am receiving messages from all topics. 
I have removed my abstractions so its just MQTTnet code and reproduced in the example below.
Is this an issue or probably more likely something I am doing wrong?

### Which component is your bug related to?
- ManagedClient

### To Reproduce
Steps to reproduce the behaviour:

```csharp
var listenTopic = $@"Apple/Banana/Orange";

var mqttFactory = new MqttFactory();
var mqttManagedClient = mqttFactory.CreateManagedMqttClient();

var managedMqttClientOptions = _configuration
    .GetSection(key: "MqttBrokerConnection")?
    .Get<MqttBrokerConnection>()?
    .BuildManagedMqttClientOptions();

mqttManagedClient.ConnectedAsync += connectedEvent => {
    _logger.LogInformation($"Listening for [{listenTopic}]");
    return Task.CompletedTask;
};
mqttManagedClient.ApplicationMessageReceivedAsync += messageEvent => {
    _logger.LogInformation($"Message received: [{messageEvent.ApplicationMessage.Topic}]: {Encoding.UTF8.GetString((messageEvent.ApplicationMessage.Payload ?? new byte[0]))}");
    return Task.CompletedTask;
};

await mqttManagedClient.SubscribeAsync(listenTopic);
_logger.LogInformation($"Subscribed");
await mqttManagedClient.StartAsync(managedMqttClientOptions);
```
### Expected behaviour
To only receive messages sent to "Apple/Banana/Orange"

### Actual Behaviour
Receiving messages of any topic. e.g.
```
Listening for [Apple/Banana/Orange]
Message received: [Carrot/Onion]: {
    "msg": "Hello"
}
```

**Comment by leemorton** [comment]
I just found that it works if I run `await mqttManagedClient.UnsubscribeAsync("#");` before I start my subscriptions. I did not see this mentioned in the wiki (maybe I missed it somewhere though).

Does it sound correct that I should have to unsubscribe from # first? Can the connection be made without any topics initially as I would be worried about an initial flood of topics beating the unsubscribe action.

**Comment by chkr1011** [comment]
No, unsubscribing "#" should not be required. I tried to reproduce your issue but was not able to do so. Which broker do you use? I assume that the error is coming from your code because also not any of our unit test fails.

**Comment by leemorton** [comment]
I removed the unsubscribe action after and everything worked as expected without it again.
I am wondering whether it is the case that the broker remembers a previous subscribe to “#” when using the same clientid before? Which is why everything started working after unsubscribe just once.

Do the brokers remember clientid subscriptions even across different sessions/clients? I am using Mosquitto.

**Comment by chkr1011** [comment]
The broker is indeed able to remember the subscriptions. This requires the "clean session" flag set to "False". Then you are able to receive messages which were published while the client is offline.
