### ISSUE TITLE
Bug of MqttBufferReader

### ISSUE THREAD

**Issue by xljiulang** [dotnet/MQTTnet#1592]
### Verification
```c#
var buffer1 = new byte[] { 5, 6, 7, 8, 9 };
var buffer2 = new byte[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };

var segment1 = new ArraySegment<byte>(buffer1);
var segment2 = new ArraySegment<byte>(buffer2, 5, 5);
Debug.Assert(segment1.SequenceEqual(segment2));

var reader1 = new MqttBufferReader();
reader1.SetBuffer(segment1.Array, segment1.Offset, segment1.Count);

var reader2 = new MqttBufferReader();
reader2.SetBuffer(segment2.Array, segment2.Offset, segment2.Count);

// Assert failure here!!!
// reader1.BytesLeft == 5
// reader2.BytesLeft == 0
Debug.Assert(reader1.BytesLeft == reader2.BytesLeft);
```

### Describe the bug
I think it is probably a bug caused by the ambiguity of the `length` and `_length` in it, so what does `length` `_length` really mean?
Personally, I think the following understanding may be more accurate:

#### Parameter `length`
The number of elements in the range delimited by the `ArraySegment`.  It's value == arraySegment.Count

#### Field `_length`
The max position of input buffer,  It's value == arraySegment.Count + arraySegment.Offset

If we don't want to change the name of the field or parameter, here's how to fix the bug:
```c#
  public void SetBuffer(byte[] buffer, int position, int length)
  {
      _buffer = buffer;
      _initialPosition = position;
      _position = position;
      _length = length;   ==>   _length = position + length;
  }
```

But I prefer to add a new method，and then I don't have to think about whether the `length`  and `_length` is `ArraySegment.Array.Length` or `ArraySegment.Count`:

```
public void SetBuffer(ArraySegment<byte> buffer)
```

**Comment by xljiulang** [comment]
If we rename `_length` to `_maxPosition`, the problem would be easier to understand.

**Comment by chkr1011** [comment]
Thanks for reporting the issue. I attached a branch to this ticket and fixed the issue.
I also added some unit test according to your sample code.

Please have a look and share your thoughts. I will still add some more tests.

**Comment by simonthum** [comment]
I'm looking into a quite strange issue with MQTTnet not receiving messages on Mosquitto 2.x but receiving fine with 1.6.x. All other clients I use work fine.

Could this be related?

**Comment by chkr1011** [comment]
Do you get an exception in the MQTTnet trace? If so, it might be related.

**Comment by simonthum** [comment]
I have to check. Does trace refer to something like https://github.com/dotnet/MQTTnet/blob/master/Samples/Diagnostics/Logger_Samples.cs?
