### ISSUE TITLE
Bug with PUBREL, QOS2 and EMQX?

### ISSUE THREAD

**Issue by chrispi68** [dotnet/MQTTnet#1594]
My application runs without problems with Mosquitto as MQTT server. However, after switching to EMQX, there are numerous disconnects when I send QOS2 messages.

With help from the EMQX-GitHub forum we could find out that probably no PUBREL is sent from the client and therefore the queue from the EMQX server is running full.

https://github.com/emqx/emqx/issues/9427

When using MQTT protocol V5, the disconnection occurs very frequently (every few seconds), when using V311 it occurs less frequently (every few minutes).

I have also tested HiveMQ and the problem occurs here as well. Only with Mosquitto the client runs stable without disconnections. Is the problem known and is there a solution?

**Comment by chkr1011** [comment]
This issue is not known. Please share the trace from the library. Then we can see if PUBREL packets are not sent properly (see Samples for enabling the trace). 

You can also try to use MQTTnetApp (https://github.com/chkr1011/MQTTnetApp) and enable the packet inspection. It will also show if PUBREL packets are sent or not.

Do you probably use several features from MQTTv5 like user properties etc?

**Comment by chrispi68** [comment]
> Do you probably use several features from MQTTv5 like user properties etc?

No, I use a simple connection, nothing special:

var options = new MqttClientOptionsBuilder()
                .WithTcpServer(_ipAddress.ToString(), 1883)
                .WithKeepAlivePeriod(TimeSpan.FromSeconds(30)).WithMaximumPacketSize(uint.MaxValue)
                .WithCleanSession()
                .WithClientId("HCSCore") 
                .Build();

The only specialty might be that I publish all messages with QOS2 and that there are approx. 3 messages per second.

I will try to share the trace.

**Comment by chrispi68** [comment]
I tried the Logger-Example but there is no useful information about PUBREL.

I also tried the InspectPackage-Event but this caused permanent disconnects even with Mosquito. 

Sorry, I am not able to share any trace log.

**Comment by chkr1011** [comment]
What does "no useful information about PUBREL." mean? Was it properly transmitted then and showed up?

**Comment by chrispi68** [comment]
> What does "no useful information about PUBREL." mean? Was it properly transmitted then and showed up?

There was no information about PUBREL in the logs, only about messages size, QOS, etc.

**Comment by logicaloud** [comment]
I have tried against the containerized EMQX broker. It comes with a dashboard and in the dashboard, under 'Monitor', I can see the PUBREL count going up. Can you see anything wrong in the EMQX dashboard?

![image](https://user-images.githubusercontent.com/47704763/204400720-6db3d406-4b79-4d6f-8a4e-ab3d1820dc0a.png)

**Comment by chrispi68** [comment]
From my point of view this looks ok:

<img width="384" alt="Bildschirm­foto 2022-11-29 um 16 40 31" src="https://user-images.githubusercontent.com/33786075/204575143-6ada89c9-f65d-49c0-8369-2c1790fa419d.png">

**Comment by logicaloud** [comment]
If the number of PUBREL received goes up at the expected rate then that parts seems to be fine.

If you can provide a minimal client code sample that produces the issue on your EMQX then I can try that against my installation and see what else I can find.

**Comment by chkr1011** [comment]
@chrispi68 You can set the QoS level in MQTTnet app by clicking on the "Properties" tab. You can also try to connect with MQTTnetApp and stay connected for a while. If the connection gets dropped, you may get details in the DISCONNECT packet which is shown in the footer of the app.

**Comment by chrispi68** [comment]
I switched to the managed client an now there problems are gone.
