### ISSUE TITLE
[MqttServer] Subscription to similar base and subtopic with wildcards fails

### ISSUE THREAD

**Issue by grobmiller** [dotnet/MQTTnet#1612]
We encountered a bug which was not present in earlier major versions of MQTTnet, but we met it since we had a major upgrade to 4.1.2.350. Same applies for the newest version 4.1.2.436

We start an MQTTnet server. Then a client. We add a subscription to these to topics:

house/+/room
house/+/room/+

Then we send messages with these two topics:

house/1/room
house/1/room/bed

**We would expect to receive both messages, but only the first one arrives**. When testing this with other servers (older MQTTnet server or Moquitto) both messages arrive. 

As you can see in the sample code below, we also made some slight variations (# instead of +), but no success. When we only use one subscription (#) everything is fine again. Replacing the mid-level wildcard with a concrete house id (1) also makes it work again.

It is not an ultra-critical bug, since there is a workaround. But we lost data in production since we did not realize this problem immediately. Might be that some others may stumble over this, too.
 
```csharp
using System;
using System.Threading;
using System.Threading.Tasks;
using MQTTnet;
using MQTTnet.Client;
using MQTTnet.Server;

namespace MqttServerTest
{
	class Program
	{
		static void Main(string[] args)
		{
			Task.Run(StartMqttServer).Wait();

			var client = Task.Run(StartClient).Result;

			client.SubscribeAsync("house/+/room");
			client.SubscribeAsync("house/+/room/+");

			//You can try these two subscriptions instead, but this will also fail
			//client.SubscribeAsync("house/+/room");
			//client.SubscribeAsync("house/+/room/#");

			//This works
			//client.SubscribeAsync("house/1/room");
			//client.SubscribeAsync("house/1/room/+");

			//This works, too
			//client.SubscribeAsync("house/1/room/#");

			Publish(client, "house/1/room");
			Publish(client, "house/1/room/bed");

			//Result with first two examples: Only first message will be shown

			Console.ReadLine();
		}

		static async Task<MqttServer> StartMqttServer()
		{
			var mqttFactory = new MqttFactory();
			
			var mqttServerOptions = 
				mqttFactory
					.CreateServerOptionsBuilder()
					.WithDefaultEndpoint()
					.Build();
			var server = mqttFactory.CreateMqttServer(mqttServerOptions);
			await server.StartAsync();
			return server;
		}
		
		static async Task<IMqttClient> StartClient()
		{
			var mqttFactory = new MqttFactory();

			var mqttClientOptions =
				mqttFactory
					.CreateClientOptionsBuilder()
					.WithTcpServer("localhost")
					.WithClientId("test")
					.Build();

			var client = mqttFactory.CreateMqttClient();

			client.ApplicationMessageReceivedAsync += args =>
			{
				Console.WriteLine(args.ApplicationMessage.Topic);
				return Task.CompletedTask;
			};

			await client.ConnectAsync(mqttClientOptions, CancellationToken.None);
			
			return client;
		}
		
		private static Task<MqttClientPublishResult> Publish(IMqttClient client, string topic)
		{
			return client.PublishAsync(new MqttApplicationMessage
			{
				Topic = topic,
				Payload = new byte[] { 1, 2, 3, 4 }
			});
		}
	}
}
```

**Comment by logicaloud** [comment]
That indeed looks to be a bug. @chkr1011 I think this one is for me; I'll be looking into it if you like.

**Comment by chkr1011** [comment]
@logicaloud Yes please have look. I will also have a look tomorrow or so. We can then join with our findings.

**Comment by chkr1011** [comment]
@logicaloud Please us the branch created for this ticket.

**Comment by logicaloud** [comment]
@chkr1011 Will do. I have found the issue and will add a pull request into the branch soon. @grobmiller, thanks for reporting this.

**Comment by grobmiller** [comment]
You're welcome, thanx for your great effort and product!
