### ISSUE TITLE
.NET Framework Compatibility

### ISSUE THREAD

**Issue by luistope** [dotnet/MQTTnet#1633]
The library description says: "It is compatible with mostly any supported .NET Framework version and CPU architecture."

Installing from NuGet manager I get the error: 
"Could not install package 'MQTTnet.Extensions.ManagedClient 4.0.0.167'. You are trying to install this package in a project that has '.NETFramework,Version=v4.0' as its target, but the package does not contain assembly references or content files compatible with that framework. For more information, contact the package author."

I am compiling to .net framework 4.0 because there are Windows XP 32-bit machines as target. 

Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error		No se pudo instalar el paquete 'MQTTnet.Extensions.ManagedClient 4.0.0.167'. Está intentando instalar este paquete en un proyecto que tiene '.NETFramework,Version=v4.0' como destino, pero el paquete no contiene referencias de ensamblado o archivos de contenido compatibles con dicho marco. Para obtener más información, póngase en contacto con el autor del paquete.				

I want to use only mqtt client.

**Comment by Jeanot-Zubler** [comment]
Well, it says *supported* .NET version. .NET Framework 4.0 has been out of support for 6 years now. The earliest still supported version of .NET Framework is 4.6.2. See https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

Windows XP has also been out of support for a *long* time. There is probably not much that you can do.

**Comment by SeppPenner** [comment]
It should be compatible with netstandard1.3 though (Check the library project files)...

**Comment by chkr1011** [comment]
@luistope @Jeanot-Zubler is partially right. We support .NET 4.5.2+ (even if 4.5.2 is no longer supported). The only framework which is older and not supported is 3.5 (which is supported until 2029).

**Comment by Jeanot-Zubler** [comment]
> It should be compatible with netstandard1.3 though (Check the library project files)...

@SeppPenner Also no luck, as .NET Framework 4.0 did not support .NET Standard.
