### ISSUE TITLE
MQTT over WebSocket: Error while authenticating. The operation has timed out.

### ISSUE THREAD

**Issue by SyncroSam** [dotnet/MQTTnet#1658]
### Describe the bug
I've [forked](https://github.com/slombardo/aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4) the example given in README.md and have updated the project to the latest version of MQTTnet. I also added another authentication method using certificates.  I can confirm that certificate authentication works well, but when attempting MQTT over WebSocket, I receive the following exception;

> Error while authenticating. The operation has timed out.

I've also verified that the code I've forked compiles the sigv4 URL properly based on the [AWS documentation](https://docs.aws.amazon.com/general/latest/gr/signing-aws-api-requests.html) and it really seems to be fine.

### Which component is your bug related to?
- Client

### To Reproduce
1. Clone this [fork](https://github.com/slombardo/aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4)
2. Load and run the solution `Dotnet win app\awsiotmqttoverwebsocketswinapp\awsiotmqttoverwebsocketswinapp.sln`.
3. Enter the AWS IoT Endpoint, Access Key, Secret Key, and the Region and hit the Connect button.
4. Either examine the log file as indicated in the App.config or put a breakpoint in `AwsIotPresenter.cs:154` to see the error message.

### Additional context / logging
After reading up on some of the AWS documentation, there have been a few different things that I have tried as you may see from the repo:

- removing the scheme `wss://` from `.WithWebSocketServer(signedRequestUrl)`
- using `var factory = new MqttFactory().UseWebSocket4Net();`
- adding `.WithClientId("mqttnet-ID")`
- adding `.WithTls()`
- adding 
```
.WithTls(new MqttClientOptionsBuilderTlsParameters
{
    SslProtocol = System.Security.Authentication.SslProtocols.Tls12,
    UseTls = true,
};
```

**Comment by logicaloud** [comment]
Is the result any different when using the `WebSocket4Net` extension?

```
var mqttFactory = new MqttFactory();
mqttFactory.UseWebSocket4Net();
```

**Comment by logicaloud** [comment]
The `ComputeSignature` method seems to add a `Host` header and includes that in the signature by default. Can you try adding the `Host` header to the MQTTnet WebSocket? I.e.,

```
var webSocketParams = new MqttClientOptionsBuilderWebSocketParameters();
webSocketParams.RequestHeaders = new Dictionary<string, string>();
webSocketParams.RequestHeaders.Add("Host", cloudConnectionConfig.Host);

mqttClientOptions = new MqttClientOptionsBuilder()
    .WithWebSocketServer(signedRequestUrl, webSocketParams)
    . . . 
```

Does that make any difference?

**Comment by chkr1011** [comment]
I assume this is done.
