### ISSUE TITLE
Return one retained message

### ISSUE THREAD

**Issue by michael-eckhart-woellkart** [dotnet/MQTTnet#1659]
### Describe the feature request
Return one retained message

### Which project is your feature request related to?
- Server

### Describe the solution you'd like
Implement new method which only return one method

**Comment by michael-eckhart-woellkart** [comment]
This would be done by:

#### MQTTnet\Server\Internal\MqttRetainedMessagesManager.cs
```
        public Task<MqttApplicationMessage> GetMessage(string topic)
        {
            lock (_messages)
            {
                if (!_messages.TryGetValue(topic, out var message))
                {
                    return Task.FromResult(message);
                }
                else
                {
                    return null;
                }
            }
        }
```

#### MQTTnet\Server\MqttServer.cs
```
        public Task<MqttApplicationMessage> GetRetainedMessageAsync(string topic)
        {
            ThrowIfNotStarted();
            return _retainedMessagesManager.GetMessage(topic);
        }
```

**Comment by chkr1011** [comment]
So you basically need an API which lets you get exactly one retained message instead of all?

**Comment by michael-eckhart-woellkart** [comment]
> So you basically need an API which lets you get exactly one retained message instead of all?

Correct :)

**Comment by chkr1011** [comment]
Please try the code from the branch attached to this ticket or try build _653_ from the myget feed. If the code works please let me know. I will then merge the feature.

**Comment by michael-eckhart-woellkart** [comment]
Work for me.
