### ISSUE TITLE
MQTTnet Downloaded Code Causes Error Just Opening MQTTnet.sln in VS 2019 or VS2022

### ISSUE THREAD

**Issue by MaxFun** [dotnet/MQTTnet#1662]
Downloaded MQTTnet-master.zip, extracted to C:\Users\MySelf\source\repos\MQTTnet-master 

Opened MQTTnet.sln with VS2019  produced 8 errors. The following is first error
 
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0.	MQTTnet	C:\Program Files\dotnet\sdk\6.0.113\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	144	

Opened MQTTnet.sln with VS2022  produced 8 errors. The following is first error

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not imported by "C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets" at (37,3), due to the file not existing.	MQTTnet.Extensions.WebSocket4Net	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.CSharp.targets	37

What version of VS was used to open  MQTTnet.sln with no errors?

**Comment by chkr1011** [comment]
I can build  the entire solution perfectly using Visual Studio 2022. Please make sure that the **.NET 7.0 SDK** is installed.

**Comment by MaxFun** [comment]
I downloaded the latest version of .NET SDK and installed it

C:\Users\MySelf\source\repos\MQTTnet-master - Subset>dotnet --info
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.113 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

Still getting errors, 3 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not imported by "C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets" at (37,3), due to the file not existing.	MQTTnet	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.CSharp.targets	37	

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4057	The target "CollectUpToDateCheckBuiltDesignTime" does not exist in the project.	MQTTnet	C:\Users\MySelf\source\repos\MQTTnet-master - Subset\Source\MQTTnet\MQTTnet.csproj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error		SourceRoot items must include at least one top-level (not nested) item when DeterministicSourcePaths is true	MQTTnet	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.Managed.Core.targets	236	

What am I missing?

**Comment by MaxFun** [comment]
My error, I opened a copy of MQTTNet that I tried to fix yesterday.

Opening original download of  MQTTNet cause 7 errors, first one

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not imported by "C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets" at (37,3), due to the file not existing.	MQTTnet	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.CSharp.targets	37

**Comment by MaxFun** [comment]
No "WindowsXaml" folder in my "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft"
