### ISSUE TITLE
"The Library" Not Located

### ISSUE THREAD

**Issue by MaxFun** [dotnet/MQTTnet#1664]
On webpage https://github.com/dotnet/MQTTnet/wiki/Server-and-client-method-documentation for Server and client method documentation, the statement "The methods are now documented in the library" where is the "the library" located?
Did not find "library" in the downloaded MQTTnet. 

With the MqttClient.cs being over 1000 lines of code, is there some kind of roadmap or flow diagram?

**Comment by chkr1011** [comment]
"The library" is the actual code. We added a lot of summary comments to that method and property will now show the required information.

There is no flow diagram or roadmap. If you need more information about the MQTT protocol itself please see the official RFC.
