### ISSUE TITLE
I can build  the entire solution perfectly using Visual Studio 2022. Please make sure that the **.NET 7.0 SDK** is installed.

### ISSUE THREAD

**Issue by MaxFun** [dotnet/MQTTnet#1665]
I can build  the entire solution perfectly using Visual Studio 2022. Please make sure that the **.NET 7.0 SDK** is installed.

_Originally posted by @chkr1011 in https://github.com/dotnet/MQTTnet/issues/1662#issuecomment-1407384459_

**Comment by MaxFun** [comment]
Using VS 2022

Microsoft Visual Studio Community 2022
Version 17.4.4
VisualStudio.17.Release/17.4.4+33213.308
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA668
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

C# Tools   4.4.0-6.22608.27+af1e46ad38d900023f8b1a2839484e471ece1502
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.4.0-6.22608.27+af1e46ad38d900023f8b1a2839484e471ece1502
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio File Histories   VSHistory
Maintains the history of all files saved in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

With .NET SDK

C:\Users\MySelf\source\repos\MQTTnet-master - Subset>dotnet --info
.NET SDK:
Version: 7.0.102
Commit: 4bbdd14480

Runtime Environment:
OS Name: Windows
OS Version: 10.0.19045
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\7.0.102\

Host:
Version: 7.0.2
Architecture: x64
Commit: d037e070eb

.NET SDKs installed:
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.526 [C:\Program Files\dotnet\sdk]
3.0.101 [C:\Program Files\dotnet\sdk]
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.104 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
5.0.416 [C:\Program Files\dotnet\sdk]
6.0.113 [C:\Program Files\dotnet\sdk]
7.0.102 [C:\Program Files\dotnet\sdk]

Opening MQTTnet cause 8 errors

The first one being 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not imported by "C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets" at (37,3), due to the file not existing.	MQTTnet.Extensions.Rpc	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\WindowsXaml\v17.0\Microsoft.Windows.UI.Xaml.CSharp.targets	37	

The error indicates it is trying to look into a folder that is not in my VS 2022 x64
No "WindowsXaml" folder in my "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft"

Does the x64 version of VS 2022 support the needs of MQTTnet?

**Comment by chkr1011** [comment]
Please try adding the windows desktop workload including UWP in the studio installer.

**Comment by MaxFun** [comment]
Thanks, adding UWP in the studio installer solved the problems, no more errors.

It would be nice if a note were add to the MQTTnet webpage (https://github.com/dotnet/MQTTnet) for all prerequisites for VS such as Universal Windows Platform development workload. 

Again Thanks

**Comment by chkr1011** [comment]
It is very strange that this is actually required. I assumed that all UWP imports are made optional in the project files. 

I will check these again.

**Comment by MaxFun** [comment]
Tried to build the Server_Simple_Samples.cs, to run it but got 4 errors, first one

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'Type' does not contain a definition for 'IsAssignableFrom' and no accessible extension method 'IsAssignableFrom' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	MQTTnet (netstandard1.3)	C:\Users\MySelf\source\repos\MQTTnet-master\Source\MQTTnet\Internal\AsyncQueue.cs	41	Active

Is there a project for each sample or how to export one of the sample that will build.

**Comment by chkr1011** [comment]
The samples are designed to work with .net 6 +. They use several language features. I will remove other targets from the project.

**Comment by chkr1011** [comment]
The samples will not work with netstandard1.3. I updated the Wiki with the UWP information.

**Comment by ethankershaw** [comment]
I fought with compilation issues for a while and eventually the note about installing the UWP workload, and a specific version of the Windows 10 SDK (https://github.com/dotnet/MQTTnet/issues/1770#issuecomment-1606422913) solved it for me.
