### ISSUE TITLE
UT: How to raise an event when I use Moq

### ISSUE THREAD

**Issue by ArthurChang01** [dotnet/MQTTnet#1673]
My unit test code segment is below:
```
_client.Setup(o => o.StartAsync(It.IsAny<ManagedMqttClientOptions>()))
                .Callback(() => _client.Raise(o => o.ConnectedAsync += null, 
                    new MqttClientConnectedEventArgs(new MqttClientConnectResult())));
```
After I press the Test button, then I get the error:
System.Reflection.TargetParameterCountException : Parameter count mismatch.

please help me, thanks.

**Comment by chkr1011** [comment]
I don't know how Moq works but the event args are only one parameter of event args type and the expected result is a Task.
