### ISSUE TITLE
Misleading signature of MqttClient.ConnectAsync, MqttClientConnectResultCode expected but throws exception

### ISSUE THREAD

**Issue by jschweda** [dotnet/MQTTnet#1681]
### Describe the bug
[ConnectAsync](https://github.com/dotnet/MQTTnet/blob/master/Source/MQTTnet/Client/MqttClient.cs#L100) returns an MqttClientConnectResult which holds an MqttClientConnectResultCode. [MqttClientConnectResultCode](https://github.com/dotnet/MQTTnet/blob/master/Source/MQTTnet/Client/Connecting/MqttClientConnectResultCode.cs) can indicate all kinds of errors while establishing a connection. But different than expected an exception is thrown. 

### Which component is your bug related to?
- Client

### To Reproduce
1. Using Version 4.1.4.563 of MQTTnet
2. Run this server code
```
 var factory = new MqttFactory();
        var serverOptions = factory.CreateServerOptionsBuilder().WithDefaultEndpoint();
        _mqttServer = factory.CreateMqttServer(serverOptions.Build());
        _mqttServer.ValidatingConnectionAsync += (e) => {
            e.ReasonCode = MQTTnet.Protocol.MqttConnectReasonCode.BadUserNameOrPassword;
            return Task.CompletedTask;
        };
        _mqttServer.StartAsync().GetAwaiter().GetResult();
```
4. Run this client code
```
            _mqttClient = _mqttFactory.CreateMqttClient();
            var mqttClientOptions = _optionsBuilderFactory.CreateClientOptionsBuilder().WithProtocolVersion(MqttProtocolVersion.V500);

            // throws unexpected exception
            MqttClientConnectResult result = await _mqttClient.ConnectAsync(mqttClientOptions, ct).ConfigureAwait(false);
            if (result.ResultCode != MqttClientConnectResultCode.Success)
            {
                _logErrorCannotConnect(_logger, result.ReasonString ?? "Unknown", result.ResultCode, null);
                return result;
            }
```
6. ConnectAsync is not expected to throw an exception based on signature.

### Expected behavior
ConnectAsync should return a MqttClientConnectResult that has the ResultCode set to a value indicating non success.

**Comment by chkr1011** [comment]
I added a new option to the client options so that you can choose. Otherwise it would introduce breaking changes.
