### ISSUE TITLE
Specifying a port causes 

### ISSUE THREAD

**Issue by gbanuk2** [dotnet/MQTTnet#1683]
### Describe the bug
When specifying a port number, I receive an error when calling ConnectAsync(). If I remove the port number, MQTTnet connects fine and I can communicate with the server normally. The port number is correct because other systems are connecting with it. The problem happens on both NET4.8 and NET6.0 targets. 

Error from ConnectAsync(): 
Received packet 'PubAck: [PacketIdentifier=21584] [ReasonCode=Success]' at an unexpected time.

### Which component is your bug related to?
- Client

### To Reproduce
1. Using this version of MQTTnet: 4.1.4.563
2. Run this code below. The commented out "WithTcpServer" line works fine. The line above it causes a failure.
```
MqttClientOptions mqttClientOptions = new MqttClientOptionsBuilder()
                .WithTcpServer(serverName, 9001)
                //.WithTcpServer(serverName)
                .WithCredentials(username, password)
                .Build();

            //Connect synchronously with a timeout.
            using (CancellationTokenSource timeoutToken = new CancellationTokenSource(TimeSpan.FromSeconds(3)))
            {
                _mqttClient.ConnectAsync(mqttClientOptions, timeoutToken.Token)
                    .Wait();
            }
```

**Comment by chkr1011** [comment]
O am wondering why both ports lead to a working connection in terms of a TCP connection. If you get "Received packet 'PubAck: " with the port 9001 it means that there is a MQTT broker behind that point. But when avoiding the port the code will default to 1883. If this works as you mentioned it means that there are two brokers available or one via two different ports?

**Comment by chkr1011** [comment]
If you have an encrypted endpoint at 9001 you need to enable TLS via using the "WithTls()" method of the client options builder.

**Comment by chkr1011** [comment]
I assume this ticket is done. If the error persists please reopen the ticket.
