### ISSUE TITLE
Q: Why has IMqttFactory been removed?

### ISSUE THREAD

**Issue by d5UtQvp8QQU9** [dotnet/MQTTnet#1686]
### Describe the feature request
Why has the interface IMqttFactory been removed with MQTTnet 4.0.0 (https://github.com/dotnet/MQTTnet/commit/2ce9b94ec9a104a629851eb4766bece4a6143098) ?
I use MqttFactory in dependency injection, not being able to replace it with a mock makes testing much harder than it needs to be.

### Which project is your feature request related to?
- Generic

### Describe the solution you'd like
Bring back IMqttFactory?

### Describe alternatives you've considered
Not using MqttFactory in DI?
Maybe I am using MQTTnet wrong? Any hints are welcome.

**Comment by Jeanot-Zubler** [comment]
The [Upgrading Guide in the Wiki](https://github.com/dotnet/MQTTnet/wiki/Upgrading-guide#from-3x-to-400) mentions some missing Interfaces. If you want to use Dependency Injection, you should probably wrap the `MqttFactory` in a custom class. This class can then implement its own Interface.

On a sidenote: in my opinion the `MqttFactory` should probably not be used in many places in your code. I would probably inject a (wrapped) `MqttClient` into the classes that need one. The creation of Clients should probably be handled in a central place.

**Comment by d5UtQvp8QQU9** [comment]
Understood, thanks.
