### ISSUE TITLE
Client connection to AWS MQTT broker just disconnects randomly

### ISSUE THREAD

**Issue by martinskov** [dotnet/MQTTnet#1689]
Hi,

I'm doing a TLS connection to AWS that seems to succeed - I have configured a keep alive periode of 5 sec, but I get random disconnects.

Log shows PINGs are running as expected, but randomly the client says "Stopped sending keep alive packets".

Any ideas what could be causing it?

`
2023-03-09 22:23:01.634 [Information] ******.amazonaws.com >> [2023-03-09T21:23:01.6342407Z] [15] [MqttChannelAdapter] [Verbose]: RX (2 bytes) <<< PingResp
2023-03-09 22:23:01.634 [Information] ******.amazonaws.com >> [2023-03-09T21:23:06.7833102Z] [50] [MqttChannelAdapter] [Verbose]: TX (2 bytes) >>> PingReq
2023-03-09 22:23:01.634 [Information] ******.amazonaws.com >> [2023-03-09T21:23:06.8205427Z] [16] [MqttChannelAdapter] [Verbose]: RX (2 bytes) <<< PingResp
2023-03-09 22:23:01.634 [Information] ******.amazonaws.com >> [2023-03-09T21:23:11.9637678Z] [50] [MqttChannelAdapter] [Verbose]: TX (2 bytes) >>> PingReq
2023-03-09 22:23:01.634 [Information] ******.amazonaws.com >> [2023-03-09T21:23:12.0058598Z] [16] [MqttChannelAdapter] [Verbose]: RX (2 bytes) <<< PingResp
2023-03-09 22:23:01.634 [Information] ******.amazonaws.com >> [2023-03-09T21:23:15.4350712Z] [15] [MqttClient] [Verbose]: Stopped sending keep alive packets.
2023-03-09 22:23:01.634 [Information] ******.amazonaws.com >> [2023-03-09T21:23:15.4350712Z] [15] [MqttClient] [Verbose]: Disconnecting [Timeout=00:01:40]
2023-03-09 22:23:01.634 [Information] ******.amazonaws.com >> [2023-03-09T21:23:15.4400714Z] [15] [MqttClient] [Verbose]: Disconnected from adapter.
`

**Comment by stefxx** [comment]
It is really random? Or every 100 seconds? I see a timeout of 00:01:40.

Are you using WebSocket?

**Comment by martinskov** [comment]
@stefxx I was also wondering where the 00:01:40 was coming from...

The "random-ness" is shown by running sometimes 2 ping/ping_response before a disconnect, an other times it can ping/pong 20-30 times.
The disconnect timeout message is always 00:01:40.

Connection is done using "WithTcpServer" - so  it should be a tcp connection and not ws.

**Comment by logicaloud** [comment]
My version may be slightly older than the current one, but TCP connections remain stable for me on .NET 6, with TLS connection to port 8883 and client certificate. 

Could you share your client configuration code?

**Comment by martinskov** [comment]
@logicaloud OK - sounds promising - below is the configuration of the client. I have tried different settigns for the 'WithKeepAlivePeriod' but still the same issue.
Randomly it says : "stopped sending keep alive packets"

`
                    var tlsParameters = new MqttClientOptionsBuilderTlsParameters
                    {
                        UseTls = true,
                        Certificates = new[] { clientCertificate },
                        IgnoreCertificateRevocationErrors = true, //Prevent online revocation check
                        IgnoreCertificateChainErrors = false,
                        AllowUntrustedCertificates = false,
                    };

                    OptionBuilder = OptionBuilder.WithClientId(clientID)
                                    .WithTcpServer(broker, brokerPort)
                                    .WithCleanSession()
                                    .WithTls(tlsParameters)
                                    .WithKeepAlivePeriod(new TimeSpan(0, 0, 5));`

**Comment by logicaloud** [comment]
Looks OK to me. On my side, I have added a timeout (`WithTimeout(TimeSpan.FromSeconds(15)`) but omitting that should not be a problem.

If you can provide a minimal program that produces the error then I can try that against my AWS IoT thing.

**Comment by martinskov** [comment]
OK - got a bit further, was able to compile and debug the library - it seems connection is being stopped due to 0-byte received.,
Any ideas why - Firewall issue, connection drop? - it seems to act up against AWS MQTT, but not local broker.

![image](https://user-images.githubusercontent.com/111112672/227225191-51839f22-6e20-432e-b0c2-4c732a353790.png)

**Comment by logicaloud** [comment]
Tried the latest version publishing a few messages to AWS and it works for me. If you can provide a minimal program that produces the error then I can have another look.

**Comment by martinskov** [comment]
@logicaloud  will try to do a mockup - I'm not publising anything, I just let i stay connected with keepalive running in the background

**Comment by martinskov** [comment]
OK, so here is an update - I have just switched around and connected with a different set of clientID and certificate, and it seem to run stable - will continue testing/monitoring...... hmmm...

**Comment by chkr1011** [comment]
0 bytes read usually indicating a clean TCP disconnect  (graceful disconnect). To you have some trace of the library for us? It should contain more details about what is happening internally. Details for enabling the trace are part of the samples.

**Comment by martinskov** [comment]
Hi,
it seems like I have narrowed it down to the fact, that it is connected to the ClientID - so I'm closing ing this issue.
Sorry for the inconveinience and thanks for your assitance - have a nice day.
