### ISSUE TITLE
MQTTNet can't connect on version 4

### ISSUE THREAD

**Issue by VentsislavDinev** [dotnet/MQTTnet#1693]
Hello, 
I try to connect with secure and unsecure broker on localhost, when I run my app we can't connect to Local MQTT. 

This is my configuration. 
We want to have Keepalive and clean session. 

public async Task Send_Responses()
        {
            var source = new CancellationTokenSource();
            var token = source.Token;

            var mqttFactory = new MqttFactory();

            using (var mqttClient = mqttFactory.CreateMqttClient())
            {
               
                var mqttClientOptions = new MqttClientOptionsBuilder()
                    .WithClientId(Guid.NewGuid().ToString())
                    .WithTcpServer("localhost", port: 1885)
                    .WithCleanSession()
                    .WithKeepAlivePeriod(TimeSpan.FromSeconds(60))
                    .Build();

                
                mqttClient.ConnectAsync(mqttClientOptions, token).Wait(token);

                // publish message 
                    var payload = Encoding.ASCII.GetBytes("Hello");
                var message = new MqttApplicationMessage
                {
                    Topic = "hello",
                    Payload = payload,
                    QualityOfServiceLevel = MqttQualityOfServiceLevel.AtLeastOnce,
                    ContentType = "application/json"
                };

               mqttClient.PublishAsync(message, token).Wait(token);
            }
        }
I can't find whre is my bug. 
Please help. 

When i change: 
  var mqttClientOptions = new MqttClientOptionsBuilder()
                .WithClientId(Guid.NewGuid().ToString())
                .WithTcpServer("localhost", port: 1885)
                .WithCleanSession()
                .WithKeepAlivePeriod(TimeSpan.FromSeconds(60))
                .Build(); 
to 
  var mqttClientOptions = new MqttClientOptionsBuilder()
                .WithTcpServer("localhost", port: 1885)
                .Build(); 

One or more errors occurred. (Error while authenticating. The operation has timed out.)'

**Comment by logicaloud** [comment]
The default port TCP/IP port would be 1883 (not 1885). Is the broker configured to use 1885?

**Comment by VentsislavDinev** [comment]
@logicaloud  Yes, the broker is configure to use 1885. 
Now I test the TestApp from this repo and can't find the bug with this configuration... :D

**Comment by chkr1011** [comment]
If you get a task cancelled exception please try your code with proper _async/await_ instead of .Wait() calls. Probably there is a deadlock internally.

**Comment by chkr1011** [comment]
I assume this issue is solved.
