### ISSUE TITLE
Example for net6.0

### ISSUE THREAD

**Issue by antt0481** [dotnet/MQTTnet#1699]
Do you have any config for net6.0 in Program.cs

First I try with 
builder.Services.AddHostedMqttServer(mqttServer => mqttServer.WithDefaultEndpointPort(1883))
    .AddMqttConnectionHandler()
    .AddConnections()
    .AddMqttTcpServerAdapter();

....

app.UseEndpoints(endpoints =>
{
    endpoints.MapMqtt("/mqtt");
    endpoints.MapControllers();
});
var mqttController = new MqttController();
app.UseMqttServer(server =>
{
    server.ClientConnectedAsync += mqttController.OnClientConnected;
});

check on mqttbox, couldn't connect
check telnet localhost 1883 => no too

**Comment by chkr1011** [comment]
Please see this sample: https://github.com/dotnet/MQTTnet/blob/master/Samples/Server/Server_ASP_NET_Samples.cs
