### ISSUE TITLE
UNO android app not receiving mqttclient subscribed topic

### ISSUE THREAD

**Issue by LiftTrack** [dotnet/MQTTnet#1708]
Hi,

I am using MQTTnet in my Android app. I have created an Android application on the UNO platform. The application is working fine in debug mode but when I publish my app and run it on my mobile phone, I am unable to **receive subscribed topic** after installing the "APK" file on my mobile phone. Unable to find out the cause behind it.

Steps:-
1. I am connected with "**test.mosquitto.org**".I am able to receive messages when I published anything under a particular topic.
2. In release mode or by installing the published "**APK**" file on my mobile phone, the app is not receiving published messages from "**test.mosquitto.org**".

Please provide me with a solution to it. Why my app is not receiving published messages in release mode?

Attaching a video for help.

https://user-images.githubusercontent.com/119324311/230410245-7615468b-88b6-473d-9654-d2860e41fb06.mp4

https://user-images.githubusercontent.com/119324311/230410280-39ffd412-1d40-4e19-b042-9b9ba1ef4c91.mp4

**Comment by chkr1011** [comment]
Without some code snippets you used I am afraid that we cannot help much.

**Comment by Jeanot-Zubler** [comment]
If everything works in debug mode, there might be some object that is garbage collected, because you forgot to keep the reference to it. something like using
```cs
mqttFactory.CreateMqttClient()
```
instead of
```cs
var client = mqttFactory.CreateMqttClient()
```

If you provide your code we might be able to help more.
