### ISSUE TITLE
How to compress the playload in Websocket MQTT?

### ISSUE THREAD

**Issue by liuyanan199205** [dotnet/MQTTnet#1717]
### Describe your question
The code shown in the following figure wants to add the Sec-WebSocket-Extensions request header, but the MQTT connection fails, does this library not support this use?
![1](https://user-images.githubusercontent.com/52774355/235035625-701e8804-2500-4aca-ab60-0c5023bb7be5.png)

**Comment by chkr1011** [comment]
We only make use of the WebSocketClient which is part of the .NET Framework. I assume that this client does not support this feature.
You may need to create a ticket at the dotnet team instead.
