### ISSUE TITLE
Mqtt server memory leak version 4.2.0.706 

### ISSUE THREAD

**Issue by Mahersrasra** [dotnet/MQTTnet#1722]
I upgraded the mqttnet version to the latest one (4.2.0.706) but the same issue persists excessive memory consumption and a very long time taken by the server to dispose its objects and return to his first state.
there are any actions that can be taken to improve memory consumption performance in general ?

_Originally posted by @Mahersrasra in https://github.com/dotnet/MQTTnet/issues/1719#issuecomment-1533638008_

**Comment by SeppPenner** [comment]
Duplicates  https://github.com/dotnet/MQTTnet/issues/1719.
