### ISSUE TITLE
NullReferenceException on MqttClient.ConnectAsync

### ISSUE THREAD

**Issue by PSanetra** [dotnet/MQTTnet#1724]
Somehow I get the following NullReferenceException on a `MqttClient.ConnectAsync` call. The issue is only happening in our CICD pipeline, so it is hard to debug. This is the output from the `InnerException` of the actually thrown `MqttConnectingFailedException`.

```csharp
   System.NullReferenceException: Object reference not set to an instance of an object.
   at MQTTnet.Client.MqttClient.AuthenticateAsync(MqttClientOptions options, CancellationToken cancellationToken)
```

Library version: MQTTnet 4.2.0.706

**Comment by chkr1011** [comment]
If this is running in your CI I assume that you are performing tests etc? Or why you execute code with MQTTnet in the CI? 
I checked the code of the _AuthenticateAsync_ method and the only thing I could imagine is that the adapter is null. Do you use a custom transport adapter etc.?

Are you able to test with a nuget from the MyGet feed? Then we can add some logging and see which part is actually null.

**Comment by PSanetra** [comment]
@chkr1011 yes we execute some tests in the CI. I have never used MyGet feed, but I think it should be possible.

**Comment by PSanetra** [comment]
My current guess is that this is some symptom of a race condition with a concurrent call to `MqttClient.Cleanup()`:

https://github.com/dotnet/MQTTnet/blob/99f4f46062611cd08e18b82515962b69e8c619e4/Source/MQTTnet/Client/MqttClient.cs#L473

**Comment by SeppPenner** [comment]
What about using `<Nullable>enable</Nullable>` in the project files? This would check if nullable errors occur: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types

**Comment by chkr1011** [comment]
I tried but since we have old frameworks we are supporting it did not work.

In my opinion this will not help here because it is a race condition and the affected field will be marked as nullable in this case.

**Comment by SeppPenner** [comment]
> I tried but since we have old frameworks we are supporting it did not work.

Ah, I see.

> In my opinion this will not help here because it is a race condition and the affected field will be marked as nullable in this case.

This was more or less a general idea for the project, not only specific for the issue here.

**Comment by chkr1011** [comment]
@PSanetra Please try **exactly** build **4.2.1.753** from the MyGet feed. It contains some improvements.

**Comment by PSanetra** [comment]
@chkr1011 at the moment I can not reproduce the issue anymore. I will try that build when it happens again. The root cause is probably related to our CI.
