### ISSUE TITLE
Any idea about mqtt

### ISSUE THREAD

**Issue by issingle** [dotnet/MQTTnet#1727]
### Describe the feature request
websocket-sharp is a lightweight websocket lib. Asp.net5.0 or greater is too heavy。

### Which project is your feature request related to?

- Server

**Comment by chkr1011** [comment]
The library you mentioned is 7 years old and has no final release yet (https://www.nuget.org/packages/WebSocketSharp).
ASP.NET also provides much more features in terms of authentication etc.
