### ISSUE TITLE
How do I receive a message from the server?

### ISSUE THREAD

**Issue by Ridyu** [dotnet/MQTTnet#1735]
### Which project is your question related to?
- Client
- ManagedClient
- Server

How do I receive a message from the server?

Sending messages to the server works fine. But i can't get messages from the server.
I'm using the latest version of MQTTnet.

I'm learning how to use it from the example on github.
It has been confirmed that [Application Message ReceivedAsync] is used for the latest version.
However, no matter how many times I try, it doesn't work.

>>>>>>>>>>>  I'd appreciate it if you could tell me how.

To sum up a few things.
1. [ ApplicationMessageReceivedAsync  ]   Is it right to use it?
2. If correct, the payload has disappeared from the [ e.ApplicationMessage.payload ].
3. So I used [ ConvertPayloadToString ]. 
4. For your information, the way to send messages to the server works. very well. Use[ payload  ] to send messages to the server.
5. However, [ payload ] is disabled for the ability to receive messages.
6. It doesn't work even if you put [ Console.WriteLine ] in it using [ ApplicationMessageReceivedAsync ]

First of all, this is my code.
 This Code is Example. Request a message From Server.
#############################################################################
private static async Task Kim_Server_Message_Receive()
      {
            var factory = new MqttFactory();
            var topic1 = "MyTopic/Test1";
            var topic2 = "MyTopic/Test2";
            var message = "Send Message?";
            var rcvTopic = string.Empty;
            var rcvMessage = string.Empty;

            using ( var client = factory.CreateMqttClient()) 
            {
                var clientOptions = new MqttClientOptionsBuilder()
                    .WithTcpServer("1831.133.1315.13513.13513.1513")                      // The server address is example
                    .WithCredentials("Test", "1234")
                    .WithProtocolVersion(MQTTnet.Formatter.MqttProtocolVersion.V500)
                    .WithClientId("Tester")
                    .Build();

                await client.ConnectAsync(clientOptions, CancellationToken.None);

                client.ApplicationMessageReceivedAsync += e =>
                {
                    rcvMessage = e.ApplicationMessage.ConvertPayloadToString();
                    rcvTopic  = e.ApplicationMessage.Topic;

                    Console.WriteLine("Receive Message : " + e.ApplicationMessage.ConvertPayloadToString());

                    return Task.CompletedTask;
                };

                await client.ReconnectAsync(CancellationToken.None);
            }
        }
#############################################################################

I'm a beginner, so I can't explain it well, but I wrote it down.
I would appreciate it if you could tell me how to receive a message from the server.
( You don't have to tell me how to send a message to the server. )

**Comment by Jeanot-Zubler** [comment]
You need to subscribe to a topic. otherwise the server will never send messages to you. Instead of `client.ReconnectAsync` call `client.SubscribeAsync`

**Comment by ebartek** [comment]
@Jeanot-Zubler, is it a way to receive callback/response for client.Publish? 
As I understand  ApplicationMessageReceivedAsync event works only with subscribing. Is that correct?

**Comment by Jeanot-Zubler** [comment]
@ebartek No. An `ApplicationMessage` in this library corresponds to a `PUBLISH` packet. Therefore the `ApplicationMessageReceivedAsync` event only gets invoked, when the server sends a `PUBLISH` packet. The server forwards these packets to any client, that is subscribed to the corresponding topic.

 `PUBACK` and `PUBREC` do not get forwarded to the `ApplicationMessageReceivedAsync` event. If you really wanted to check every packet, you can use the `InspectPacketAsync` event. Some information is also available in the return value of the `PublishAsync` method.

**Comment by chkr1011** [comment]
You can also make use of the low level client which let's you handle all the details of the MQTT protocol. But usually there is no need to. This library puts ab abstraction layer on top of the MQTT protocol.

**Comment by chkr1011** [comment]
I assume this question is answered.
