### ISSUE TITLE
Error in Wiki Code Snippet

### ISSUE THREAD

**Issue by henon** [dotnet/MQTTnet#1751]
On page https://github.com/dotnet/MQTTnet/wiki/Server

```csharp
// Start a MQTT server.
var mqttServer = new MqttFactory().CreateMqttServer();
await mqttServer.StartAsync(new MqttServerOptions());
Console.WriteLine("Press any key to exit.");
Console.ReadLine();
await mqttServer.StopAsync();
```

Has a bug or is no longer valid. It should be

```csharp
            // Start a MQTT server.
            var mqttServer = new MqttFactory().CreateMqttServer(new MqttServerOptions());
            await mqttServer.StartAsync();
            Console.WriteLine("Press any key to exit.");
            Console.ReadLine();
            await mqttServer.StopAsync();
```

The same goes for the next code snippet after that.

**Comment by SeppPenner** [comment]
The Wiki is only valid for version 3.x. It will not be updated anymore.

**Comment by SeppPenner** [comment]
Check out https://github.com/dotnet/MQTTnet/discussions/1744#discussioncomment-6024454 as well.


The wiki is not up-to-date at all and will not be updated anymore. If you check the Examples page under https://github.com/dotnet/MQTTnet/wiki/Examples --> There it's stated that only v3.x is covered in the wiki.
