### ISSUE TITLE
use stm32 paho.mqtt.c subscribe not ok

### ISSUE THREAD

**Issue by beidou566** [dotnet/MQTTnet#1759]
### Describe 
my use stm32 paho.mqtt.c client connect mqttnet srever,
paho.mqtt.c only can use v311,
but can't  subscribe success，connect ok。
I tried switching to another mqtt server，all ok.
v311 is  return different？

### in file  MqttV3PacketFormatter.cs line 80
    SubAck if  the same ConnAck??

          case MqttControlPacketType.ConnAck:
                    if (_mqttProtocolVersion == MqttProtocolVersion.V311)
                    {
                        return DecodeConnAckPacketV311(receivedMqttPacket.Body);
                    }
                    else
                    {
                        return DecodeConnAckPacket(receivedMqttPacket.Body);
                    }

                case MqttControlPacketType.SubAck:
                    return DecodeSubAckPacket(receivedMqttPacket.Body);

Seek help
thank very much

**Comment by beidou566** [comment]
https://github.com/eclipse/paho.mqtt.c/issues?page=1&q=is%3Aissue+is%3Aopen

**Comment by logicaloud** [comment]
Could you post a minimal example program that re-produces the problem? 

I don't seem to have an issue subscribing and receiving messages with the `paho-mqtt3a' library.
