### ISSUE TITLE
MqttClientOptionsBuilderTlsParameters no longer has CertificateValidationCallback 

### ISSUE THREAD

**Issue by ovidiaconescu** [dotnet/MQTTnet#1772]
Ideally the documentation should be updated for the special characters use-case as the MqttClientOptionsBuilderTlsParameters no longer has CertificateValidationCallback 

https://github.com/dotnet/MQTTnet/wiki/Client#tls-using-a-client-certificate

**Comment by Jeanot-Zubler** [comment]
At the top of the wiki page you find the following sentence

> These samples are only valid for **version 3**. Please check the **Samples directory** for samples and documentation for version 4.0+

The wiki is no longer maintained

**Comment by ovidiaconescu** [comment]
Thanks, is there a sample that uses dependency injection for v4?

**Comment by Jeanot-Zubler** [comment]
Not in the samples directory, but take a look at the [MQTT multimeter](https://github.com/chkr1011/mqttMultimeter). It's a more complex project, but it uses dependency injection.
