### ISSUE TITLE
MQTTnet.dll in nuget package not signed

### ISSUE THREAD

**Issue by maongit** [dotnet/MQTTnet#1777]
Is it deliberate that the MQTTnet.dll in MQTTnet 4.2.1.781 published on nuget  is *not* digitally signed?

Some clients are starting to reject installation of any executable or dll that is not signed. We could build and sign ourselves, but then we loose the convenience of just pulling the latest release from nuget.

Thanx in advance.

**Comment by CZEMacLeod** [comment]
It doesn't appear that the nuget package is signed either...

**Comment by chkr1011** [comment]
The assemblies do have a strong name but the nuget is indeed not signed.

**Comment by CZEMacLeod** [comment]
@chkr1011 I think @maongit is referring to a 'code signing' digital signature on the DLL, not a strong name. e.g. It isn't signed using SignTool.

**Comment by chkr1011** [comment]
I created a ticket at the .NET Foundation so that this project can get a signing certificate. 

https://github.com/dotnet-foundation/projects/issues/337

**Comment by chkr1011** [comment]
Starting with version 4.3.5.x the nuget and its DLLs are properly signed.
