### ISSUE TITLE
Extended authentication handler is not yet supported

### ISSUE THREAD

**Issue by saud-saeed** [dotnet/MQTTnet#1788]
### Describe the bug
I'm encountering an issue while attempting to connect to AWS IoT Core from my C# Web API in .NET 7.0. Interestingly, the same setup was functioning perfectly a few days ago. I'm using MQTTnet package version 4.2.1.781. The error message I'm now receiving is as follows:

MQTTnet.Adapter.MqttConnectingFailedException: 'Error while authenticating. Extended authentication handler is not yet supported'

### Which component is your bug related to?

- Client

### Expected behavior
It should successfully connect to AWS IoT MQTT broker.

### Screenshots
 
```csharp
string certPem = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Certificates/Users_Thing.cert.pem");
string keyPem = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Certificates/Users_Thing.private.key");

var pfxCert = new X509Certificate2(X509Certificate2.CreateFromPemFile(certPem, keyPem).Export(X509ContentType.Pfx));
                var factory = new MqttFactory();
                var mqttClient = factory.CreateMqttClient();
                var options = new MqttClientOptionsBuilder()
                        .WithTcpServer(IotEndpoint, BrokerPort)
                        .WithClientId(ClientId)
                        .WithCleanSession()
                        //.WithCommunicationTimeout(TimeSpan.FromSeconds(60))
                        .WithTls(new MqttClientOptionsBuilderTlsParameters
                        {
                            UseTls = true,
                            SslProtocol = System.Security.Authentication.SslProtocols.Tls12,
                            IgnoreCertificateRevocationErrors = true,
                            IgnoreCertificateChainErrors = true,
                            AllowUntrustedCertificates = true,
                            Certificates = new List<X509Certificate>
                            {
                                pfxCert
                            }
                        })
                        .Build();

                await mqttClient.ConnectAsync(options, CancellationToken.None);
```

**Comment by Temppus** [comment]
I am getting same exception. Seems related to https://github.com/dotnet/MQTTnet/issues/1139 ?

**Comment by BEagle1984** [comment]
We are facing the same issue connecting to emqx. I'm under the impression that it worked flawlessly some releases ago.
This exception is thrown quite often but it eventually connects (my [library](https://github.com/BEagle1984/silverback) retries to establish the connection).

```log
MQTTnet.Adapter.MqttConnectingFailedException: Error while authenticating. Extended authentication handler is not yet supported
 ---> System.NotSupportedException: Extended authentication handler is not yet supported
   at MQTTnet.Client.MqttClient.Authenticate(IMqttChannelAdapter channelAdapter, MqttClientOptions options, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Client.MqttClient.Authenticate(IMqttChannelAdapter channelAdapter, MqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectInternal(IMqttChannelAdapter channelAdapter, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(MqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(MqttClientOptions options, CancellationToken cancellationToken)
   at Silverback.Messaging.Broker.Mqtt.MqttClientWrapper.TryConnectClientAsync(Boolean isFirstTry, CancellationToken cancellationToken)
```

Half a second after the exception above, it successfully connected. I'm quite confident that nothing changes in the settings between the retries.

**Comment by RashiqueProgbiz** [comment]
Have you got any solution?

**Comment by saud-saeed** [comment]
Yes, this issue has been resolved now. To resolve the IoT connectivity problem, I followed these steps:

1. Create a new certificate in the AWS IoT Core console.
2. Download the certificate and key files.
3. Replace the content of the private key and certificate PEM files in the Web API project.
4. After performing these steps, the connection was successfully established, and we are now able to send and receive messages from IoT once again.

**Comment by RashiqueProgbiz** [comment]
> Yes, this issue has been resolved now. To resolve the IoT connectivity problem, I followed these steps:
> 
> 1. Create a new certificate in the AWS IoT Core console.
> 2. Download the certificate and key files.
> 3. Replace the content of the private key and certificate PEM files in the Web API project.
> 4. After performing these steps, the connection was successfully established, and we are now able to send and receive messages from IoT once again.

Thank you so much for the response. I will try the way you have suggested.
