### ISSUE TITLE
how is wild card publish is working?

### ISSUE THREAD

**Issue by Kaushik-007** [dotnet/MQTTnet#1807]
Hi All,

wanted to know how wildcard publish is handled in MqttNet

**Comment by CZEMacLeod** [comment]
@Kaushik-007 Can you explain where you are 'receiving' the notification mixed up? There is only one ApplicationMessageReceivedAsync event and it is called for all messages. If you have registered 2 handlers, you need to examine the ApplicationMessage.Topic field in each message and see if your handler is applicable.
You can check and set the IsHandled property to reduce the amount of work each handler has to do...

Something like this in a single handler would dispatch to the correct function for each generic topic...

```cs
if (e.IsHandled) return;
      string topic = e.ApplicationMessage.Topic;
      var parts = topic.Split('/',5);
      if (parts.Length >=4 && parts[0]=="DigitalLab" && parts[1]=="Devices")
      {
	switch(parts[3])
	{
		case "HeartBeat":
			await HandleHeartBeatAsync(e, parts[2]);
			break;
              case "MachineState":
			if (parts.Length == 5)
			{
				await HandleMachineStateAsync(e, parts[2], parts[4]);
			}
                  break;
          }
      }
```
```cs
private static Task HandleMachineStateAsync(MqttApplicationMessageReceivedEventArgs e, string device, string topicState) => throw new NotImplementedException();

private static Task HandleHeartBeatAsync(MqttApplicationMessageReceivedEventArgs e, string device) => throw new NotImplementedException();
```
Alternatively, you could use some sort of regex (I have the following to pick out Tasmota telemetry)
```cs
static readonly Regex topicRegex = new("^(?:tele/)(?<device>tasmota_[^/]+)(?:/)(?<infotype>[^/]+)$");

var result = topicRegex.Match(topic);
if (result.Success)
{
    HandleTasmota(e, result);
    e.IsHandled = true;
    break;
}
```

**Comment by Kaushik-007** [comment]
@CZEMacLeod  thank you for the response . yes I found that same handler is used for both subscription. 

I need to know how the wildcard topics are mapped to actual topic and notification is published in Mqttnet code.
I need the same implementation at my end as i need to bubble out the notification to different client

**Comment by CZEMacLeod** [comment]
@Kaushik-007 I'm not sure I follow what you are asking. There is no 'wildcard' publish in MQTT (regardless of flavour, client/server). 
Once your client is subscribed (either explicitly or with wildcards), whenever a matching topic value changes on the server, any registered handlers are called with a message with the topic and value (payload), as well as other metadata. 

MQTT doesn't really have a 'bubble out' intrinsically. If a value from one device should be used as an input for another, they should be configured to publish and subscribe to the same topic. Multiple devices can subscribe (that is the point) to a single topic, so the 'bubbling' is done by the server, not by any additional code.

If you want to publish a value, like any other MQTT client you just create a new message to publish and publish it.
If you are hosting a server, you can 'inject' messages into the server and notify any subscribed clients. This allows another source, such as a webpage, or API, to update values.

There are examples of publishing in the repo: https://github.com/dotnet/MQTTnet/blob/9295626503231e50310aba104ed94e216ba4e95a/Samples/Client/Client_Publish_Samples.cs#L36

```cs
            var applicationMessage = new MqttApplicationMessageBuilder()
                .WithTopic("samples/temperature/living_room")
                .WithPayload("19.5")
                .Build();

            await mqttClient.PublishAsync(applicationMessage, CancellationToken.None);
```

Perhaps if you can give an example of what you are trying to achieve, it might be easier to point you in the right direction.
