### ISSUE TITLE
 CONNECT packet must have at least 7 bytes

### ISSUE THREAD

**Issue by zzhanxianzhi** [dotnet/MQTTnet#1809]
After connecting to the client, it frequently disconnects and prompts Error while processing CONNECT packet, CONNECT packet must have at least 7 bytes. My code
MqttServerOptionsBuilder mqttServerOptionsBuilder = new MqttServerOptionsBuilder();
mqttServerOptionsBuilder.WithDefaultEndpoint();
mqttServerOptionsBuilder.WithDefaultEndpointBoundIPAddress(IPAddress.Parse(MqttService.ip));
mqttServerOptionsBuilder.WithDefaultEndpointPort(MqttService.port);
//mqttServerOptionsBuilder.WithEncryptedEndpointPort(port);
mqttServerOptionsBuilder.WithPersistentSessions(MqttService.withPersistentSessions);
mqttServerOptionsBuilder.WithDefaultCommunicationTimeout(TimeSpan.FromMilliseconds(60000));

**Comment by chkr1011** [comment]
Is the error thrown by the client or the server? If done by the client please make sure to properly use async/await. Please also see samples (https://github.com/dotnet/MQTTnet/tree/master/Samples).

**Comment by ovidiaconescu** [comment]
This error is thrown by the server, if using the client to connect to an older version of the server it works well.

`Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets
Connection id "0HMVFGQQU7FA6" sending RST because: "CONNECT packet must have at least 7 bytes."`

**Comment by ovidiaconescu** [comment]
@jwbrothers - this Issue was closed, I've opened it again here for tracking https://github.com/dotnet/MQTTnet/issues/1897
This works with a server that is version 3.x, we just kept ours on the older version for now until it's fixed.

you're saying you can't reproduce locally - does it work with a TLS connection on your dev machine?

**Comment by jwbrothers** [comment]
Thanks @ovidiaconescu I will move my comment to your thread.

I cannot reproduce this issue in my environment at all.  I have a customer running code in their environment and they are seeing this issue often.  I suspect there is something on their network trigging the issue.  There are not any issues if they disable TLS.
