### ISSUE TITLE
How does the server receive messages from the client

### ISSUE THREAD

**Issue by YuanXiaoLcx** [dotnet/MQTTnet#1815]
MQTTnet ： V4.2.1

History:Server instance listening UseApplicationMessageReceivedHandler，How to implement the new version。

**Comment by Jeanot-Zubler** [comment]
See https://github.com/dotnet/MQTTnet/blob/master/Samples/Server/Server_Intercepting_Samples.cs

**Comment by chkr1011** [comment]
I assume that this question is answered.
