### ISSUE TITLE
Descrypt MQTT traffic in wireshark

### ISSUE THREAD

**Issue by mistoll** [dotnet/MQTTnet#1823]
### Describe your question

When using TLS with MQTTnet server, is it possible to decrypt the traffic in wireshark?

The wireshark [doc](https://wiki.wireshark.org/TLS#using-the-pre-master-secret) says I need RSA private key (which I have) or keylog.
Unfortunately the decryption with RSA private key does not work. Is it possible to get a keylog out of MQTTnet?

There's [this](https://adrianalin.gitlab.io/popsblog.me/posts/decrypt-mqtt-tls-traffic/) for Mosquitto. 

### Which project is your question related to?
- Server

**Comment by chkr1011** [comment]
I don't think this is possible at all. We make use of the TLS implementation in .NET. So if there is any chance of doing this I recommend that you search in the .NET community instead.
