### ISSUE TITLE
why not config socket receivetimeout

### ISSUE THREAD

**Issue by cuican6** [dotnet/MQTTnet#1824]
use mqttnet in linux-arm,
i send message to broker ,message level is atleastonce, i send msg and close network, get socket err use  too long time ,by read source code, i get the socket only set sendtimeout, but not set receivetimeout, i edit source code  that set socket receive timeout same as sendtimeout,  mqtt check  dis use a short time.
thanks sir.

**Comment by cuican6** [comment]
hello sir,
I have made changes to the code, but I was unable to submit a merge request。
help me sir,
thanks.

**Comment by chkr1011** [comment]
Where did you set the receive timeout? I see no property on socket level!?

**Comment by cuican6** [comment]
![image](https://github.com/dotnet/MQTTnet/assets/64738051/cdb0ebd0-92d8-4f8a-bf8a-fdbde93576c3)

**Comment by cuican6** [comment]
![image](https://github.com/dotnet/MQTTnet/assets/64738051/7ce20072-574c-4ed1-963a-b9d1ef3ac978)

**Comment by chkr1011** [comment]
From MSDN:
> This option applies to synchronous [Receive](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.receive?view=net-7.0) calls only.

In this project only the async methods are used. So it has no benefit setting it. The same also applies for the send timeout (so it might also be pointless setting it).
