### ISSUE TITLE
MqttClient hangs on ConnectAsync

### ISSUE THREAD

**Issue by nvham** [dotnet/MQTTnet#1825]
**Describe the bug**
IMqttClient instance hangs on ConnectAsync when trying to connect to a MQTT server while internet connection is off.

**Which project is your bug related to?**
Client
Basic Information
MQTTnet version: 4.2.1.781
.net 6.0
Platform: Windows

To Reproduce

**Start application**
Try to connect to a mqtt server
Application will hang on ConnectAsync method

**Expected behavior**
Client should cancel the operation and throw exception after cancellation is requested
Code example

  ```
            using (var mqttClient = mqttFactory.CreateMqttClient())
            {
                var mqttClientOptions = new MqttClientOptionsBuilder()
                    .WithClientId("mqtt-explorer-test")
                    .WithConnectionUri("testuri")
                    .WithCredentials("name", "pass")
                    .Build();


                Program crashes  here  with no error message - >>
                var res = await mqttClient.ConnectAsync(mqttClientOptions, CancellationToken.None);

                var applicationMessage = new MqttApplicationMessageBuilder()
                    .WithTopic(topic)
                    .WithPayload(json)
                    .Build();

                await mqttClient.PublishAsync(applicationMessage, CancellationToken.None);

                Console.WriteLine("MQTT application message is published.");

            }
```

**Comment by nvham** [comment]
Issue with  mqttclient.ConnectAsync.  Any suggestions?

**Comment by xyderos** [comment]
> Issue with mqttclient.ConnectAsync. Any suggestions?

You need to change your URI, this is a faulty representation.

**Comment by chkr1011** [comment]
Please use a proper cancellation token with a timeout value. Using "CancellationToken.None" will wait forever.

**Comment by nvham** [comment]
> > Issue with mqttclient.ConnectAsync. Any suggestions?
> 
> You need to change your URI, this is a faulty representation.

This was basically it.  I changed to an TCP connection and realized the original connection string was not in service.  Thanks!
