### ISSUE TITLE
NullReferenceException on TryPingAsync

### ISSUE THREAD

**Issue by codeMark1** [dotnet/MQTTnet#1831]
i try call the Samles Reconnect_Using_Timer, when run TryPingAsync, “System.NullReferenceException” Appear；i don't know what's wrong;
![image](https://github.com/dotnet/MQTTnet/assets/19514412/3369b518-4837-4673-8e49-ad45d7a8b031)
![image](https://github.com/dotnet/MQTTnet/assets/19514412/82ed5426-4635-42c8-9596-b9824141341b)

**Comment by Jeanot-Zubler** [comment]
The stack trace in english would probably be helpful

**Comment by chkr1011** [comment]
The code is not checking for the connection state (I will fix this) and the sample lacks a blocking statement so that the client will not be disposed.
