### ISSUE TITLE
Is it possible to work with Unity's WebGL build?

### ISSUE THREAD

**Issue by wwj718** [dotnet/MQTTnet#1841]
MQTTnet is a really cool project, I use it in Unity.

MQTTnet  provides great WebSocket support. It works well with unity (both development mode and native build).

I want to build the project(webSocket connection using MQTTnet) to WebGL,  it doesn't work.

What should I do?

**Comment by ovidiaconescu** [comment]
what is the error?

**Comment by wwj718** [comment]
No error message, it just doesn't work, the same project works fine in development mode and native build.

**Comment by chkr1011** [comment]
I don't think that this is the right place for that topic. We do not use any Unity libraries etc. so that I recommend that you create a ticket at Unity instead.
