### ISSUE TITLE
Server: MqttServer.StopAsync() doesn't indicate correct reason

### ISSUE THREAD

**Issue by patrickpracht** [dotnet/MQTTnet#1846]
### Describe the bug
When a asp.net core app shuts down gracefully, the client connections are closed with reason `MqttClientDisconnectOptionsReason.NormalDisconnection`.

### Which component is your bug related to?
- Server

### Expected behavior
When a graceful shutdown happens, the client connections should be closed with `MqttClientDisconnectOptionsReason.ServerShuttingDown` instead.

Sending this reason would make distinction between conditions more easy, f.e. `ServerShuttingDown` could be used by the client to try reconnecting at a later time (or never).

### Additional context / logging
Hosted service is added here: [ServiceCollectionExtensions.cs#L75](https://github.com/dotnet/MQTTnet/blob/6fdee9e0db738817c6f457c3597f84460cff3cd0/Source/MQTTnet.AspnetCore/ServiceCollectionExtensions.cs#L75)

Shutdown is observed here: [MqttHostedServer.cs#L28](https://github.com/dotnet/MQTTnet/blob/6fdee9e0db738817c6f457c3597f84460cff3cd0/Source/MQTTnet.AspnetCore/MqttHostedServer.cs#L28)

Connections are closed here: [MqttServer.cs#L295](https://github.com/dotnet/MQTTnet/blob/6fdee9e0db738817c6f457c3597f84460cff3cd0/Source/MQTTnet/Server/MqttServer.cs#L295)

**Comment by chkr1011** [comment]
Please try **exactly** build https://www.myget.org/feed/mqttnet/package/nuget/MQTTnet/4.3.1.909 from the myget feed and let me know if the issue is solved.
