### ISSUE TITLE
Integrating of server in another project

### ISSUE THREAD

**Issue by DaveSanders** [dotnet/MQTTnet#1855]
### Describe your question
I want to make sure I'm not completely misunderstanding the use of the library. We were looking to use it as a way to implement MQTT servers and clients within our existing software package. (Basically we need to ad MQTT support to our software.)

In reading through the sample code, it seems the server examples are built around having a wait loop with the console, but that obviously won't work in our situation.  Are there examples somewhere of integrating and starting a server that just runs until its told to stop?

It seems the way to stops immediately after the server starts that it doesn't work the way I expected, but I'm probably missing something.  Or maybe there's a sample I just completely didn't see that's relevant.

### Which project is your question related to?
- Server

**Comment by rlkollman** [comment]
Is this intended to run on Windows?  You can run it in a WPF or WinForms application, start the broker at application startup, and stop listening when the application closes.

If you are looking for something that just runs in the background with no user interaction, you can create a Windows Services project and start listening on Service OnStart() and stop listening OnStop(); All messages & connections are received/handled in the background until you stop the service, or the computer shuts down (or a fatal crash in the application).

I have also created classes that inherit the ApplicationContext from System.Windows.Forms to have the application run in the background without generally having a GUI, and then created a System Tray Icon to stop/restart/configure the broker.

The examples are only intended to show you how to use the MQTTNet library - just an easy, testable method to learn about the features and methods - you can implement it in any way you desire.

**Comment by DaveSanders** [comment]
Yep, I was testing it directly in a Winform app.  Simple setup of just two buttons, a start and a stop, and a logger to see what events are being called.  I could find no way to call the server to start it without it immediately shutting down. I can find no errors that indicate why its shutting down immediately, and I'm using an external mqtt tester where I can verify if there might be a port conflict or some other process running, but no luck.

And I'm not doing anything complicated, so perhaps I'm just not understanding what's really going on:

```
    public async Task Start()
    {
        LogMessage("Starting");

        // Start Server
        var mqttFactory = new MqttFactory();
        var mqttServerOptions = new MqttServerOptionsBuilder().WithConnectionBacklog(100).Build();
        // .WithDefaultEndpointPort(port)


        using (mqttServer = mqttFactory.CreateMqttServer(mqttServerOptions))
        {
            // Event Handlers
            mqttServer.StartedAsync += (e) => serverStarted(e);
            mqttServer.StoppedAsync += (e) => serverStopped(e);
            mqttServer.ClientConnectedAsync += (e) => clientConnected(e);
            mqttServer.ClientDisconnectedAsync += (e) => clientDisconnected(e);
            mqttServer.InterceptingPublishAsync += (e) => serverMessageReceived(e);

            await mqttServer.StartAsync();
            LogMessage("After Start Async");
        }
    }
```

With breakpoints I see the StartedAsync handler fires and then immediately the StoppedAsync fires.  On my front-end log, it looks like this:
```
"10/6/2023 4:52:50 PM" "broker" - "Starting"
"10/6/2023 4:52:50 PM" "broker" - "Started"
"10/6/2023 4:52:50 PM" "broker" - "After Start Async"
"10/6/2023 4:52:50 PM" "broker" - "Stopped"
```

So that's why I assumed I'm just plain doing something wrong.

**Comment by DaveSanders** [comment]
Thank you, that makes sense. I figured I was doing something dumb and I wasn't disappointed!  And yeah, I only shared the relevant code. The objects are being handled outside the function.

Removing the using worked. Thank you so much for your help.
