### ISSUE TITLE
UnobservedTaskException MqttChannelAdapter doesn't observe exception if cancelled earlier

### ISSUE THREAD

**Issue by ArsenijK** [dotnet/MQTTnet#1856]
### Description
In this part of code, if cancellation is completed first (timeout), and later you get some kind of ConnectAsync exception (i.e.: System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine), then you get UnobserverdTaskException, because nobody observes or awaits `connectTask` in the `if` statement, that throws OperationCancelledException:
`
                var connectTask = _channel.ConnectAsync(cancellationToken);

                var timeout = new TaskCompletionSource<object>();
                using (cancellationToken.Register(() => timeout.TrySetResult(null)))
                {
                    await Task.WhenAny(connectTask, timeout.Task).ConfigureAwait(false);
                    if (timeout.Task.IsCompleted && !connectTask.IsCompleted)
                    {
                        throw new OperationCanceledException("MQTT connect canceled.", cancellationToken);
                    }

                    // Make sure that the exception from the connect task gets thrown.
                    await connectTask.ConfigureAwait(false);
                }
`

### Which component is your bug related to?
- ManagedClient

### To Reproduce
1. Using this version of MQTTnet '4.3.1.873'.
2. Somehow emulate, that timeout arrives first, before ConnectAsync completes
3. And then SocketException arises in ConnectAsync (which is no longer awaited)
4. Garbage collect to get UnobservedTaskException
I've got these exceptions logged from real life clients. And library code proves my point - there is a path, when task is not await and it's Exception property is not accessed.

### Expected behavior
Exception should be observed, even if OperationCanceledException is thrown instead. Probably it can be ignored, or logged, but UnobservedTaskException should not be raised.

### Additional context / logging
Stack Trace example:

```batch
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<T, TResult> endFunction, Action<T> endAction, Task<TResult> promise, bool requiresSynchronization)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Implementations.MqttTcpChannel+<ConnectAsync>d__17.MoveNext()
```

**Comment by chkr1011** [comment]
Please try *exactly* version https://www.myget.org/feed/mqttnet/package/nuget/MQTTnet/4.3.1.907 from the myget feed and let me know if the issue still exists.
