### ISSUE TITLE
Support Custom CA chain in TLS validation

### ISSUE THREAD

**Issue by rido-min** [dotnet/MQTTnet#1857]
# Introduction

Hi! I work on the Microsoft Azure Edge platform. My team produces SDKs for customers to use in their Edge deployments so that they can use our services. We are considering taking a dependency on MQTTNet. This is our first interaction with this project and we'd like to know if you have any feedback on Microsoft using MQTTNET in this way and if there are any areas where we can contribute.

# Description
 
There are cases where we need to connect with TLS when the certificate does not chain to a trusted root, such as `test.mosquitto.org:8883`

Today, we can use the RemoteCertificateValidationCallback to customize the chain validation.

However this has some security, and performance issues:

1. This will imply that the platform will perform the validation once, and then we re-validate after the callback
2. There are some validation errors (such HostName validation) that might be easy to miss 
 
With .NET7, we could use the new [CustomTrustStore](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainpolicy.customtruststore?view=net-7.0) to configure how the platform will validate the certificate without using the callback.

> Note: This is a well-known pattern in other MQTT libraries and tools, where the `CaFile` can be specified when configuring the SslContext.

### Which project is your feature request related to?
- Client
 
### Describe the solution you'd like
I'm already proposing a solution in https://github.com/dotnet/MQTTnet/pull/1851

### Describe alternatives you've considered
configuring the callback (eg: https://github.com/Azure-Samples/MqttApplicationSamples/pull/69 )

### Additional context
Custom CAs is a common pattern in CloudNative applications, and we'd like to have support in the library without requiring additional customizations.

**Comment by chkr1011** [comment]
Implemented with #1851.
