### ISSUE TITLE
Custom interceptor for mosquito?

### ISSUE THREAD

**Issue by apetrut** [dotnet/MQTTnet#1875]
### Describe your question
How can I create a custom interceptor for the mosquito broker OR for the MQTT managed client?
What I want is to look at the message and cancel it before reaching the subscribers if it meets some conditions.

I am running mosquito locally, hence I don't create the server programmatically and I can't seem to find a way to create an interceptor for this.

### Which project is your question related to?
- ManagedClient
- Server

**Comment by sandee9** [comment]
Hi @apetrut, Found any solution to this ? I'm also stuck into a similar requirement.

**Comment by SeppPenner** [comment]
Just to make things clear: This repository has nothing to do with Mosquitto at all, so I would ask at Stackoverflow or the Mosquitto Github community if I were you...

> What I want is to look at the message and cancel it before reaching the subscribers if it meets some conditions.

Two possibilities:
1. Ask Mosquitto people if there is an interceptor similar to the one MqttNet (Server side) offers:

```csharp
// Server side code from MQTTNet if you run this server from C#.
var mqttServerOptions = new MqttFactory()
    .CreateServerOptionsBuilder()
    .WithDefaultEndpoint()
    .WithDefaultEndpointBoundIPAddress(IPAddress.Any)
    .WithDefaultEndpointPort(1883)
    .Build();
var mqttServer = this.mqttFactory.CreateMqttServer(mqttServerOptions);
mqttServer.InterceptingPublishAsync += this.InterceptPublish;
await mqttServer.StartAsync();

private async Task InterceptPublish(InterceptingPublishEventArgs args)
{
    if (args.ClientId == "SomethingIDontWantToPublish")
    {
        args.ProcessPublish = false;
        return;
    }

    args.ProcessPublish = true;
}
```

2. Check the messages your client publishes before publishing.

```csharp
// Client side code from MQTTNet if you run this client from C#.
var mqttClient = new MqttFactory().CreateMqttClient();
var mqttClientOptions = new MqttClientOptionsBuilder()
    .WithTcpServer("127.0.0.1", 1883)
    .WithClientId("SomethingRandom")
    .WithCredentials("hans", "test")
    .WithCleanSession(true)
    .WithProtocolVersion(MqttProtocolVersion.V311)
    .Build();
await mqttClient.ConnectAsync(mqttClientOptions, CancellationToken.None);

public async Task<bool> Publish(MqttApplicationMessage message)
{
    if (message.Topic == "SomethingIDontWantToPublish")
    {
        return false;
    }

    var result = await client.PublishAsync(message, CancellationToken.None);
    return result.IsSuccess;
}
```
and just give the `Publish(MqttApplicationMessage message)` method to the `outer` world / other applications that use your code. Not sure, if this is possible with the managed client, too to be honest.

**Comment by SeppPenner** [comment]
I would close this @chkr1011 as unrelated. Please re-open if you think we can help more.
