### ISSUE TITLE
Use WebSocket in .Net6.0

### ISSUE THREAD

**Issue by lurost** [dotnet/MQTTnet#1896]
### Describe your question

Hello, I have a question about how I can also enable the use of WebSocket in my .net6.0 (Project Sdk="Microsoft.NET.Sdk") application

### Which project is your question related to?
I have a class that creates a broker with logic for processing messages and also depends on other classes

```
public class MqttBrokerService : IDisposable, IHostedService, IMqttBrokerService
{
  public MqttBrokerService(...)
  {
      var options = new MqttServerOptionsBuilder()
                  .WithDefaultEndpoint()
                  .Build();
  
      _server = new MqttFactory().CreateMqttServer(options);
  }
}
```

then this class is created in the Program.cs

```
var webApplicationOptions = new WebApplicationOptions
{
  ContentRootPath = AppContext.BaseDirectory,
  Args = args,
};
var builder = WebApplication.CreateBuilder(webApplicationOptions);
var services = builder.Services;

services.AddHostedService<MqttBrokerService>();
```

Unfortunately, I don’t understand how else to enable WebSocket support specifically for the broker that will be created in this class

I will be very grateful for your help

**Comment by 296370493** [comment]
You need to use MQTTnet AspNetCore is required to support websocket

**Comment by lurost** [comment]
yes, I found it, but there the broker is created in the service by specifying the MqttServerOptionsBuilder parameter and a connection via a websocket is created through the service, but how do I indicate that you need to enable websocket support specifically for the broker that is created in this class

**Comment by 296370493** [comment]
You can refer to this example.
https://github.com/dotnet/MQTTnet/wiki/Server#aspnet-core-31-since-mqtt-version-309

**Comment by lurost** [comment]
Sorry, but I don’t really understand how it works, I did as indicated there, but the client tries to connect (via websocket and 1883) but always gets an error and disconnects (validation). 

```
services.AddSingleton<MqttBrokerService>();
services.AddHostedMqttServerWithServices(options => {
    var s = options.ServiceProvider.GetRequiredService<MqttBrokerService>();
    s.ConfigureMqttServerOptions(options);
});
services.AddMqttConnectionHandler();
services.AddMqttWebSocketServerAdapter();
services.AddConnections();
```

```
app.UseMqttEndpoint();
app.UseMqttServer(server =>
{
    var mqttBrokerService = app.Services.GetRequiredService<MqttBrokerService>();
    mqttBrokerService.ConfigureMqttServer(server);
});
```

```
public void ConfigureMqttServerOptions(AspNetMqttServerOptionsBuilder options)
{
    options.WithDefaultEndpoint();
}
public void ConfigureMqttServer(MqttServer mqtt)
{
    this._server = mqtt;
    mqtt.InterceptingPublishAsync += InterceptingPublishAsync;
    mqtt.ValidatingConnectionAsync += ValidatingConnectionAsync;
    mqtt.ClientConnectedAsync += ClientConnectedAsync;
    mqtt.ClientDisconnectedAsync += ClientDisconnectedAsync;
}
```

```
MqttBrokerService Client validating: mqtt-explorer-asdf34r2
MqttBrokerService Client disconnected: mqtt-explorer-asdf34r2


: : ConnectAsync(options, CancellationToken.None);
Error: Error while authenticating. Connection closed.
```

but there is still a problem, another class that was injected into the broker class and it should cause event publication of messages to subscribed clients, also how to do this? I just use ConfigureMqttServer to create events for processing, but how can I create a message for publication from another class that is injected into this class (it will itself be included in it via a singleton)
