### ISSUE TITLE
Recommended way to check for empty PayloadSegment property

### ISSUE THREAD

**Issue by d5UtQvp8QQU9** [dotnet/MQTTnet#1907]
### Describe your question
What is the correct, recommended way to check for empty PayloadSegment property?

I've seen
````cs
if(applicationMessage.PayloadSegment == EmptyBuffer.ArraySegment)
{
	return null;
}

if (applicationMessage.PayloadSegment.Array == null)
{
	return null;
}
````
(https://github.com/dotnet/MQTTnet/blob/v4.3.3.952/Source/MQTTnet/MqttApplicationMessageExtensions.cs#L20-L28)

I've also seen
````cs
if (e.ApplicationMessage.PayloadSegment.Count > 0)
````
(https://github.com/dotnet/MQTTnet/blob/v4.3.3.952/Source/MQTTnet.TestApp/ClientTest.cs#L37)

Shouldn't it be sufficient for practical purposes to only use the latter?

n.b.: The Count property is backed by a field, at least in latest NET runtimes. No performance penalties and no need to check the underlying array for null.

### Which project is your question related to?

- Client
- ManagedClient

**Comment by chkr1011** [comment]
Using "EmptyBuffer.ArraySegment" is somewhat internal of this library. So I recommend to not use it.
Using "e.ApplicationMessage.PayloadSegment.Count " is fine because since the array segment is a struct you will always get a proper value (0).
