### ISSUE TITLE
Support Unix Domain Sockets

### ISSUE THREAD

**Issue by rafael-biz** [dotnet/MQTTnet#1908]
### Describe the feature request
I'm am trying to connect a client application to a MQTT message broker (Mosquitto) through Unix Domain Sockets instead of the localhost loopback address (both are installed on the same machine). However, I'm using the `MqttClient` and its current implementation doesn't seem to support it.

### Which project is your feature request related to?
- Client

### Describe the solution you'd like
I would like the ability to specify the unix file name as a parameter at the `MqttClientOptionsBuilder`.

#### Example
```
    MqttClientOptions clientOptions = new MqttClientOptionsBuilder()
        .WithUnixDomainSocket("foo.socket")
        .Build();
```

**Comment by chkr1011** [comment]
These are not yet support and require a rework of the internal socket handling because it requires usage of different classes, overloads etc. I will have a look on how to implement it.

**Comment by chkr1011** [comment]
Please download the following build from the myget feed: https://www.myget.org/feed/mqttnet/package/nuget/MQTTnet/4.3.3.955

This versions adds a new overload for the client options builder (WithEndPoint). It allows you to pass another end point implementation type like the unis domain sockets.

I am not sure if you also have to change the AddressFamily in the options but it may be required.

Please test the version and let me know if it works.

**Comment by rafael-biz** [comment]
@chkr1011  Unfortunately I can't test it now because I just discovered that Mosquitto's Unix Domain Sockets support on Windows isn't working either.
https://github.com/eclipse/mosquitto/issues/2857

I'll wait for a fix in Mosquitto so I can test MQTTNet.

Thank you very much!

**Comment by chkr1011** [comment]
OK, I will then merge the PR because it exposes the EndPoint which allows using other types of endpoints.

**Comment by lt-havoc** [comment]
Since mosquitto now supports AF_UNIX and this issue shows up when searching for MQTTNet and UDS, i'll add a comment how to get it to work. As noted above, you need both `WithAddressFamily(AddressFamily.Unix)` and `WithProtocolType(ProtocolType.IP)`

```
var mqttopts = new MqttClientOptionsBuilder()
           .WithClientId("MQTTNET-on-AF_UNIX")
           .WithEndPoint(new UnixDomainSocketEndPoint("./mqttnet.sock"))
           .WithAddressFamily(AddressFamily.Unix)
           .WithProtocolType(ProtocolType.IP)
           .Build();
```

I suspect the 108 character path limitation is true for.,NET as well.
