### ISSUE TITLE
Requesting the last data from mqtt broker

### ISSUE THREAD

**Issue by TaheJdidi** [dotnet/MQTTnet#1924]
I have an MQTT client that publishes temperature data to an MQTT broker every second. 
However, I only want to receive data every minute. 
Is there a feature offered in MQTTnet that addresses this use case?

**Comment by chkr1011** [comment]
This is not possible with this library nor the MQTT protocol itself.
One thing you could try is to subscribe to the topic, wait until no more packet is received then unsubscribe and subscribe again after 1 minute.

This requires that the server persists the session and the client does not send a _clean session_ flag.
