### ISSUE TITLE
Not able to run the sample code

### ISSUE THREAD

**Issue by neetabisht** [dotnet/MQTTnet#1931]
Hi Team,

After build is successful, i am trying to run the project but facing below error.

![image](https://github.com/dotnet/MQTTnet/assets/105039104/32eebde6-4f16-4daf-ba23-cf30b45ca4f8)

can anyone help.

Thanks,
Neeta

**Comment by rido-min** [comment]
you must set the _start up project_ to the Samples. Class Libraries (like MQTTnet) cannot be started as a debug target.

**Comment by neetabisht** [comment]
Thanks a lot..it worked :)
