### ISSUE TITLE
Missing assemblies when building the solution

### ISSUE THREAD

**Issue by Korporal** [dotnet/MQTTnet#1936]
I get a few build errors with this message: "The reference assemblies for .NETCore,Version=v5.0 were not found." I'm sure it's just a simple installation I need to do but I'm not sure _exactly_ what to download here.

The message also refers to "framework" but .Net Core is nothing to do with .Net Framework so this is adding to my confusion.

![image](https://github.com/dotnet/MQTTnet/assets/12262952/a9e49fc7-ef54-428e-bbdc-a273a0c9dd10)

Also when I search specifically for this error nothing comes up, like it's just very rare. I have VS 2022 Enterprise.

Thanks.

**Comment by chkr1011** [comment]
To me it sounds like you have to download the .NET 5.0 SDK. But having the .NET 7.0 SDK installed should also work. To me it sounds like a Visual Studio installation issue but definitely not an issue with this library.
