### ISSUE TITLE
MqttServer.StartAsync  Unable to actually start the listening port

### ISSUE THREAD

**Issue by shouhujishu** [dotnet/MQTTnet#1968]
Hello, I install MQTTnet under the ASP core6-API project, version number: 4.3.3.952
Use the code under the IHosted Service interface:
var optionsBuilder = new MqttServerOptionsBuilder().WithConnectionBacklog(100).WithDefaultEndpointPort(87941)
var mMqtt = new MqttFactory(new MyLogger()).CreateMqttServer(optionsBuilder.Build())
await mMqtt.StartAsync()
On the premise that there is no abnormal error and the startup is successful, the actual mMqtt. StartAsync () is not started and does not monitor the specified port
How do I start an MQTT server side within a defined IHosted Service?

**Comment by SeppPenner** [comment]
I would recommend to build a background service following https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service and provide it within the startup:

```csharp
service.AddSingleton<MyBackgroundService>();
service.AddHostedService(p => p.GetRequiredService<MyBackgroundService>());
```

**Comment by shouhujishu** [comment]
> I would recommend to build a background service following https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service and provide it within the startup:
> 
> ```cs
> service.AddSingleton<MyBackgroundService>();
> service.AddHostedService(p => p.GetRequiredService<MyBackgroundService>());
> ```
Hello, test code output: StartAsync still does not open the port, IMqttNetLogger log has output: Started, and then there is no active content output.
`public class IotMqttServer : IHostedService
{
    private MqttServer mMqtt;
    public IotMqttServer()
    {
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        try
        {

            var optionsBuilder = new MqttServerOptionsBuilder().WithConnectionBacklog(100).WithDefaultEndpointPort(87941);
            var mMqtt = new MqttFactory(new MyLogger()).CreateMqttServer(optionsBuilder.Build());
            await mMqtt.StartAsync();
            System.Diagnostics.Debug.WriteLine("StartAsync");
        }
        catch (Exception)
        {


        }

    }
    public async Task StopAsync(CancellationToken cancellationToken)
    {
        if (mMqtt != null)
        {
            if (mMqtt.IsStarted)
            {
                await mMqtt.StopAsync();
            }
        }
    }}`
`builder.Services.AddSingleton<IotMqttServer>();
builder.Services.AddHostedService(P=>P.GetRequiredService<IotMqttServer>());`

**Comment by SeppPenner** [comment]
@shouhujishu This is how I use it:

```csharp
using MQTTnet;
using MQTTnet.Protocol;
using MQTTnet.Server;

/// <inheritdoc cref="BackgroundService"/>
public sealed class MqttBrokerService : BackgroundService
{
    /// <summary>
    /// The MQTT Server.
    /// </summary>
    public MqttServer MqttServer { get; internal set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="MqttBrokerService"/> class.
    /// </summary>
    public MqttBrokerService()
    {
        var mqttFactory = new MqttFactory();
        var mqttServerOptions = mqttFactory
            .CreateServerOptionsBuilder()
            .WithDefaultEndpoint()
            .WithDefaultEndpointBoundIPAddress(IPAddress.Parse("0.0.0.0"))
            .WithDefaultEndpointPort(1883)
            .Build();
        this.MqttServer = mqttFactory.CreateMqttServer(mqttServerOptions);
    }

    /// <inheritdoc cref="BackgroundService"/>
    public override async Task StartAsync(CancellationToken cancellationToken)
    {
        this.logger.Information("Starting MQTT server on port {Port}", 1883);

        // Start the MQTT server
        await this.MqttServer.StartAsync();

        this.logger.Information("MQTT server has started");
        await base.StartAsync(cancellationToken);
    }

    /// <inheritdoc cref="BackgroundService"/>
    public override async Task StopAsync(CancellationToken cancellationToken)
    {
        this.logger.Information("Stopping MQTT server");
        await this.MqttServer.StopAsync();
        await base.StopAsync(cancellationToken);
        this.logger.Information("MQTT server is stopped");
    }

    /// <inheritdoc cref="BackgroundService"/>
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            await Task.Delay(TimeSpan.FromSeconds(30), stoppingToken);
            this.logger.Information("MQTT server is running");
        }
    }
}
```

I guess, you were missing `.WithDefaultEndpoint()` and `.WithDefaultEndpointBoundIPAddress(IPAddress.Parse("0.0.0.0"))`.

**Comment by shouhujishu** [comment]
> @shouhujishu This is how I use it:
> 
> ```cs
> using MQTTnet;
> using MQTTnet.Protocol;
> using MQTTnet.Server;
> 
> /// <inheritdoc cref="BackgroundService"/>
> public sealed class MqttBrokerService : BackgroundService
> {
>     /// <summary>
>     /// The MQTT Server.
>     /// </summary>
>     public MqttServer MqttServer { get; internal set; }
> 
>     /// <summary>
>     /// Initializes a new instance of the <see cref="MqttBrokerService"/> class.
>     /// </summary>
>     public MqttBrokerService()
>     {
>         var mqttFactory = new MqttFactory();
>         var mqttServerOptions = mqttFactory
>             .CreateServerOptionsBuilder()
>             .WithDefaultEndpoint()
>             .WithDefaultEndpointBoundIPAddress(IPAddress.Parse("0.0.0.0"))
>             .WithDefaultEndpointPort(1883)
>             .Build();
>         this.MqttServer = mqttFactory.CreateMqttServer(mqttServerOptions);
>     }
> 
>     /// <inheritdoc cref="BackgroundService"/>
>     public override async Task StartAsync(CancellationToken cancellationToken)
>     {
>         this.logger.Information("Starting MQTT server on port {Port}", 1883);
> 
>         // Start the MQTT server
>         await this.MqttServer.StartAsync();
> 
>         this.logger.Information("MQTT server has started");
>         await base.StartAsync(cancellationToken);
>     }
> 
>     /// <inheritdoc cref="BackgroundService"/>
>     public override async Task StopAsync(CancellationToken cancellationToken)
>     {
>         this.logger.Information("Stopping MQTT server");
>         await this.MqttServer.StopAsync();
>         await base.StopAsync(cancellationToken);
>         this.logger.Information("MQTT server is stopped");
>     }
> 
>     /// <inheritdoc cref="BackgroundService"/>
>     protected override async Task ExecuteAsync(CancellationToken stoppingToken)
>     {
>         while (!stoppingToken.IsCancellationRequested)
>         {
>             await Task.Delay(TimeSpan.FromSeconds(30), stoppingToken);
>             this.logger.Information("MQTT server is running");
>         }
>     }
> }
> ```
> 
> I guess, you were missing and . Note: as IP address is needed if you want to have the broker accessible from outside the machine as well, else you can use as well. You can change the port of to any other port, of course.`.WithDefaultEndpoint()``.WithDefaultEndpointBoundIPAddress(IPAddress.Parse("0.0.0.0"))``0.0.0.0``127.0.0.1``1883`
Thanks for the help, I added WithDefaultEndpoint () and it works fine

**Comment by SeppPenner** [comment]
I guess, we can close this :)
