### ISSUE TITLE
Unable to use certificate in Ubuntu (TLS1.2)

### ISSUE THREAD

**Issue by honeyxiaoyi** [dotnet/MQTTnet#1972]
### Describe your question
A clear and concise description of what you want to know.

I use NET6 connects to the MQTT server of AWS IOT Core through the latest version of MQTTnet, using a certificate connection method.
Running normally on Windows OS, but running incorrectly on Ubuntu.
The exception information on Ubuntu is as follows:
Exception : **Received an unexpected EOF or 0 bytes from the transport stream.**

My ClientCertificatesProvider like this:
   public class MqttCert : IMqttClientCertificatesProvider
   {
       public X509CertificateCollection GetCertificates()
       {
           X509CertificateCollection x509Certificates = new X509CertificateCollection();

           var tempCaText = File.ReadAllText("RootCA1.pem"); // AmazonRootCA1.pem

           var tempCrtText = File.ReadAllText("cer.pem"); // certificate.pem.crt

           var tempKeyText = File.ReadAllText("private.pem"); // private.pem.key

           var tempCa = new X509Certificate2(X509Certificate2.CreateFromPem(tempCaText));

           var tempCrt = X509Certificate2.CreateFromPem(tempCrtText, tempKeyText);

           var ca = new X509Certificate2(tempCa.Export(X509ContentType.Pkcs12));

           var cert = new X509Certificate2(tempCrt.Export(X509ContentType.Pkcs12));

           x509Certificates.Add(ca);
           x509Certificates.Add(cert);

           return x509Certificates;
       }
   }

I used Wireshark to capture TLS1.2 packets and found that both the client sending ClientHello and the server sending ServerHello were normal on Ubuntu, but the length of the certificate sent by the client was 0, which corresponds to the above exception.
![image](https://github.com/dotnet/MQTTnet/assets/116904300/b92f5649-ae35-4643-b583-11d6440ffc90)

I would like to know the difference between Windows and Ubuntu. The same program can connect normally on Windows, but not on Ubuntu.

### Which project is your question related to?

- Client ：.NET6 
- ManagedClient
- Server ： AWS IOT Core
- Generic

**Comment by SeppPenner** [comment]
What was the issue with the certificate?
