### ISSUE TITLE
MQTTnet.AspTestApp Fails to start

### ISSUE THREAD

**Issue by grendo** [dotnet/MQTTnet#1980]
I have the latest code from the repo and tried to start the MQTTnet.AspTestApp project to test websockets.  
I had to add a handler to the program.cs as ServiceCollectionExtensions.AddHostedMqttServer crashes if it is null

builder.Services.AddMqttServer(config => {
    
});
 
After that the server started but in the web page you get
mqtt.min.js:5 WebSocket connection to 'ws://localhost:5049/mqtt' failed:

**Comment by chkr1011** [comment]
The argument check is indeed wrong. I will remove it so that it will support _null_ again as it was originally intended.

I tested with _mqttMultimeter_ and I can connect with URI: _localhost:5000/mqtt_

Do you have some logs from mqtt.min why the connection has failed?
