### ISSUE TITLE
Last Will not working?

### ISSUE THREAD

**Issue by SCHoschY** [dotnet/MQTTnet#1990]
### Describe your question
Im Currently testing LW and cant get it working.

### Which project is your question related to?
- Client

Im currently testing with [this example](https://github.com/emqx/MQTT-Client-Examples/blob/master/mqtt-client-Csharp-MqttNet/pub-sub-tcp/Program.cs)
I have extended the Optionsbuilder for credentials and last will. The credentials are working fine, but LW seems to not work.

            string topicLW = "test/LW";
            string messageLW = "Cya, im gone";

            ...
            var options = new MqttClientOptionsBuilder()
                              .WithClientId(clientId)
                              .WithTcpServer(broker, port)
                              .WithCredentials(username, password)
                              .WithCleanSession()
                              .WithKeepAlivePeriod(TimeSpan.FromSeconds(30)) 
                              //.WithWillDelayInterval(10) -> Im Using 3.1 - not implemented
                              .WithWillQualityOfServiceLevel(MqttQualityOfServiceLevel.AtLeastOnce)
                              .WithWillRetain(true)
                              .WithWillTopic(topicLW)
                              .WithWillPayload(messageLW)
                              .Build();

**Am i missing a OptionsBuilder parameter or is something off in general?**

---
The program sends 0-9 with these OptionsBuilder settings, but my "test/LW" topic does not get changed.

Im also Testing with Retained and clearing - noted here, to explain the 3rd screenshots with "missing" topic ;)

Initial Subscription 
![image](https://github.com/dotnet/MQTTnet/assets/8095296/7501a9ab-2474-4eed-a7ac-a05596401a10)

in the middle of my test-run:
![image](https://github.com/dotnet/MQTTnet/assets/8095296/701eddaf-92c3-4bc5-be96-36ee09e51158)

10 min. after the test:
![image](https://github.com/dotnet/MQTTnet/assets/8095296/d2ddeb8c-cfa7-4379-bfe3-50d5023a48c9)

if i test it with another subscriber i get the same result:

run 1
> schoschy@NB105:~$ mosquitto_sub -t test/LW -h 192.168.42.6
>
>

run 2 to verify that the normal messages do work
>schoschy@NB105:~$ mosquitto_sub -t test/csharp -h 192.168.42.6
>Hello, MQTT! Message number 0
>Hello, MQTT! Message number 1
>Hello, MQTT! Message number 2
>Hello, MQTT! Message number 3
>Hello, MQTT! Message number 4
>Hello, MQTT! Message number 5
>Hello, MQTT! Message number 6
>Hello, MQTT! Message number 7
>Hello, MQTT! Message number 8
>Hello, MQTT! Message number 9

a Wireshark trace seems to be okay aswell.

Other applications of mine do offer a working LW retained message
>schoschy@NB105:~$ mosquitto_sub -t Availability/Webio-20 -h 192.168.42.6 -v
>Availability/Webio-20 Online
+pulled Eth Cable
>Availability/Webio-20 Offline
+linked Eth Cable
>Availability/Webio-20 Online

i did start a test-instance of mosquitto to check if there are problems with my Test-broker, that did also not help.

---
Thanks for your help and have a nice week

Schoschy

**Comment by chkr1011** [comment]
In the sample the client gets disconnected properly by calling _DisconnectAsync_. This will indicate a _clean_ disconnect. The last will ist only published if the client is disconnected in a _non clean_ way.

This means losing network connection or a crashing application. You can also try to make in _non clean_ by avoiding the call of _DisconnectAsync_ and instead calling _Dispose_. Or you simply close your application :smile:
