### ISSUE TITLE
PublishAsync doesn't return a result nor exception

### ISSUE THREAD

**Issue by don-pironet-hatch** [dotnet/MQTTnet#1996]
### Describe the bug
When publishing async messages after each other we often don't get a result back and also no exception is thrown. 
On top of that we also have seen cases that the awaits are all executed but with no result (which is weird because we don't see the the result of the publish and still it goes to the next publish).

### Which component is your bug related to?
- Client

### To Reproduce
1. Using this version of MQTTnet 'v4.3.4.1084'.
2. Run this code see below
3. Not always a result is returned
4. We don't see any exception nor error.

### Expected behavior
What we expect is or a result is returned either success or not OR an exception is thrown that something did go wrong

### Code example
```csharp
	_mqttFactory = new MqttFactory();
        _mqttClient = _mqttFactory.CreateMqttClient();


	var mqttClientOptions = new MqttClientOptionsBuilder().WithTcpServer(ipAddress).WithKeepAlivePeriod(TimeSpan.FromSeconds(30)).WithCleanSession().Build();
        var response = await _mqttClient.ConnectAsync(mqttClientOptions);

        private async Task PublishTopic(string topic, byte[]? payload = null)
        {

            try
            {
                var applicationMessageBuilder = new MqttApplicationMessageBuilder()
                    .WithTopic(topic);

                if (payload != null)
                {
                    applicationMessageBuilder.WithPayload(payload);
                }

                var result = await _mqttClient.PublishAsync(applicationMessageBuilder.Build(), CancellationToken.None);
                Logger.WriteLine(
                        $"Publish topic: {topic} with success: {result.IsSuccess}"); // Often not seen
            }
            catch (Exception exception)
            {
                Logger.WriteLine($"MQTT publish failed with exception: {exception}"); // No exception when the result is never returned either
            }
        }

        public async Task Foo(byte[] data)
        {
            await _mqttPublisher.Publish(topic1, data);
            await _mqttPublisher.Publish(topic2, data); // continues even though we didn't get a result nor exception
            await _mqttPublisher.Publish(topic3, data);
        }
 
```

**Comment by chkr1011** [comment]
What exactly means "no result". Is there _null_ returned or is there a wrong reason code?

**Comment by SeppPenner** [comment]
> public async Task Foo(byte[] data)
        {
            await _mqttPublisher.Publish(topic1, data);
            await _mqttPublisher.Publish(topic2, data); // continues even though we didn't get a result nor exception
            await _mqttPublisher.Publish(topic3, data);
        }

How do you expect to get a result if you don't read it into a variable? ` await _mqttPublisher.Publish(topic2, data);` will always proceed unless an exception is thrown and that is alright?

What about something like:

```csharp
public async Task Foo(byte[] data)
{
    var x = await _mqttPublisher.Publish(topic1, data);
    var y = await _mqttPublisher.Publish(topic2, data); // continues even though we didn't get a result nor exception
    var z = await _mqttPublisher.Publish(topic3, data);
}
```

**Comment by don-pironet-hatch** [comment]
What I would expect is that this line:

`                var result = await _mqttClient.PublishAsync(applicationMessageBuilder.Build(), CancellationToken.None);`
always have a result stored in that property before returning. And if there is an exception that an exception is thrown. Now we see that it publishes the mqtt command but before the PublishAsync ends we are already executing the next commands
