### ISSUE TITLE
Breaking Change in MqttClientTcpOptions with 4.3.5.1141

### ISSUE THREAD

**Issue by rido-min** [dotnet/MQTTnet#2005]
With  4.3.5.1141 `MqttClientTcpOptions` `Server` and `Port` are marked as obsolete, however those properties return null. 

We are extending the  `MqttClientOptionsBuilder`  with more `.WithXXX` methods, to verify those methods we have unit tests like.

```cs
 MqttConnectionSettings mqttConnectionSettings = new("localhost")
  {
      ClientId = "clientId",
      TcpPort = 4343,
      Username = "user",
      KeepAlive = TimeSpan.FromSeconds(15),
      CleanStart = false,
  };
  MqttClientOptions options = mqttClientOptionsBuilder.WithMqttConnectionSettings(mqttConnectionSettings).Build();
  Assert.NotNull(options);
  Assert.False(options.CleanSession);
  Assert.Equal("clientId", options.ClientId);
  Assert.Equal(TimeSpan.FromSeconds(15), options.KeepAlivePeriod);
  MqttClientTcpOptions tcpOptions = (MqttClientTcpOptions)options.ChannelOptions;
  Assert.Equal("localhost", tcpOptions.Server);
  Assert.Equal(4343, tcpOptions.Port);
```

The last two asserts fail with Null.

I tried to use `RemoteEndpoint` instead, but it does not include properties for `Server` and `Port`

Probably related, when connecting the traces show `Trying to connect with server 'Unspecified/localhost:1883'` (note the **Unspecified**, as this seems to be `RemoteEndpoint.ToString()` )

This change is not mentioned in the [Release Notes](https://github.com/dotnet/MQTTnet/releases/tag/v4.3.5.1141)

**Comment by chkr1011** [comment]
The origin of this issue was adding support for unix sockets which exposes the base remote endpoint instead of a dedicated server and port property. In your case you must use a _DnsEndPoint_ for the _RemoteEndpoint_ as the _WithTcpServer_ does. I restored the _Server_ and _Port_ properties because it would lead to a breaking change but unfortunately the behavior of these properties is still different. I will have a look how to restore the behavior...

**Comment by chkr1011** [comment]
I restored the old behavior. Please test build 4.3.5.1148 from MyGet and let me know if it works.

**Comment by rido-min** [comment]
yep, it works. Thanks for the quick update!!

BTW, we will keep the other workaround of casting the RemoteEndpoint to DnsEndPoint to avoid the obsolete warning.

**Comment by lukas-mertens** [comment]
Was this actually published in a release already? Because I don't see a 1148 release, the latest for me is a 1141 release.

**Comment by chkr1011** [comment]
It was released a few seconds ago.
