### ISSUE TITLE
Connecting To localhost...Could not open connection to the host, on port 1883: Connect failed

### ISSUE THREAD

**Issue by LeGi0N09** [dotnet/MQTTnet#2013]
using MQTTnet.Server;
using MQTTnet;
using System;
using System.Threading.Tasks;

namespace MQTTDemo
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var options = new MqttServerOptionsBuilder()
                .WithDefaultEndpointPort(1883)
                .Build();

            var mqttServer = new MqttFactory().CreateMqttServer(options);

            mqttServer.ClientConnectedAsync += async e =>
            {
                Console.WriteLine($"Client '{e.ClientId}' connected.");
                await Task.CompletedTask;
            };

            mqttServer.ClientDisconnectedAsync += async e =>
            {
                Console.WriteLine($"Client '{e.ClientId}' disconnected.");
                await Task.CompletedTask;
            };

            mqttServer.StartedAsync += async e =>
            {
                Console.WriteLine("MQTT Broker started and listening on port 1883.");
                await Task.CompletedTask;
            };

            mqttServer.StoppedAsync += async e =>
            {
                Console.WriteLine("MQTT Broker stopped.");
                await Task.CompletedTask;
            };

            await mqttServer.StartAsync();

            // Keep the application running to keep the broker alive
            Console.WriteLine("Press any key to exit...");
            Console.ReadLine();
            await mqttServer.StopAsync();
        }
    }
}

**Comment by SeppPenner** [comment]
Can you try

```csharp
var options = new MqttServerOptionsBuilder()
.WithDefaultEndpoint()
.WithDefaultEndpointPort(1883)
.Build();
```

**Comment by LeGi0N09** [comment]
done
