### ISSUE TITLE
Target .net8 framework

### ISSUE THREAD

**Issue by montigab78** [dotnet/MQTTnet#2041]
Hi,
have you got any plan to target .net8 framework?

Thanks

**Comment by chkr1011** [comment]
Version 5 of the library will target .net8.

**Comment by yannicvlegel** [comment]
Does the current version work on .net8 or will it not work?

**Comment by SeppPenner** [comment]
> Does the current version work on .net8 or will it not work?

Yes, it does. We use it in production with Net8.
