### ISSUE TITLE
How to publish messages from the server to the client

### ISSUE THREAD

**Issue by dfengpo** [dotnet/MQTTnet#2049]
How to publish messages from the server to the client

I couldn't find the method

**Comment by SeppPenner** [comment]
Please see the example under https://github.com/dotnet/MQTTnet/blob/e18a91a4b59bc312aa9acf9be575401d07b793e4/Samples/Server/Server_Simple_Samples.cs#L39

**Comment by antlu65** [comment]
Use MqttServer.InjectApplicationMessage(...) to a topic subscribed to by the MqttClient.

**Comment by SeppPenner** [comment]
That should be solved, I guess.
