### ISSUE TITLE
Dose MQTTnet support Native AOT? 

### ISSUE THREAD

**Issue by yxlolxy** [dotnet/MQTTnet#2056]
### Describe the feature request
i will generate a dll lib via native aot, Dose MQTTnet support Native AOT?

**Comment by chkr1011** [comment]
I don't know if there is anything we can actively do to support it. I assume you need to just give it a try if it works or not.

**Comment by Vincent-X-Zhang** [comment]
@chkr1011 does MQTTnet 5.x support aot now? I mean if there have any dynamic code suck like reflection or expression?

**Comment by chkr1011** [comment]
There is no reflection happening or dynamic code generation happening in the library.
