### ISSUE TITLE
Reopen: nuget version of MQTTnet.Extensions.TopicTemplate is not up to date

### ISSUE THREAD

**Issue by clively** [dotnet/MQTTnet#2057]
I do not have the ability to reopen issues, so per github recommendations I am creating a new one.

Original issue: [https://github.com/dotnet/MQTTnet/issues/2055](https://github.com/dotnet/MQTTnet/issues/2055)

I have confirmed that the version numbers now match, however when attempting to use the packages with the sample project I get the following:

`CS1929 'MqttClientSubscribeOptionsBuilder' does not contain a definition for 'WithTopicTemplate' and the best extension method overload 'TopicTemplateExtensions.WithTopicTemplate(MqttTopicFilterBuilder, MqttTopicTemplate, bool)' requires a receiver of type 'MQTTnet.MqttTopicFilterBuilder' MQTTnet.Samples C:<my project details>\Samples\Client\Client_Subscribe_Samples.cs 47`

What I did was pull just that one project from your github repo. I then changed the project references to target the latest versions of the packages on nuget. And then I did a build. I'm attaching a screen shot.

It looks like the MqttClientSubscribeOptionsBuilder WithTopicTemplate extension method was not compiled into the package.

![mqttnetissues](https://github.com/user-attachments/assets/65105565-a10a-40ec-b2c3-5609610968f8)

**Comment by SeppPenner** [comment]
What's the problem with using a `MqttTopicFilterBuilder`?

**Comment by VedMod** [comment]
I have the same problem.

> What's the problem with using a `MqttTopicFilterBuilder`?

The "problem" is, that this is from the [sample code](https://github.com/dotnet/MQTTnet/blob/e18a91a4b59bc312aa9acf9be575401d07b793e4/Samples/Client/Client_Subscribe_Samples.cs#L47C52-L47C81) from the current master branch, so the sample hast to be adapted or there is a bug.

@SeppPenner or can u light us up and show the working code with the MqttTopicFilterBuilder?

**Comment by SeppPenner** [comment]
Maybe this is not yet released @chkr1011 ?

**Comment by simonthum** [comment]
The issue is that the master examples depend on the master template extension. While unfortunate, it is a one-off and has an easy solution. When you open the full project solution (not just examples), things should work fine.

**Comment by simonthum** [comment]
@SeppPenner I think this can be closed.
