### ISSUE TITLE
When using InjectApplicationMessage the client does not receive any message when the topic starts with `$`

### ISSUE THREAD

**Issue by nullbydefault** [dotnet/MQTTnet#2059]
### Description

I am using the MqttNet server and want to publish messages from the broker to connected clients.
To do this I am using the `InjectApplicationMessage` method.
It seems like the server blocks the message from being published when the topic starts with `$`.
When I send messages that does not start with `$` the clients will receive the message.

### Which component is your bug related to?
- Server

### To Reproduce
1. Using this version of MQTTnet '4.3.6.1152'.
2. Sending messages to clients.
```
var mqttMessage = new MqttApplicationMessageBuilder().WithTopic("$foo/bar")
                                                .WithPayload("Hello")
                                                .WithRetainFlag(true)
                                                .WithQualityOfServiceLevel(MqttQualityOfServiceLevel.AtMostOnce)
                                                .Build();
                                                
var appMessage = new InjectedMqttApplicationMessage(mqttMessage)
{
    SenderClientId = $"{this.ServerId}"
};
await this._mqttServer.InjectApplicationMessage(appMessage);
```

Setting the topic to `foo/bar` will make it work... So for some reason the `$` prevents the message to be sent.

### Expected behavior

Connected clients that subscribe to for example `#` should get the message

### Actual behavior

No message is received and no error is seen.

## Update

If I subscribe to `$foo/#` it works, so it seems like when only subscribing to `#` you do not get the messages if they start with `$`

**Comment by bxb-l** [comment]
Did your server successfully send the message?What I tested was fine.
![image](https://github.com/user-attachments/assets/6794856e-353e-4773-966e-92293944ce8a)

**Comment by nullbydefault** [comment]
Are you doing the same thing? Using `InjectedMqttApplicationMessage` ? 
For me the server fail to send messages to wild card subscribers when they are subscribing to `#`. 
As mentioned above subscribing to for example `$foo/#` works just fine. 

Other brokers/servers works as expected, but this one does not send messages to subscribers using `#` as topic.

**Comment by bxb-l** [comment]
Yes, I'm using it.
But I didn't use # to subscribe to $.

**Comment by Jeanot-Zubler** [comment]
I don't know about mqttnet, but other brokers (e.g. [mosquitto](https://mosquitto.org/man/mosquitto-8.html#idm456)) do not publish `$SYS` topics when just subscribed to `#`.

**Comment by nullbydefault** [comment]
Found this in the MQTT specification, so I will close this.
```
 A subscription to “#” will not receive any messages published to a topic beginning with a $
```
