### ISSUE TITLE
MQTTClient Thread-safety: Publishing

### ISSUE THREAD

**Issue by fazho** [dotnet/MQTTnet#2077]
### Describe your question
I am using MqttClient class (https://github.com/dotnet/MQTTnet/blob/2fdbb02dc8922937e751a75a1f2f3163dcf45300/Source/MQTTnet/MqttClient.cs#L21) to publish MQTT messages. The method I am calling is PublishAsync(). Right now my code can access the same MqttClient object from multiple threads. Is MqttClient or PublishAsync() thread safe? 

### Which project is your question related to?

- Client

**Comment by fazho** [comment]
@chkr1011 for visibility. Thanks!

**Comment by fazho** [comment]
QoS Level: at least once

**Comment by chkr1011** [comment]
The client is not thread safe.

**Comment by fazho** [comment]
Deep-dive thread: https://github.com/dotnet/MQTTnet/issues/2078
