### ISSUE TITLE
Cannot find MqttServerFactory?

### ISSUE THREAD

**Issue by JansthcirlU** [dotnet/MQTTnet#2085]
### Describe the bug

I've created a new class library project, added `MQTTnet` to it, but when trying to make a new `MqttServerFactory`, the IDE complains that that class cannot be found.

### Which component is your bug related to?

- Server

### To Reproduce

1. Using this version of MQTTnet '4.3.7.1207'.
2. Using .NET 8
3. Create a new class library using `dotnet new classlib`.
4. Add a field of type `MqttServerFactory`.
5. See error CS0246: The type or namespace name 'MqttServerFactory' could not be found (are you missing a using directive or an assembly reference?).

### Expected behavior

The `MqttServerFactory` class, which lives inside the `Server` namespace and is public, should be recognized.

### Screenshots

![image](https://github.com/user-attachments/assets/32a9aa8c-87f5-4df6-9b08-39991067ee67)

### Code example

```cs
using Microsoft.Extensions.Hosting;
using MQTTnet.Server;

namespace MqttHosting;

public class MqttHost : IHostedService
{
    private readonly MqttServerFactory _serverFactory;

    public MqttHost(MqttServerFactory serverFactory)
    {
        _serverFactory = serverFactory;
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        Console.WriteLine("server starting");
    }

    public async Task StopAsync(CancellationToken cancellationToken)
    {
        Console.WriteLine("server stopping");
    }
}
```
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
  </ItemGroup>

</Project>
```

**Comment by rg0815** [comment]
Had the same problem.
There is a error in the given example.

Solution:
Replace "MqttServerFactory" with "MqttFactory".
This should solve your problem.

**Comment by SeppPenner** [comment]
> There is an error in the given example.

No, the wiki is just not used anymore, just for version 3.x. For version 4.x, refer to the https://github.com/dotnet/MQTTnet/tree/master/Samples folder, please.
