### ISSUE TITLE
Error while authenticating. Extended authentication handler is not yet supported, with Azure Event Grid MQTT Broker

### ISSUE THREAD

**Issue by pre-subham** [dotnet/MQTTnet#2095]
### Describe the bug
We're facing this error: 
**Error while authenticating. Extended authentication handler is not yet supported. with the Latest MQTT net release and Azure Event Grid MQTT Broker.**
We have already tried the solution mentioned to recreate the certificate/user for the Broker, but this issue is frequent on two days basis on One particular Broker out of 3 setups. 
Everything is consistent across deployment but the issue is faced with one broker only.

### Which component is your bug related to?
- Client
- Server

### To Reproduce
1. Using this version of MQTTnet '...'.
     4.2.1.781, 4.3.7.1207
2. Run this code '....'.
```
mqttClientOptions = new MqttClientOptionsBuilder()
                    .WithClientId(MqttPublisherConstant.userId)
                    .WithTcpServer(MqttPublisherConstant.connectHost, MqttPublisherConstant.port)
                    .WithTls(new MqttClientOptionsBuilderTlsParameters
                    {
                        UseTls = true,
                        Certificates = certs
                    })
                    .WithCredentials(MqttPublisherConstant.userName)
```

### Expected behavior
Should connect without any issues.

### Screenshots
![Image](https://github.com/user-attachments/assets/31e7f9ea-cc2c-44dc-93a9-ee8ce7bf036c)

**Comment by rido-min** [comment]
ExtendedAuthentication is supported with MQTT5, and usually used with OAUTH tokens, not sure what's the use case to use ExtendedAuth with certificates.

There is a sample to connect to [EventGrid with JWT tokens](https://github.com/Azure-Samples/MqttApplicationSamples/blob/main/scenarios/jwt_authentication/dotnet/jwt_authentication/Program.cs)  

note how ExtendedAuth is used in the  [WithJWT](https://github.com/Azure-Samples/MqttApplicationSamples/blob/e0411eef86958f5c91de63a0f5ecc845da88a97c/mqttclients/dotnet/MQTTnet.Client.Extensions/WithJWT.cs#L30-L35) extension method

**Comment by pre-consultant** [comment]
What is the change required here for the use of certificate @rido-min. We have been running same for past 1 year, this error started coming now. We have not mentioned protocol, hence it's using default which should be v3.1.

**Comment by chkr1011** [comment]
@pre-subham  It seems that this feature is broken (regardless of certificates or other variant). There is a handler for that but not used when connecting.
I will add it and let you know when a test version is available.

**Comment by pre-consultant** [comment]
@chkr1011 What can we do in the meantime, the broker is disconnecting every day

**Comment by pre-consultant** [comment]
Hi @chkr1011 , do you have any version where this feature will work or any step for keeping it from disconnecting until new version is available?
