### ISSUE TITLE
About statistics of _bytesSent and _bytesReceived

### ISSUE THREAD

**Issue by xljiulang** [dotnet/MQTTnet#2104]
I am not sure if the following behavior is a bug. 
In [MqttChannelAdapter.cs#L166](https://github.com/dotnet/MQTTnet/blob/master/Source/MQTTnet/Adapter/MqttChannelAdapter.cs#L166) and [MqttChannelAdapter.cs#L239](https://github.com/dotnet/MQTTnet/blob/master/Source/MQTTnet/Adapter/MqttChannelAdapter.cs#L239),  sent is counted counts to _bytesReceived, and t receive counts to _bytesSentand .

**Comment by chkr1011** [comment]
This is by design. These values are always written from the perspective of the owner.
So, the server has SENT 100 MB to the client, but the client RECEIVED 100 MB.
