### ISSUE TITLE
Any way to generate events on receipt of PUBACK or PUBREC packets?

### ISSUE THREAD

**Issue by trev0115** [dotnet/MQTTnet#487]
To prove that a subscribed client received the message from a server, it would be nice if the server could raise a event indicating a PUBACK in QOS1 or PUBREC in QOS2 was received. Mostly used for logging. Is this something that could be added to the MqttServer?

**Comment by chkr1011** [comment]
So you mean just a plain event (probably containing the application message and client ID as a property) which is fired after every ACK and PUBREC?

**Comment by trev0115** [comment]
Yeah, that would be perfect.

**Comment by trev0115** [comment]
When the client connects, I will publish a message with the client's ID and human-readable identifier to the server, storing it in a hashtable. Then when an ACK or PUBREC packet arrives, I can look up the human-readable identifier in the hashtable to display in a log with the topic and payload. This should prove that the client acknowledged receipt of the message from the server.

**Comment by SeppPenner** [comment]
What's the status of this?

**Comment by chkr1011** [comment]
I added this feature and it will be release with version 4.1.x.
