### ISSUE TITLE
Adopt async/await in the MQTTnet internals

### ISSUE THREAD

**Issue by dpsenner** [dotnet/MQTTnet#556]
Today there are several `Task.Run` invocations to work around deadlock situations. In a properly designed async/await stack these should not be necessary. By implementing the async/await pattern throughout the internals would make the MQTTnet internals (effectively) single-threaded and thus further resolve issues like  #523. This issue also relates to #524.

**Comment by dpsenner** [comment]
This issue further relates to #554, #535, #523 and #506.

**Comment by dpsenner** [comment]
Some discussion already happened in PR #550, starting with [this comment](https://github.com/chkr1011/MQTTnet/pull/550#discussion_r257802778).

**Comment by dpsenner** [comment]
We should at first discuss how MQTTnet should behave when a PUB is received. It may send PUBREL or PUBACK to the broker:

1. on receipt before calling user space (before invocation of `ReceivedApplicationMessageHandler`)
1. on receipt after calling user space

With option two we can opt to not send PUBREL or PUBACK when an unhandled exception handles in user space when handling the PUB.

**Comment by dpsenner** [comment]
After crawling the issues, this issue appears to be a duplicate of #506 and @dealproc appears to have already done some more to make MQTTnet completely async. I would like to kindly invite @dealproc, @ramonsmits and @chkr1011 to join this conversation and make this happen as a joint effort.

**Comment by BennyM** [comment]
FYI with the current develop branch I can get into a deadlock when I unplug the wifi router (or move out of its range). Reconnection attempts will start but eventually a deadlock occurs.

**Comment by GieltjE** [comment]
@BennyM there have been several incidents of deadlocks in the past with bad/broken connections, seems to be a recurring theme (which is understandable given the complexity of the project and intended purpouse).

**Comment by dpsenner** [comment]
@BennyM I observed that too and a fix should be the outcome of this issue.

**Comment by chkr1011** [comment]
@BennyM Do you have some example code to reproduce this? To you have event handlers etc. attached? My devices are reconnecting without problems. So I am wondering about the diff.

**Comment by chkr1011** [comment]
Ah OK I understand.

**Comment by BennyM** [comment]
I will try to create a repro with code. Though probably not that easy. I really tested with unplugging the router :)

**Comment by dpsenner** [comment]
I observed a starvation (not necessarily a deadlock scenario) with the new task api when I attempted to forward a previously published message to another topic and returning the task returned by `PublishAsync()`. Ideally, that task is implemented as `TaskCompletionSource` that, depending on QoS, completes either when:

* QoS0: the publish was sent (with tcp transport this would mean that it actually was received and ack'd by the broker)
* QoS1: puback was received
* QoS2: pubcomp was received

**Comment by dpsenner** [comment]
I have summarized the expected async behavior in a sequence diagram. It consists of four sequences:

![sequence diagram](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=cGFydGljaXBhbnQgTG9uZ1J1bm5pbmdUYXNrCgpub3RlIGxlZnQgb2YgVXNlclNwYWNlOiBzaW1wbGUgcHVibGlzaCB3aXRoIFFvUyAyCgAcCS0tPisAJwtiZWdpbgApCAAbCz4rTXF0dENsaWVudDogUABLBkFzeW5jKCkKABEKLS0-ABwMbmV3IFRhc2tDb21wbGV0aW9uU291cmNlACQQAIEoC3JldHVybiB0ACMTLgCBaAUAYgsAgQ8GQnJva2VyOiBQVUJMSVNIAIFaBwAQCgCBBQ9QVUJSRUMAgSISADwLUkVMADIOLQAyD0NPTVAAgVwaAIEnFVNldFJlc3VsdACCIg4-LQCDJAtwcmV2aW91c2x5AIIAB2VkAIIEBSBjAII6BmVzAIMrDQAuDQCDXAcAIggAhA0HcmlnaACEEAUAgh0MAIQPB3N1YnNjcmlwdGlvbgCEDwwAgi0NAIJVDWIAgmUFIHJlY2VpdmVzAIQeCQCCYQsAhBkPAIMCEQCDMQkAhRsLYXdhaXQgQXBwbGljYXRpb25NZXNzYWdlSGFuZGxlcigpAIVHGWFzeW5jIGNvZGUgb3IgY3B1IGludGVuc2l2ZQCCMwZ0aGF0AIRMB3MAhQUFAIVHDACDSQ0AhG0LOwCFNxoAawYAgwUPAIJYEgAmCXQgdGhpcyBwb2ludACBYQcAg0IKAIRlHgCFHQYAhSkaAIUdBgCEPgkAhXsPAIUZCQCFNg4AgzkRbGVhc2VzIHJlcwCHFAVzAIQbHQCEGxYAgl8GZm9yd2FyZHMgbQCDNwYAiGMKMQCDPoEUAINoHwCJUw4AhAQNAIhbGgCBXA0AiCMRQUNLAIQzJW9mAIpQDwCCY4FPcwCEKghvZmZsb2FkcyB0aACNGQoAiSsGYXdheQCDF4EfKgCOdg86AIIHgkwAkVIPLT4Agl0QAI4HC2Rlc3Ryb3kAkgUQ&s=qsd)

In the last of the four sequences I outlined how a long running task could be started while the publish completes immediately. The code in the ApplicationMessageHandler would in this case read like:

```csharp
Task StartLongRunningTaskHandler(ApplicationMessage message) {
    Task.Run(LongRunningTask); // fire and forget
    // it would be wise to record the long running task into a registry that would further allow it to be cancelled
    // using new CancellationTokenSource() for this purpose would be a good option
    return Task.Completed;
}
```

**Comment by dpsenner** [comment]
I stumbled upon [this interesting discussion](https://github.com/AtherEnergy/rumqtt/issues/94) while investigating at which point in time other mqtt client libraries send puback / pubrel (i.e. before calling userspace or after).

While we discuss changing the api by adding async interfaces, does it make sense to pass the message handler into `SubscribeAsync` instead? MQTTnet could then take care of matching the topic and calling the appropriate message handler when a publish arrives that matches the subscription. We could then further add an overload of `SubscribeAsync` that allows to customize the point in time when puback / pubrel are sent.

**Comment by chkr1011** [comment]
Since a long time has passed please try with version 4 and reopen this ticket of the issue persists.
