### ISSUE TITLE
GetClientSessionsStatus causes server to hang

### ISSUE THREAD

**Issue by PontusHolmberg** [dotnet/MQTTnet#573]
I tried call the GetClientSessionsStatus when clients disconnects to update my listbox.
It works sometimes, but most of the time it locks up and the functions never returns.

I current only use it when client connects, but the list gets long after a few days.
Clients that has disconnected is still returned by the GetClientSessionsStatus.

**Comment by bartbreur** [comment]
Same here, a call to GetClientSessionsStatus takes forever. (Version 2.8.5) 
Before we upgraded from 2.7.5 to 2.8.5 we didn't have this problem, might be a clue. 
A probable cause is that the call waits indefinitely for the lock on _sessions (MqttClientSessionsManager).
But it's hard to find a deadlock victim. The only thing I can see is a lot things happening from within the lock (firing events) that can hopefully be placed outside the lock, maybe this helps. 
I'm looking at Commit 64b38487. Hope this gives a hint.

**Comment by PontusHolmberg** [comment]
Hm.
Also, disconnected devices is not removed for the lists returned by "GetclientSessionsStatus", but maybe they are not suppose to?

**Comment by imanpeeman** [comment]
@JanEggers do you have an opinion / solution for/on this?

**Comment by JanEggers** [comment]
@imanpeeman i dont use that API so i have not experienced this issue.

I think the best approach is to create a repositiory with runnable code to reproduce the error. 

If we have that @chkr1011 and I can look at that code and figure out what causes the deadlock

**Comment by imanpeeman** [comment]
Some progress on this:
- It seems to occur ONLY in release builds of the library. 
- The deadlock occurs when something fails / hang in the PrepareClientSession method. (see screenshot) from a debug session with the library build in release mode)

![deadlockGetSessions](https://user-images.githubusercontent.com/6469882/59746484-4e10d400-9277-11e9-8374-dad1bc81ea57.png)

I'm currently working on a unittest to reproduce the issue, I hope to be able to get it in deadlock in debug build also. To be continued!

**Comment by JanEggers** [comment]
could you please expand the callstack of prepareClient and also the other threads that are blocked on manualreseteventslim.wait()

**Comment by JanEggers** [comment]
or maybe just update to the latest version I cant find a method prepareClient

**Comment by imanpeeman** [comment]
Hi Jan, we're on the 2.8.5 version while the 3.0.x branch is too young for us. At the moment i'm trying to reproduce the deadlock to provide the callstacks.

regards,

**Comment by imanpeeman** [comment]
@JanEggers just reproduced in release build. The ManualResetEvent.Wait has an external code callstack, and no details.  i'll try in debug again.... fingers crossed

**Comment by SeppPenner** [comment]
@imanpeeman Do you have some code that we can reproduce this?

**Comment by imanpeeman** [comment]
> @imanpeeman Do you have some code that we can reproduce this?

Hi, 

Unfortunately we can't reproduce in debug mode to find out where the deadlock occurs. 
Last weekend we run an endurance test with a debug build of the 2.8.5 version (home-brew) which doesn't lock. Inspection of the code turns out that there are many .getAwaiter().getResult() which are fine for performance, but are recipe for dead-locks. 
For now we're investigating why it doesn't deadlock in debug build.

We're focussing on the MqttClientSessionsManager class, because that's where we see the deadlock occur.

**Comment by SeppPenner** [comment]
@imanpeeman Ok, thanks for the update. Just give us all a hint if you see something strange in there ;)

**Comment by imanpeeman** [comment]
@SeppPenner  @JanEggers @chkr1011 Ok, back again, and re-produced the issue with a debug build and stacktraces. :) See the attached screenshot causing the deadlock. it has to do with de Stop of a session within the _sessions lock and a GetAwaiter().GetResult is not returning. Which is also the manualResetEventSlim mentioned in the screenshot of my earlier comment. 


![deadlock](https://user-images.githubusercontent.com/6469882/60665916-0d63ae00-9e66-11e9-98f3-fba8262df10c.png)
![image](https://user-images.githubusercontent.com/6469882/60666231-dc37ad80-9e66-11e9-8fbf-ecefeeeb44d4.png)

**Comment by endlessmind** [comment]
Any more updates on this?

**Comment by bartbreur** [comment]
Hi Pontus e.a., we are testing a custom build of the library to see if replacements of certain GetAwaiter.GetResult statements by await is solving the issue. If so, I would like to submit a pull request. But it is too early to do so now.

Kind regards, Bart Breur

Van: Pontus Holmberg
Verstuurd: maandag 12 augustus 16:16
Onderwerp: Re: [chkr1011/MQTTnet] GetClientSessionsStatus causes server to hang (#573)
Aan: chkr1011/MQTTnet
Cc: Bart Breur, Comment


Any more updates on this?

**Comment by SeppPenner** [comment]
@endlessmind No update from my side. I haven't tried this yet to be honest.

**Comment by PontusHolmberg** [comment]
Any news on the progress? :-)

**Comment by chkr1011** [comment]
Please try again with the latest 4.0 preview from the MyGet feed. The way how the server handles and sends messages is completely reworked. If this problem still appears please reopen this ticket.
