### ISSUE TITLE
perf improvements

### ISSUE THREAD

**Issue by JanEggers** [dotnet/MQTTnet#596]
I like to keep improving latency / throughput

my current approach was to mimic some changes the asp.net guys did.

one thing that is left is this:

- only create async statemachine if actually required
https://github.com/aspnet/AspNetCore/pull/9512

this issue should be a reminder / todo list for myself but if anyone has suggestions how to speed things up feel free to post them here

**Comment by JanEggers** [comment]
try this: https://adamsitnik.com/ConcurrencyVisualizer-Profiler/

**Comment by chkr1011** [comment]
Please checkout latency / throughput with latest 4.0.0 preview from MyGet feed and let me know (in a new ticket) if it is even better now 😄
