### ISSUE TITLE
Can I catch a puback from client?

### ISSUE THREAD

**Issue by avengerstark** [dotnet/MQTTnet#624]
Hello, I want to see pubacks from client. Is it possible?

**Comment by chkr1011** [comment]
Hi,
this is not possible. Why do you need that? 
Best regards
Christian

**Comment by avengerstark** [comment]
I want to check that the message is received by client.

**Comment by chkr1011** [comment]
Do you want to check this in the server or client? I can add a new event handler for such a situation.

**Comment by avengerstark** [comment]
I want to check this in the server.

**Comment by kyoani** [comment]
> Do you want to check this in the server or client? I can add a new event handler for such a situation.

Hello!  Have you finished this event handler?  I need to check that the message is received int the server too...

**Comment by chkr1011** [comment]
This event handler will be added in version 4.1. The myget preview feed already contains this feature.
