### ISSUE TITLE
Managed MQTT Client + Subscribe Options

### ISSUE THREAD

**Issue by CaiB** [dotnet/MQTTnet#675]
Hi there,

I'm trying to use the `ManagedMqttClient` along with the `SubscriptionIdentifier` functionality of `MqttClientSubscribeOptions`, but there is no overload of `SubscribeAsync()` that supports using the extended options, only ones that use `TopicFilter` in different ways.

Is this something that is difficult/not recommended because of how the managed client stores messages internally?

Is there another way that I should be managing multiple subscriptions with independent handlers with the managed client?

Thanks!

**Comment by chkr1011** [comment]
Hi,
sorry but this is yet not supported. If you need that you should use the regular _MqttClient_. But this client does not reconnect automatically etc.

Best regards
Christian

**Comment by CaiB** [comment]
Thanks for the quick response, I'll use the regular client instead.

**Comment by SeppPenner** [comment]
@chkr1011 Do you want to keep this open as feature request for the future?

**Comment by chkr1011** [comment]
Yes.

**Comment by CaiB** [comment]
I'm having some trouble related to this. I've switched back to using the non-managed client, but I still don't see a good way to have multiple different subscriptions that each call a different handler method when they receive a published message. Initially, I thought that was the purpose of the `SubscriptionIdentifier`, but that does not appear to be the case.

What is the recommended way of handling multiple subscriptions going to separate listeners?

Thanks!

**Comment by chkr1011** [comment]
This is literally not possible. There is no way in MQTT to associate a handler with a certain subscription. You can use a subscription identifier etc. and check this in the single handler to distribute handling to other components etc. But in the end it is your turn.

Also sending the _SubscriptionIdentifier_ using the managed client is supported now.
