### ISSUE TITLE
ManagedMQTTClient Retry Best Practice

### ISSUE THREAD

**Issue by MattComb** [dotnet/MQTTnet#750]
I have a couple of real world scenarios I wanted to raise.

What happens if the user/password credentials are changed AFTER a successful connection has occurred. I believe a publish of a message causes the connection to disconnect, and then when it tries automatically to reconnect it cannot. How many times will it try before giving up ?

Similarly, in normal use we are seeing that if a second connection connects using the same clientID, the first connection will disconnect and then retry. It appears to retry indefinitely, is that correct? 

What is the best practice recommendation to know when all attempts have been exhausted, e.g. an OnGiveup event would be nice so I can remove the client from the connection pool.

**Comment by SeppPenner** [comment]
> What happens if the user/password credentials are changed AFTER a successful connection has occurred. I believe a publish of a message causes the connection to disconnect, and then when it tries automatically to reconnect it cannot. How many times will it try before giving up ?

This is something @chkr1011 needs to explain.

> Similarly, in normal use we are seeing that if a second connection connects using the same clientID, the first connection will disconnect and then retry. It appears to retry indefinitely, is that correct?

As far as I know, both connections will kick each other from time to time. You should never use the same client id twice with MQTT in any case...

> What is the best practice recommendation to know when all attempts have been exhausted, e.g. an OnGiveup event would be nice so I can remove the client from the connection pool.

Again something @chkr1011 needs to answer to you :)

**Comment by MattComb** [comment]
Thanks Hans, with regards to ClientID, we never do, unfortunately the MQTT Broker belongs to our customer, and they have a bad habit of connecting to it with another client.

once we get into this state, we enter a continuous connect/disconnect cycle that never recovers.

**Comment by SeppPenner** [comment]
> Thanks SeppPenner, with regards to ClientID, we never do, unfortunately the MQTT Broker belongs to our customer, and they have a bad habit of connecting to it with another client.

> once we get into this state, we enter a continuous connect/disconnect cycle that never recovers.

Ah, I see. This is something I didn't expect...

**Comment by chkr1011** [comment]
I assume this question is answered.
