### ISSUE TITLE
Can someone describe what the ConnectionCheckInterval is on the managed MQTT client?

### ISSUE THREAD

**Issue by djarvis** [dotnet/MQTTnet#768]
Is there somewhere where all these settings are actually documented, at least with just a sentence or two?  I can't find anything out there.

**Comment by SeppPenner** [comment]
Maybe https://github.com/chkr1011/MQTTnet/wiki/Server-and-client-method-documentation#managedclient? I know, the design of this page looks horrible, but for now I didn't find a solution to make it more beautiful.

I didn't see `ConnectionCheckInterval` when I documented the managed client. Which version are you referring to, by the way?

**Comment by djarvis** [comment]
ManagedMqttClientOptions.ConnectionCheckInterval was the setting I was referring to.  Version is 3.0.8.

Yes I have seen that page.

When the documentation says things like

WithCommunicationTimeout() : sets the communication timeout

it doesn't help very much to explain what that setting ACTUALLY does and what it actually means, how it relates to the very many other timeout settings, etc.

It would be wonderful for someone to go through all of these types of settings (all of the timeout/connection/delay type of settings) on the client and the server and be passionately descriptive in the explanations.

**Comment by SeppPenner** [comment]
I can understand that. I can update the documentation, I just can't tell you when I have the time for that. I wanted to contribute a lot more to this library, but sadly didn't have that much time yet.

**Comment by chkr1011** [comment]
The _ConnectionCheckInterval_ is the interval in which the managed client will check the connection status and reconnects if required. In other words: The client will reconnect every one second if required. If this leads to performance issues etc. this value can be changed but should not be usually. The default value is 1 second. 

Property descriptions are added soon.
