### ISSUE TITLE
How to handle disconnection in case of failure in incoming message processing in async scenario?

### ISSUE THREAD

**Issue by PayDrum** [dotnet/MQTTnet#778]
### Describe your question

Summary of my use-case: I have a consumer module which listens for mqtt messages on a certain topic. My module is not allowed to have persistence, because it must be able to run on hardware without any physical storage. In order to assure no messages are lost, I am manually handling the processingfailed boolean. The program also has to be async due to incoming http requests. 

So based on the current implementation of Mosquitto, in order for the broker to retry a message, the client has to disconnect and reconnect. Therefore, every time I fail to process a message, I manually call the disconnect on the client in the message handler. However, it appears that calling the disconnect will cause the message to be kept dangling in the mqtt client, and not to be retried later. Furthermore, this behavior doesnt seem consistent, as in sometimes theres a retry and sometimes there isnt. This even gets worse when max_inflight_messages is set to something more than 1 with a high rate of incoming messages. In case there's a disconnect, all the message tasks that have been pushed to the messagehandler will be left dangling. If the disconnection lasts long enough, the inflight_message limit will be hit and on the reconnection, there will be no more messages.

It is also worth noting that I have had to use async void for both the handlers, due to the fact that using async task leads to deadlocks.

Is there some way to handle this situation gracefully? or perhaps is this a bug on the client?

### Which project is your question related to?

- Client

**Comment by chkr1011** [comment]
Please test again with the latest version 4 and reopen this ticket if the error persists. A lot of things have changed in internal message handling.

**Comment by SimoneBWS** [comment]
With version 4, in case of error during message processing (notified with ProcessingFailed = false) is there always need to disconnect and connect again to receive the same message again?
