### ISSUE TITLE
cpu 100+% 

### ISSUE THREAD

**Issue by wangchaoit** [dotnet/MQTTnet#788]
English is poor
After using for a period of time, the usage rate of cpu will always exceed 100%.

**Platform:**

![image](https://user-images.githubusercontent.com/2391683/68104249-52334a80-ff15-11e9-874d-127955d94de4.png)

**Top:**

![image](https://user-images.githubusercontent.com/2391683/68104304-8a3a8d80-ff15-11e9-881a-a2b83bb760e3.png)

**Trace File:**

[trace.zip](https://github.com/chkr1011/MQTTnet/files/3802912/trace.zip)

**Comment by chkr1011** [comment]
Hi, 
do you have some logs maybe (Tracing is described in Wiki)? I cannot identify the root cause from high CPU load only.

Best regards
Christian

**Comment by pigwing** [comment]
@wangchaoit i have the same problem with you

**Comment by imperugo** [comment]
Same here!!!

**Comment by pigwing** [comment]
i think it is asp.net core websocket problem,when i have many websocket subscribe and many websocket client, it maybe crash cpu 100%

**Comment by imperugo** [comment]
I'm not using websockets and I've 100% CPU

**Comment by pigwing** [comment]
@imperugo di you publish in linux?

**Comment by imperugo** [comment]
Yes

**Comment by pigwing** [comment]
same to you,

**Comment by imperugo** [comment]
reading the release doc, this version https://github.com/chkr1011/MQTTnet/releases/tag/v3.0.10 seems to fix the problem

>Core] Fixed issue in closed socket detection (fixes high CPU load issue).

Need to try it

**Comment by mikaellindemann** [comment]
I have an instance of the MQTTNet broker running in a .NETCore 3 host (not webhost).
After some time it will start using more and more CPU, and it seems to correlate with the time where this kind of trace is made:

```
>> [2020-06-10T05:35:31.9664655Z] [15] [MqttClientSessionsManager] [Error]: Specified argument was out of the range of valid values.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MQTTnet.AspNetCore.SpanBasedMqttPacketBodyReader.ReadSegmentWithLengthPrefix()
   at MQTTnet.AspNetCore.SpanBasedMqttPacketBodyReader.ReadStringWithLengthPrefix()
   at MQTTnet.Formatter.MqttPacketFormatterAdapter.ParseProtocolVersion(ReceivedMqttPacket receivedMqttPacket)
   at MQTTnet.Formatter.MqttPacketFormatterAdapter.DetectProtocolVersion(ReceivedMqttPacket receivedMqttPacket)
   at MQTTnet.AspNetCore.ReaderExtensions.TryDecode(MqttPacketFormatterAdapter formatter, SpanBasedMqttPacketBodyReader reader, ReadOnlySequence`1& input, MqttBasePacket& packet, SequencePosition& consumed, SequencePosition& observed, Int32& bytesRead)
   at MQTTnet.AspNetCore.MqttConnectionContext.ReceivePacketAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Server.MqttClientSessionsManager.HandleClientConnectionAsync(IMqttChannelAdapter channelAdapter, CancellationToken cancellationToken)
```

```
>> [2020-06-10T05:35:42.0800685Z] [9] [MqttClientSessionsManager] [Error]: Specified argument was out of the range of valid values. (Parameter 'length')
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at MQTTnet.AspNetCore.SpanBasedMqttPacketBodyReader.ReadSegmentWithLengthPrefix()
   at MQTTnet.AspNetCore.SpanBasedMqttPacketBodyReader.ReadStringWithLengthPrefix()
   at MQTTnet.Formatter.MqttPacketFormatterAdapter.ParseProtocolVersion(ReceivedMqttPacket receivedMqttPacket)
   at MQTTnet.Formatter.MqttPacketFormatterAdapter.DetectProtocolVersion(ReceivedMqttPacket receivedMqttPacket)
   at MQTTnet.AspNetCore.ReaderExtensions.TryDecode(MqttPacketFormatterAdapter formatter, SpanBasedMqttPacketBodyReader reader, ReadOnlySequence`1& input, MqttBasePacket& packet, SequencePosition& consumed, SequencePosition& observed, Int32& bytesRead)
   at MQTTnet.AspNetCore.MqttConnectionContext.ReceivePacketAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Server.MqttClientSessionsManager.HandleClientConnectionAsync(IMqttChannelAdapter channelAdapter, CancellationToken cancellationToken)
```

From a CPU profiling session (this happens on my developer machine after some time as well) one thread going crazy. Furthermore most of the time is spent inside System.IO.Pipelines that seems to be called by MQTTNet.

![image](https://user-images.githubusercontent.com/359941/84231817-42a16300-aaef-11ea-8778-1c9662da8aa3.png)

For some reason it seems like my MQTT clients like to connect twice with the same ClientID causing a Takeover disconnect every few seconds - not sure if that is related.

**Comment by imperugo** [comment]
@chkr1011 any news on this issue?

**Comment by chkr1011** [comment]
@JanEggers I have no idea about the pipe stuff so I assume this is an issue for you 😄

**Comment by matteodav** [comment]
My MQTT server, updated with the new version of MQTTnet (3.0.12), continue to have the same problem (after one day of running, the usage rate of CPU always exceed 100%).
Somebody else? Or it is only my problem...

**Comment by imperugo** [comment]
Same here. Updated to latest version but nothing change

**Comment by JanEggers** [comment]
@imperugo @matteodav can you provide any details to track this down? my deployments are runnng for month / years without issues.

**Comment by zly243941866** [comment]
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
20287 root      20   0 4224108 142480  51604 S 199.7  1.8 864:34.25 dotnet

dotnet-dump


OS Thread Id: 0x7ded (16)
        Child SP               IP Call Site
00007F321BFFE520 00007F329EFFAB2A System.IO.Pipelines.Pipe.AdvanceReader(System.IO.Pipelines.BufferSegment, Int32, System.IO.Pipelines.BufferSegment, Int32) [/_/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs @ 555]
00007F321BFFE5D0 00007F329F020BAD System.IO.Pipelines.Pipe+DefaultPipeReader.AdvanceTo(System.SequencePosition, System.SequencePosition)
00007F321BFFE600 00007F329EFB9D75 MQTTnet.AspNetCore.MqttConnectionContext+<ReceivePacketAsync>d__37.MoveNext()
00007F321BFFE880 00007F329EFCF651 System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs @ 315]
00007F321BFFE8C0 00007F329FD2C37C System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[MQTTnet.AspNetCore.MqttConnectionContext+<ReceivePacketAsync>d__37, MQTTnet.AspNetCore]].MoveNext(System.Threading.Thread) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 654]
00007F321BFFE900 00007F329EBC5649 System.Threading.ThreadPoolWorkQueue.Dispatch() [/_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs @ 699]
00007F321BFFED10 00007f3312ceb5ef [DebuggerU2MCatchHandlerFrame: 00007f321bffed10] 


clrstack -a                                                                                                                                                                                                     
OS Thread Id: 0x7ded (16)
        Child SP               IP Call Site
00007F321BFFE520 00007F329EFFAB2A System.IO.Pipelines.Pipe.AdvanceReader(System.IO.Pipelines.BufferSegment, Int32, System.IO.Pipelines.BufferSegment, Int32) [/_/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs @ 555]
    PARAMETERS:
        this = <no data>
        consumedSegment = <no data>
        consumedIndex = <no data>
        examinedSegment = <no data>
        examinedIndex = <no data>

00007F321BFFE5D0 00007F329F020BAD System.IO.Pipelines.Pipe+DefaultPipeReader.AdvanceTo(System.SequencePosition, System.SequencePosition)
    PARAMETERS:
        this = <no data>
        consumed = <no data>
        examined = <no data>


00007F321BFFE600 00007F329EFB9D75 MQTTnet.AspNetCore.MqttConnectionContext+<ReceivePacketAsync>d__37.MoveNext()
    PARAMETERS:
        this (0x00007F321BFFE620) = 0x00007f32747dbec8

00007F321BFFE880 00007F329EFCF651 System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs @ 315]
    PARAMETERS:
        threadPoolThread = <no data>
        executionContext = <no data>
        callback = <no data>
        state = <no data>

00007F321BFFE8C0 00007F329FD2C37C System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[MQTTnet.AspNetCore.MqttConnectionContext+<ReceivePacketAsync>d__37, MQTTnet.AspNetCore]].MoveNext(System.Threading.Thread) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 654]
    PARAMETERS:
        this = <no data>
        threadPoolThread = <no data>

00007F321BFFE900 00007F329EBC5649 System.Threading.ThreadPoolWorkQueue.Dispatch() [/_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs @ 699]

00007F321BFFED10 00007f3312ceb5ef [DebuggerU2MCatchHandlerFrame: 00007f321bffed10] 
> clrstack -a                                                                                                                                                                                                     
OS Thread Id: 0x7ded (16)
        Child SP               IP Call Site
00007F321BFFE520 00007F329EFFAB2A System.IO.Pipelines.Pipe.AdvanceReader(System.IO.Pipelines.BufferSegment, Int32, System.IO.Pipelines.BufferSegment, Int32) [/_/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs @ 555]
    PARAMETERS:
        this = <no data>
        consumedSegment = <no data>
        consumedIndex = <no data>
        examinedSegment = <no data>
        examinedIndex = <no data>

00007F321BFFE5D0 00007F329F020BAD System.IO.Pipelines.Pipe+DefaultPipeReader.AdvanceTo(System.SequencePosition, System.SequencePosition)
    PARAMETERS:
        this = <no data>
        consumed = <no data>
        examined = <no data>

00007F321BFFE600 00007F329EFB9D75 MQTTnet.AspNetCore.MqttConnectionContext+<ReceivePacketAsync>d__37.MoveNext()
    PARAMETERS:
        this (0x00007F321BFFE620) = 0x00007f32747dbec8

00007F321BFFE880 00007F329EFCF651 System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs @ 315]
    PARAMETERS:
        threadPoolThread = <no data>
        executionContext = <no data>
        callback = <no data>
        state = <no data>

00007F321BFFE8C0 00007F329FD2C37C System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[MQTTnet.AspNetCore.MqttConnectionContext+<ReceivePacketAsync>d__37, MQTTnet.AspNetCore]].MoveNext(System.Threading.Thread) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 654]
    PARAMETERS:
        this = <no data>
        threadPoolThread = <no data>

00007F321BFFE900 00007F329EBC5649 System.Threading.ThreadPoolWorkQueue.Dispatch() [/_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs @ 699]

00007F321BFFED10 00007f3312ceb5ef [DebuggerU2MCatchHandlerFrame: 00007f321bffed10] 



setthread 15                                                                                                                                                                                                    
> clrstack                                                                                                                                                                                                        
OS Thread Id: 0x729 (15)
        Child SP               IP Call Site
00007F3238AC0BD0 00007F329EFF6E5F System.IO.Pipelines.Pipe.GetReadResult(System.IO.Pipelines.ReadResult ByRef) [/_/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs @ 863]
00007F3238AC0CB0 00007F329EFF6C0D System.IO.Pipelines.Pipe.ReadAsync(System.Threading.CancellationToken) [/_/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs @ 675]
00007F3238AC0DF0 00007F329EFF6AA2 System.IO.Pipelines.Pipe+DefaultPipeReader.ReadAsync(System.Threading.CancellationToken) [/_/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.DefaultPipeReader.cs @ 27]
00007F3238AC0E00 00007F329EFB966B MQTTnet.AspNetCore.MqttConnectionContext+<ReceivePacketAsync>d__37.MoveNext()
00007F3238AC1080 00007F329FD2C584 System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[MQTTnet.AspNetCore.MqttConnectionContext+<ReceivePacketAsync>d__37, MQTTnet.AspNetCore]](<ReceivePacketAsync>d__37 ByRef) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 1036]
00007F3238AC10C0 00007F329FD2C4C4 MQTTnet.AspNetCore.MqttConnectionContext.ReceivePacketAsync(System.TimeSpan, System.Threading.CancellationToken)
00007F3238AC1140 00007F329EFB834C MQTTnet.Server.MqttClientSessionsManager+<HandleClientConnectionAsync>d__24.MoveNext()
00007F3238AC13F0 00007F329EFB8133 System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[MQTTnet.Server.MqttClientSessionsManager+<HandleClientConnectionAsync>d__24, MQTTnet]](<HandleClientConnectionAsync>d__24 ByRef) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 1036]
00007F3238AC1460 00007F329EFB808B System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[MQTTnet.Server.MqttClientSessionsManager+<HandleClientConnectionAsync>d__24, MQTTnet]](<HandleClientConnectionAsync>d__24 ByRef)
00007F3238AC1480 00007F329EFB8030 MQTTnet.Server.MqttClientSessionsManager.HandleClientConnectionAsync(MQTTnet.Adapter.IMqttChannelAdapter, System.Threading.CancellationToken)
00007F3238AC1540 00007F329EFB7F69 MQTTnet.Server.MqttClientSessionsManager.HandleClientConnectionAsync(MQTTnet.Adapter.IMqttChannelAdapter)
00007F3238AC1570 00007F329EFB7ED5 MQTTnet.Server.MqttServer.OnHandleClient(MQTTnet.Adapter.IMqttChannelAdapter)
00007F3238AC1590 00007F329EFB74FF MQTTnet.AspNetCore.MqttConnectionHandler+<OnConnectedAsync>d__4.MoveNext()
00007F3238AC1680 00007F329EFB7273 System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[MQTTnet.AspNetCore.MqttConnectionHandler+<OnConnectedAsync>d__4, MQTTnet.AspNetCore]](<OnConnectedAsync>d__4 ByRef) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 1036]
00007F3238AC16F0 00007F329EFB71CB System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[MQTTnet.AspNetCore.MqttConnectionHandler+<OnConnectedAsync>d__4, MQTTnet.AspNetCore]](<OnConnectedAsync>d__4 ByRef)
00007F3238AC1710 00007F329EFB717C MQTTnet.AspNetCore.MqttConnectionHandler.OnConnectedAsync(Microsoft.AspNetCore.Connections.ConnectionContext)
00007F3238AC1780 00007F329AC89858 Microsoft.AspNetCore.Connections.ConnectionBuilderExtensions+<>c__DisplayClass0_0`1[[System.__Canon, System.Private.CoreLib]].<UseConnectionHandler>b__0(Microsoft.AspNetCore.Connections.ConnectionContext) [/_/src/Servers/Connections.Abstractions/src/ConnectionBuilderExtensions.cs @ 17]
00007F3238AC1790 00007F329AC899D0 Microsoft.AspNetCore.Connections.ConnectionBuilderExtensions+<>c__DisplayClass2_0.<Run>b__1(Microsoft.AspNetCore.Connections.ConnectionContext) [/_/src/Servers/Connections.Abstractions/src/ConnectionBuilderExtensions.cs @ 38]
00007F3238AC17A0 00007F329FD94F74 Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection+<ExecuteAsync>d__32.MoveNext()
00007F3238AC1850 00007F329FDAD1B4 System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection+<ExecuteAsync>d__32, Microsoft.AspNetCore.Server.Kestrel.Core]](<ExecuteAsync>d__32 ByRef) [/_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 1036]
00007F3238AC1890 00007F329FDAD109 Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.ExecuteAsync()
00007F3238AC18F0 00007F329FDAD0B6 Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.System.Threading.IThreadPoolWorkItem.Execute() [/_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelConnection.cs @ 181]
00007F3238AC1900 00007F329EBC5666 System.Threading.ThreadPoolWorkQueue.Dispatch() [/_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs @ 699]
00007F3238AC1D10 00007f3312ceb5ef [DebuggerU2MCatchHandlerFrame: 00007f3238ac1d10]

**Comment by chkr1011** [comment]
@JanEggers Isn't there already a fix in master for this?

**Comment by zly243941866** [comment]
> @JanEggers Isn't there already a fix in master for this?

v3.0.11

**Comment by JanEggers** [comment]
@chkr1011 I did change something that should have improved the behavior in case of invalid packets but I was never able to reproduce the 100% cpu in idle

**Comment by PavelFischerCoupa** [comment]
still have issue with sdk 3.1.405+, 5 and 6. But one need to put some load on the broker. Otherwise you can't run into the issue

**Comment by PavelFischerCoupa** [comment]
But in my case in MqttServerKeepAliveMonitor.DoWork

**Comment by GieltjE** [comment]
Been trying to gather some more information on this one for quite a few months now, here are my findings thus far:

- Nearly always happens on CPU constrained machines (either due to load or just old cpu's), newer machines don't seem to have as many issues with it
- Happens when running exclusively against localhost, no external connections
- Message processing is halted permanently when the CPU usage (at least 2 cores) maxes out
- Doesn't happen when the client talks to an external server (Mosquitto), this runs fine for months on end without issues
- Takes a long time, mostly 24h+ sometimes just a few hours, sometimes 48+ on our most frequent offender (2 clients 4 messages every 2 seconds)

We are using MQTT on localhost as IPC on windows simply isn't reliable when asynchronously sending messages, even when using external libraries.

We are more than happy to help run test builds on these machines in order to progress, running VS with debugging enabled is not an easy option though.

**Comment by chkr1011** [comment]
To me this sounds like a issue with the server in the first place. I created the branch "Fix-high-CPU-usage" with some changes in thread management. The server will now give the OS the chance to schedule other tasks/threads after each packet.

Please let me know if this changes the stability in any way.
You can use the nuget version x.x.x.210 from the MyGet feed. It includes the changes I already made.

**Comment by GieltjE** [comment]
Thnx, I'll run it on the most prone machine when the myget package hits .210 (.207 for now).
Many thanks for the response!

**Comment by chkr1011** [comment]
.210 is now available.

**Comment by GieltjE** [comment]
Deployed, let's see what it does over the weekend.

There is a monitoring tool running which logs and kills it if it goes awry so not much can go wrong.

**Comment by GieltjE** [comment]
First results look promising, less spikes and lower overall usage, will report back in a few more days to be sure.

**Comment by chkr1011** [comment]
Thanks for the feedback. I am on vacation next week so you can keep it running over the next week as well 😄

**Comment by GieltjE** [comment]
Enjoy your holliday, I'll be off after that so might be a while then 👍

**Comment by chkr1011** [comment]
Then just leave a comment before. If it already works good I can release a Bugfix version.

**Comment by GieltjE** [comment]
0 crashes so far (or any other issues), retained general lower cpu usage, I'd consider it stable for now :)

**Comment by GieltjE** [comment]
Back from holiday, no further issues detected, I'd consider it fixed.

**Comment by chkr1011** [comment]
Thank you for the feedback.
