### ISSUE TITLE
Cannot reconnect to restarted broker - MqttCommunicationException: Cannot access a disposed object

### ISSUE THREAD

**Issue by tamerin-tech** [dotnet/MQTTnet#803]
### Describe the bug
Connected to broker (rabbitmq),  after stopping and restarting the broker, the library throws an exception and does not reconnect.

> MQTTnet.Exceptions.MqttCommunicationException: Cannot access a disposed object.
> Object name: 'System.Net.Sockets.Socket'. ---> System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'System.Net.Sockets.Socket'.
>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
> --- End of stack trace from previous location where exception was thrown ---
>    at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
>    at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
>    at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
>    at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
>    at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
>    at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
>    at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.ReconnectIfRequiredAsync()

### Which project is your bug related to?
- ManagedClient

### To Reproduce
1. Using this version of MQTTnet '3.0.8'.
2. Run this code 'await _managedClient.StartAsync(_mqttOptions)'.
3. With these arguments '....'.
4. See error.

### Expected behavior
Should be able to reconnect after restarts of the broker

**Comment by hjsjy** [comment]
how to solve this problem

**Comment by chkr1011** [comment]
Please test with latest version 4 and reopen this ticket if the issue persists.
