### ISSUE TITLE
context.ReasonCode = MqttConnectReasonCode.BadUserNameOrPassword not working

### ISSUE THREAD

**Issue by pigwing** [dotnet/MQTTnet#807]
### Describe the bug
when is set context.ReasonCode = MqttConnectReasonCode.BadUserNameOrPassword;
and the mqttbox always connected and it can publish and subscribe some think

### Which project is your bug related to?

- Server v3.0.8

**Comment by SeppPenner** [comment]
I don't understand this... Can you provide a bit more of information, please?

**Comment by pigwing** [comment]
@SeppPenner i found the problem in the WithConnectionValidator i am use WithConnectionValidator(async context =>{}) this will lead to context.ReasonCode = MqttConnectReasonCode.BadUserNameOrPassword; not working

**Comment by SeppPenner** [comment]
@JanEggers Tell me if I miss something, but this bug needs to be somewhere around here, I would say: https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Server/MqttClientSessionsManager.cs#L269

**Comment by chkr1011** [comment]
Please make sure that the method properly returns a task or awaits other methods. Your code may be running in parallel so that your value is never used. Also checkout the new samples for version 4 for more information.
