### ISSUE TITLE
DisconnectedHandler Null exception

### ISSUE THREAD

**Issue by 1QuasiDev** [dotnet/MQTTnet#811]
**Bug**
I'm not able to get the Disconnection event args to know the Exception or AuthenticateResult which stay in null state.

**Project**
- Client

**To Reproduce**
Using 3.0.8:

> IMqttClient client;
> 
> this.options = new MqttClientOptionsBuilder()
> .WithTcpServer(ip, port)
> .WithCredentials(login, password)
> .WithClientId(ClientId)
> .WithCleanSession(true)
> .WithWillMessage(lastWill)
> .WithCommunicationTimeout(new TimeSpan(0, 0, 1))
> .WithKeepAlivePeriod(TimeSpan.FromSeconds(0.5))
>  .Build();
> 
> client = new MqttFactory().CreateMqttClient();
> client.DisconnectedHandler = new MqttClientDisconnectedHandlerDelegate(e =>
> {
>     ex = e.Exception;
> });
> 
> await mqtt.ConnectAsync(options, CancellationToken.None).ConfigureAwait(false);
> 

In case of disconnection, (broker down or bad login, or whatever the reason), the MqttClientDisconnectedEventArgs e values give the right ClientWasConnected state, but the Exception and AuthenticateResult stay null.

State of the MqttClientDisconnectedEventArgs in case of broker stop:
AuthenticateResult = null
ClientWasConnected = true
Exception = null

### Expected behavior
I would like to know the disconnected event reason.

**Comment by chkr1011** [comment]
Hi, thank you for reporting the issue.

Do you what exactly causes the disconnect? When the client disconnects via DISCONNECT packet the mentioned fields are null. This is by design.

**Comment by 1QuasiDev** [comment]
> Hi, thank you for reporting the issue.
> Do you what exactly causes the disconnect? When the client disconnects via DISCONNECT packet the mentioned fields are null. This is by design.

I've done two disconnection event tests:
- One by shuting down the broker
- Ther other with wrong credential (used a bad password)

**Comment by chkr1011** [comment]
Please retest with latest version 4 and reopen this issue if the problem persists.
