### ISSUE TITLE
Concurrent processing

### ISSUE THREAD

**Issue by ramonsmits** [dotnet/MQTTnet#812]
### Describe the feature request
Issue https://github.com/chkr1011/MQTTnet/issues/732 talk parallel processing which is also my request.

This is especially important under high load if the processor is also doing IO. Assume for example that due to IO processing duration is 200ms than only 5 messages per second is possible. 

Allow concurrent processing if the consumer requests this but have the default set to 1 which would result in sequential processing.

### Which project is your feature request related to?

- Client

### Describe the solution you'd like

Allow concurrent processing. The amount of allows concurrent processing should be limited by using for example `SemaphoreSlim`.

### Describe alternatives you've considered

There is a bad workaround possible by doing something like:
```c#
static SemaphoreSlim concurrencyLimit = new SemaphoreSlim(Environment.ProcessorCount * 4);

static async Task Handler(MqttApplicationMessageReceivedEventArgs ea)
{
    await concurrencyLimit .WaitAsync().ConfigureAwait(false);
    // Do NOT await, so task is forked but results in QoS 1 issues it task fails.
    Task.Run(async () =>
    {
        try
        {
            // Do your stuff here
        }
        catch
        {
        }
        finally
        {
            concurrencyLimit .Release();
        }
    });
}
```

But this solution has issues with QoS 1 as now the event handler ACK's already before actually completed.

**Comment by chkr1011** [comment]
I am already working on a new client which is mostly just a wrapper on top of a socket. It does not implement and use cases etc. So you can deal with all messages on your own and how you need it for your use cases. I don't think I can implement this in the client because some need the order (so no tasks) and some need it as fast as possible ignoring the order. I hope this helps. I hope to release that new client soon.

**Comment by ramonsmits** [comment]
@chkr1011 I understand that for some order is important so having the default be a concurrency limit of 1 to get sequential thus ordered processing would probably be a good idea.

> because some need the order (so no tasks)

For my understanding, what do you mean with the comment "so no tasks"?

**Comment by PMExtra** [comment]
Please reference my forked commit: https://github.com/PMExtra/MQTTnet/commit/d7704b1a7f8dfd422c17eeca86c53306953ba3a5

I've made a concurrent solution, but i have no idea about UnitTest. I've tested it in my project, it seems to work fine.

**Comment by ramonsmits** [comment]
@PMExtra Not entirely sure if your solution is thread-safe and also, it doesn't have any maximum concurrency control meaning you could potentially have thousands of concurrent tasks.

**Comment by PMExtra** [comment]
@ramonsmits I know, it's just a primary solution. Not production ready.

**Comment by ramonsmits** [comment]
@chkr1011 Has any progress made on this where mqttnet works reliably with QoS1, concurrent processing and PUBACK? I got burned last weekend because the handling of a message took a long time and other messages weren't processed. I can't just 'fire and forget' and need the reliability of QoS1.

**Comment by ramonsmits** [comment]
Looked at the code based and it seems that recently some related changes have been made but not yet released:

https://github.com/chkr1011/MQTTnet/blob/8f1d4e3c22f3226570eec681bccef3a88c4ebd16/Source/MQTTnet/MqttApplicationMessageReceivedEventArgs.cs#L49

Seems it should be used like maybe the following:

```c#
async Task Handle(MqttApplicationMessageReceivedEventArgs arg)
{
    arg.AutoAcknowledge = false
    _ = HandleInternal(arg).ContinueWith(t => arg.AcknowledgeAsync(CancellationToken.None));
```

This should result in concurrent execution but something is off....

**Comment by ramonsmits** [comment]
Created 2 tests in this PR: https://github.com/chkr1011/MQTTnet/pull/1151

**Comment by chkr1011** [comment]
I assume this is done. If no please reopen this ticket.
