### ISSUE TITLE
ConnectingFailedHandler doesnt follow the same approach?

### ISSUE THREAD

**Issue by i8beef** [dotnet/MQTTnet#822]
### Describe the bug
No extension methods to use additional client delegates like ConnectingFailedHandler

### Which project is your bug related to?
- Client
- ManagedClient

### To Reproduce
1. Create a client or ManagedClient and attempt to use the additional handlers by the apparent new format of UseConnectingFailedHandler, which doesn't exist.
2. See that other exposed handler methods also dont have accessors like ApplicationMessageProcessed, SKipped, etc.

### Expected behavior
In Pre 3.0 you could bind a handler to the ConnectionFailed event to log additional context, but I can't find how to do that now.

**Comment by chkr1011** [comment]
In version 4 all these events are now proper .net events supporting async tasks. Please test with latest version 4.
