### ISSUE TITLE
MqttServerConnectionValidator incorrect to handling of the ReasonCode

### ISSUE THREAD

**Issue by xljiulang** [dotnet/MQTTnet#834]
### Describe the bug
 
When the username and password are verified, clientA{clientId:id001,username:user001}has been connected and subscribed successfully, and then clientB {clientId: id001, username: someErrorUsername} request connection is rejected by `NotAuthorized ReasonCode`, but the subscription of clientA is affected, and clientA can no longer receive any messages.

### Which project is your bug related to?

- MQTTnet.AspNetCore v3.08

### To Reproduce
1. clientA connnect
2. clientB with the same id but an error username or paaword to connnect
3. rejecte clientB  by `NotAuthorized ReasonCode`,
4. query clientStatus by `IMqttServer.GetClientStatusAsync`
5. 0 client found in the server, but the clientA has a tcp connection with the server

### Expected behavior
clientA is not affected

**Comment by SeppPenner** [comment]
I'm not sure if this is a bug. In my understanding, both clients should be disconnected if another client with the same client id connects. What's your opinion on this @chkr1011 @JanEggers?

**Comment by xljiulang** [comment]
In some scenarios, the clientId is self increasing, and the validation rules depend on username and password. Other clientIds can be inferred based on the existing clientId ..

**Comment by SeppPenner** [comment]
> In some scenarios, the clientId is self increasing, and the validation rules depend on username and password.

Sure, but where's the problem? The client id should be unique in this scenario, I would say?

> Other clientIds can be inferred based on the existing clientId ..

What do you mean by that exactly? Do you have a concrete example?

I'm not really sure if it's possible to distinguish clients if their client id is the same... This is a question for someone else...

**Comment by xljiulang** [comment]
The problem is that when you guess someone else's client id without knowing its account and password, you can make this client Id inoperative

**Comment by SeppPenner** [comment]
> The problem is that when you guess someone else's client id without knowing its username and password, you can make this client Id inoperative

Good point. That's true...
