### ISSUE TITLE
MQTT PacketIdentifier is not exposed to library user

### ISSUE THREAD

**Issue by kiranpradeep** [dotnet/MQTTnet#837]
### Describe the feature request
Currently MqttClient [[1](https://github.com/chkr1011/MQTTnet/blob/8ecf658059c9fcb2e245210eebd24f870ab8bfc5/Source/MQTTnet/Client/MqttClient.cs#L25)] has packet identifier provider and so the identifier is not exposed to client (unlike libmosquitto[[2](https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_publish)]). 

Consider the case in which the client wishes to manage and clear messages from offline db on successful publish. Assume the client publishes 100 messages in a loop (without awaiting) and uses `Task.WhenAll` after the loop. Here, eventhough `MqttClientPublishResult` contains packet idenfifier, since it was not generated by client it doesn't know which message succeeded and which failed. 

### Which project is your feature request related to?
- Client. Maybe related to #600

### Describe the solution you'd like
Could an API be provided for the client to provide the identifier?

### Alternative considered
Client could still publish messages one by one, using await and based on the result it could clear the offline db. But the client is unable to to full advantage of parallelism offered by async/await.

**Comment by chkr1011** [comment]
The packet identifier will be available in version 4.1. The myget feed already contains this change.
