### ISSUE TITLE
Is there an example for Xamarin Forms?

### ISSUE THREAD

**Issue by biapar** [dotnet/MQTTnet#862]
Is there an example for Xamarin Forms?

### Which project is your feature request related to?
- Client
- ManagedClient
- Generic

**Comment by SeppPenner** [comment]
I haven't seen one yet. I don't have Xamarin installed on my machine (And I don't have that much time at the moment). Otherwise I would create one.

**Comment by biapar** [comment]
Do it work with it?

**Comment by SeppPenner** [comment]
> Do it work with it?

In general, it should work with Xamarin as well.

**Comment by JimmyPun610** [comment]
https://github.com/JimmyPun610/XF.Mqtt

I made one. but looks iOS have some problems.
