### ISSUE TITLE
ClientDisconnectedHandler  event occurs

### ISSUE THREAD

**Issue by danielstock** [dotnet/MQTTnet#929]
i used some managed clients connecting to the mqttnet server.
sometimes the server will encount ClientDisconnected event with  DisconnectType of notClean
all the clients use the same user/pwd but complete different clientids.
what doest it mean?  thanks.

 app.UseMqttServer(server =>
            {
                server.ClientConnectedHandler = new MqttServerClientConnectedHandlerDelegate(e =>
                {
                    System.Console.WriteLine("ClientId[" + e.ClientId + "] connected event fired.");
                });
                server.ClientDisconnectedHandler = new MqttServerClientDisconnectedHandlerDelegate(e =>
                {
                    System.Console.WriteLine("ClientId[" + e.ClientId + "] disconnected event fired, Reason=" + e.DisconnectType.ToString());
                });
.....

**Comment by danielstock** [comment]
my client code is as follows:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Timers;
using System.Threading.Tasks;
using System.Configuration;

using MQTTnet;
using MQTTnet.Client.Connecting;
using MQTTnet.Client.Disconnecting;
using MQTTnet.Client.Options;
using MQTTnet.Client.Receiving;
using MQTTnet.Extensions.ManagedClient;
using MQTTnet.Formatter;
using MQTTnet.Protocol;
using MQTTnet.Server;

namespace MQTTClientTest
{
    class MultiClients
    {
        private List<IManagedMqttClient> managedMqttClients = new List<IManagedMqttClient>();
        private Timer _timer = new Timer();

        string serverIP = ConfigurationManager.AppSettings["MQTTServer.Addr"];
        string serverPort = ConfigurationManager.AppSettings["MQTTServer.Port"];
        string serverUserId = ConfigurationManager.AppSettings["MQTTServer.UserId"];
        string serverPasswd = ConfigurationManager.AppSettings["MQTTServer.Passwd"];
        string serverTopic = ConfigurationManager.AppSettings["MQTTServer.Topic"];

        // start multiple clients
        public async void start(int clientsCount)
        {
            await Task.Factory.StartNew(async () =>
            {
                for (int i = 0; i < clientsCount; i++)
                {
                    string clientId = Guid.NewGuid().ToString();
                    var options = new ManagedMqttClientOptionsBuilder()
                     .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
                     .WithClientOptions(new MqttClientOptionsBuilder()
                         .WithClientId(clientId)
                         .WithCleanSession(true)
                         .WithTcpServer(serverIP, Convert.ToInt32(serverPort))
                         .WithCredentials(serverUserId, serverPasswd)
                         .Build()
                     )
                     .Build();

                    var c = new MqttFactory().CreateManagedMqttClient();
                    c.ConnectedHandler = new MqttClientConnectedHandlerDelegate(arg =>
                    {
                        System.Console.WriteLine("Client Connected");
                    });
                    c.DisconnectedHandler = new MqttClientDisconnectedHandlerDelegate(arg =>
                    {
                       System.Console.WriteLine("Client disconnected, ClientWasConnected=" + arg.ClientWasConnected.ToString());
                    });
                    c.ApplicationMessageReceivedHandler = new MqttApplicationMessageReceivedHandlerDelegate(arg =>
                    {
                        string payload = System.Text.Encoding.UTF8.GetString(arg.ApplicationMessage.Payload);
                        System.Console.WriteLine("Message received, topic [" + arg.ApplicationMessage.Topic + "], payload [" + payload + "], connectedCount=" + _connectedCount.ToString());
                    });

                    await c.SubscribeAsync(serverTopic, MqttQualityOfServiceLevel.AtLeastOnce);
                    await c.StartAsync(options);

                   managedMqttClients.Add(c);
                   
                    System.Threading.Thread.Sleep(200);
                }
            });

           /* _timer.Interval = 30000;
            _timer.Elapsed += new ElapsedEventHandler(timer_elapsed);
            _timer.Enabled = false;*/
        }//start

        public async void stop()
        {
            foreach(IManagedMqttClient c in managedMqttClients)
            {
                if (c.IsStarted)
                {
                    await c.StopAsync();
                }
            }
        }//stop

        private void timer_elapsed(object sender, ElapsedEventArgs e)
        {
            if (managedMqttClients.Count < 1)
                return;

            string strPayload = DateTime.Now.ToString();
            //IManagedMqttClient c = managedMqttClients[0];
            //c.PublishAsync(serverTopic, strPayload);           
        }       
    }
}

**Comment by danielstock** [comment]
it works well with clientsCountless than 50.
if  clientsCount is bigger than 100, lots of  ClientDisconnectedHandler -event  occurs in the server side.

what's the possible problem, thanks !

**Comment by danielstock** [comment]
the server side 's Program.cs:

public class Program
    {
        public static void Main(string[] args)
        {
#if DEBUG
           CreateHostBuilder(args).Build().Run();
#else
            var pathToExe = Process.GetCurrentProcess().MainModule.FileName;
            var pathToContentRoot = Path.GetDirectoryName(pathToExe);
            var host = WebHost.CreateDefaultBuilder(args).UseContentRoot(pathToContentRoot).UseStartup<Startup>().UseKestrel(
                o =>
                {
                    o.ListenAnyIP(Config.WsPort);
                    o.ListenAnyIP(Config.TcpPort, t => t.UseMqtt());
                }
                
                ).Build();
            host.RunAsService();
#endif
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                                .ConfigureWebHostDefaults(webBuilder =>
                                {
                                    webBuilder.UseStartup<Startup>().UseKestrel(o =>
                                    {
                                        o.ListenAnyIP(Config.WsPort);
                                        o.ListenAnyIP(Config.TcpPort, t => t.UseMqtt());
                                    });
                                });
    }

**Comment by danielstock** [comment]
startup.cs:


        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            Config.UserName = Configuration["MqttOption:UserName"];
            Config.Pwd = Configuration["MqttOption:Password"];
            
            services.AddControllers();
            services.AddHostedMqttServer(b => b.WithDefaultEndpointPort(Config.TcpPort)
            .WithConnectionBacklog(512)
            .WithConnectionValidator(context =>
            {
                if (Config.UserName != null && Config.Pwd != null)
                {
                    if (context.Username != Config.UserName || context.Password != Config.Pwd)
                    {
                        context.ReasonCode = MqttConnectReasonCode.BadUserNameOrPassword;
                        return;
                    }
                }
                context.ReasonCode = MqttConnectReasonCode.Success;
            })           
            );

            services.AddMqttConnectionHandler();

            services.AddMqttWebSocketServerAdapter();

            services.AddMqttTcpServerAdapter();       
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();            
            app.UseMqttEndpoint("/mqtt");
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
            app.UseMqttServer(server =>
            {
                server.ClientConnectedHandler = new MqttServerClientConnectedHandlerDelegate(e =>
                {
                    System.Console.WriteLine("ClientId[" + e.ClientId + "] connected event fired.");
                });
                server.ClientDisconnectedHandler = new MqttServerClientDisconnectedHandlerDelegate(e =>
                {
                    System.Console.WriteLine("ClientId[" + e.ClientId + "] disconnected event fired, Reason=" + e.DisconnectType.ToString());
                });
                server.ClientSubscribedTopicHandler = new MqttServerClientSubscribedHandlerDelegate(e =>
                {
                    System.Console.WriteLine("ClientId[" + e.ClientId + "] subscribe topic[ " + e.TopicFilter.Topic + "] event fired.");
                });
                server.ApplicationMessageReceivedHandler = new MqttApplicationMessageReceivedHandlerDelegate(e =>
                {
                    System.Console.WriteLine("ClientId[" + e.ClientId + "] message topic[ " + e.ApplicationMessage.Topic + "] event fired.");
                });

                MqttHelper.Server = server;
            });
        }

**Comment by danielstock** [comment]
the same situation happens when i changed the server program to mqttnet.server instead of mqttnet.net.core.

**Comment by smuellener** [comment]
I can see the same effect when creating many ManagedMqttClients (20+). I am using a mosquitto broker and a simple console application to create multiple ManagedMqttClients. The broker's log shows all clients to connect successfully at first but then starts to loose connections.

It looks to me like the connection handling on the ManagedMqttClient side is not optimized for handling multiple clients in the same process. Also the keep alive mechanism gets delayed to a point where connections are lost due to not sending keep alives in time.

@chkr1011 do you have an explanation for this effect? Should I try to create a repro repo?

**Comment by smuellener** [comment]
I suggest the bug label here

**Comment by danielstock** [comment]
@smuellener   thanks. so it's not the server problem, but the ManagedMqttClient ?

**Comment by danielstock** [comment]
@smuellener  @chkr1011 
i tried CreateMqttClient instead of managedClient.
it works well with more than 100 clients.

**Comment by chkr1011** [comment]
I assume this issue solved. Using lots of managed clients in a single application is not supported. The overhead of the managed client is to high. For such scenarios I suggest to use the regular client (which solved the issue).

**Comment by smuellener** [comment]
> I assume this issue solved. Using lots of managed clients in a single application is not supported. The overhead of the managed client is to high. For such scenarios I suggest to use the regular client (which solved the issue).

Question: What do you mean by „lots of“? What about two managed clients from within the same process? Thanks

**Comment by chkr1011** [comment]
Two should not be a problem depending on how much messages they produce. But 10, 50, 100 or event more may not work properly. Also please retest with version 4.0 and let me know if the stability is still an issue when using more managed clients in the same process.

**Comment by cholexa** [comment]
> Two should not be a problem depending on how much messages they produce. But 10, 50, 100 or event more may not work properly. Also please retest with version 4.0 and let me know if the stability is still an issue when using more managed clients in the same process.

I am using version 4.0, and have the same issue when the keepalive period from the client is 50+ seconds, CommunicationTimeout remains 100 seconds, I have not changed it
