### ISSUE TITLE
Best Implementation Document for ASP.Net Core

### ISSUE THREAD

**Issue by farazp** [dotnet/MQTTnet#942]
### Describe the feature request
I See and read Wiki page but there is not good document for implementing MQTT Service,
In Startup and CreateHostBuilder!
I'm am trying to do like this:
```
public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder
                    .UseKestrel(o => {
                        o.ListenAnyIP(1883, l => l.UseMqtt()); // MQTT pipeline
                        o.ListenAnyIP(5000); // Default HTTP pipeline
                    })
                    .UseIIS()
                    .UseStartup<Startup>();
                });
```
and in startup:

```
services.AddSingleton<MQTTService>();
services
                .AddHostedMqttServerWithServices(options => 
                {
                    var s = options.ServiceProvider.GetRequiredService<MQTTService>();
                    s.ConfigureMqttServerOptions(options);
                    options.WithDefaultEndpoint();
                    options.Build();
                })
                .AddMqttConnectionHandler()
                .AddConnections()
                .AddMqttTcpServerAdapter();
```

and Configure:
```
_ = app.UseMqttEndpoint();
 app.UseMqttServer(server => app.ApplicationServices.GetRequiredService<MQTTService>().ConfigureMqttServer(server));
```
also my service is:

```
public class MQTTService :
        IMqttServerClientConnectedHandler,
        IMqttServerClientDisconnectedHandler,
        IMqttServerApplicationMessageInterceptor,
        IMqttServerConnectionValidator,
        IMqttServerStartedHandler
    {
        IMqttServer mqtt;
        public void ConfigureMqttServerOptions(AspNetMqttServerOptionsBuilder options)
        {
            options.WithConnectionValidator(this);
            options.WithApplicationMessageInterceptor(this);
        }

        public void ConfigureMqttServer(IMqttServer mqtt)
        {
            this.mqtt = mqtt;
            mqtt.ClientConnectedHandler = this;
            mqtt.ClientDisconnectedHandler = this;
        }

        public Task HandleClientConnectedAsync(MqttServerClientConnectedEventArgs eventArgs)
        {
            return Task.Run(() => { });
        }

        public Task HandleClientDisconnectedAsync(MqttServerClientDisconnectedEventArgs eventArgs)
        {
            return Task.Run(() => { });
        }

        public Task HandleServerStartedAsync(EventArgs eventArgs)
        {
            return Task.Run(() => { });
        }

        public Task InterceptApplicationMessagePublishAsync(MqttApplicationMessageInterceptorContext context)
        {
            return Task.Run(() => { });
        }

        public Task ValidateConnectionAsync(MqttConnectionValidatorContext context)
        {
            return Task.Run(() => { });
        }
```

but I have two problem! one after some try to debug my project IIS Express say another Proccess on this port, I change Port number but not work. Two Can anyone publish good document for good and standard implementing of this?

### Which project is your feature request related to?
- ManagedClient
- MQTTnet.Server ASP.NET Core 
- Server
- Generic

I want this library to rise and most of best library for MQTT to run on any platform

**Comment by SeppPenner** [comment]
Well, I don't know where the error is here, but I can tell you that this works... Check out e.g. https://github.com/SeppPenner/NetCoreMQTTExampleDapperConfig. There, you can find that the code works properly.

I'm not sure if maybe `.UseIIS()` causes the problem in your case? But I'm not an expert for IIS / Kestrel to be honest.

**Comment by farazp** [comment]
> Well, I don't know where the error is here, but I can tell you that this works... Check out e.g. https://github.com/SeppPenner/NetCoreMQTTExampleDapperConfig. There, you can find that the code works properly.
> 
> I'm not sure if maybe `.UseIIS()` causes the problem in your case? But I'm not an expert for IIS / Kestrel to be honest.

I see that but problem is here, What is the best why for implementing!! and why get that error on changing the Port but not fix or conflicted with IIS or not!

**Comment by JimmyPun610** [comment]
Perhaps you should not use IIS. You may try to follow this which is not using IIS and working.
(I think the project configuration may do the trick)
https://github.com/JimmyPun610/MQTTnet.Playground/tree/master/MQTTnet.NetCore.Server

**Comment by farazp** [comment]
> Perhaps you should not use IIS. You may try to follow this which is not using IIS and working.
> (I think the project configuration may do the trick)
> https://github.com/JimmyPun610/MQTTnet.Playground/tree/master/MQTTnet.NetCore.Server

Thanks for your Post, this is good but after release, I want to hosted project in IIS and i think this should be using IIS! what you think?

**Comment by JimmyPun610** [comment]
> > Perhaps you should not use IIS. You may try to follow this which is not using IIS and working.
> > (I think the project configuration may do the trick)
> > https://github.com/JimmyPun610/MQTTnet.Playground/tree/master/MQTTnet.NetCore.Server
> 
> Thanks for your Post, this is good but after release, I want to hosted project in IIS and i think this should be using IIS! what you think?

If you use IIS, I think you can only use web socket to do it. It seems UseKestrel and UseIIS cannot be used at the same time. 

To do so, just forget about the settings in Program.cs in server code. Just use default is enough.
```C#
                    webBuilder
                    .UseStartup<Startup>();
```

To connect it, only web socket is allowed. the connection uri should be .
```
{host}:{port}/{mqttEndpoint}
```

**Comment by chkr1011** [comment]
I assume this question is answered.
