### ISSUE TITLE
Keep Alive not sent when device is not plugged to power source

### ISSUE THREAD

**Issue by AngeloLazzari** [dotnet/MQTTnet#951]
Hi, we created a Xamarin app and all is working correctly until the device is plugged to the power supply, but when we disconnect it, even with 100% battery, the client stop send the keepalive and the mqtt server disconnect it in a few seconds...

So, is that a problem this MQTTnet library or we need to treat the instance of the library class to be managed in a different way when in battery mode?

thank you very much!

**Comment by SeppPenner** [comment]
This sounds like some issue with background services / power saving options on the mobile device to me...

**Comment by AngeloLazzari** [comment]
Hi @SeppPenner , thank for the reply, but from the xamarin project I cannot manage or force the keepalive push of the library, or you are saying that the library does not check if the device is connected or not to the power source?

or do I have to instance the mqttnet library in a special way to tell the device operative system to do not kill that process? ...
thank you very much

**Comment by SeppPenner** [comment]
I'm not an expert for Xamarin... I'm not sure if this is an issue with the library or with Xamarin / your project or energy saving options in general.

> or do I have to instance the mqttnet library in a special way to tell the device operative system to do not kill that process? ...

I would assume that but I'm not sure.

**Comment by chkr1011** [comment]
I assume we cannot do much about this behavior in this library. Please check first how to execute certain tasks when a Xamarin application is suspended etc. due to power saving purposes. Apart from that you can try to avoid using keep alive since the client is simply not able support this.
