### ISSUE TITLE
Notification of messages not sent

### ISSUE THREAD

**Issue by paulvizard** [dotnet/MQTTnet#977]
Calling *PubishAsync* the a MQTTnet client when the server is not running still returns a success.  I understand that this is due to internal queuing by the client.  However, if I need to exit my application how can I determine which messages are queued and have not been sent?

```
var result = _mqttClient?.PublishAsync(message, CancellationToken.None).Result;
if (result?.ReasonCode == MqttClientPublishReasonCode.Success)
{
     // Gets here after server has been shutdown 
}

```

### Which project is your question related to?
- ManagedClient

**Comment by chkr1011** [comment]
You can check the property _PendingApplicationMessagesCount_ or make use of the event _ApplicationMessageProcessedAsync_ to see which message is already processed.
