### ISSUE TITLE
how to close auto reconnect function in MQTTnet3.0.11?

### ISSUE THREAD

**Issue by liaoliaoda** [dotnet/MQTTnet#986]
hi,

I want to close auto reconnect function in MQTTnet3.0.11, but the default reconnect time is 5 seconds. So how can I close this function?

**Comment by chkr1011** [comment]
You mean you warnt to disable that Feature?

**Comment by liaoliaoda** [comment]
> You mean you warnt to disable that Feature?

Hi @chkr1011 ,

yes, I want to realize reconnect function by myself in the callback function of OnMqttClientDisconnected.

**Comment by chkr1011** [comment]
I added this in master branch. Please let me know if this works for you.

**Comment by liaoliaoda** [comment]
> I added this in master branch. Please let me know if this works for you.

hi @chkr1011 ,

ok, I will try that and repply, thanks a lot.

**Comment by liaoliaoda** [comment]
Hi @chkr1011 ,

I setted WithoutAutoReconnect in MQTTnet3.0.13, but it failed when connect to server. Callback function did not work in OnMqttClientConnected OnMqttClientDisconnected and OnMqttClientConnectingFailed. 

So could you pls help to look into this case. Thanks a lot.

**Comment by chkr1011** [comment]
Please test with the latest version 4 and reopen this ticket if the issue still happens.
