### ISSUE TITLE
Client TLS options confusion

### ISSUE THREAD

**Issue by i8beef** [dotnet/MQTTnet#995]
### Describe your question
I'm a little confused on MQTT over TLS vs TLS authentication configuration... it seems like the two use cases are both sharing the `WithTls()` extension, but I'm unclear how all the settings apply to one or the other.

1. What is `UseTls` exposed for? Is this because `WithTls` is used for both connection encryption AND cert authentication, and instead of differentiating the two we needed a way to say "the config here is JUST to setup a client cert"?
2. Is `certificates` ONLY for TLS authentication certs? I.e., you can't inject CA certs to avoid using the 'AllowUntrustedCertificates', `IgnoreCertificateChainErrors` and `IgnoreCertificateRevocationErrors` settings or validation callbacks?
3. Does everything else under MqttClientOptionsBuilderTlsParameters apply only to MQTT over TLS encryption?

This seems like two things are conflated under the same builder, connection encryption settings, and authentication... am I mistaken?

### Which project is your question related to?

- Client
- ManagedClient

**Comment by chkr1011** [comment]
Yes both things are covered in one area of the options. The reason is that they are also combined in the underlying .net framework. So you always need to use a TLS stream in order to use a client certificate at all. There is no way of doing this without a TLS connection.
